### ISSUE TITLE
LTM - Add telemetry support

### ISSUE THREAD

**Issue by sppnk** [iNavFlight/inav-configurator#1]
With a future support of LTM the iNav-configurator could be used also as GCS. Maps, logging in real time and other tetelemetry features.

**Comment by skaman82** [comment]
this is great. It would be also very cool to have a tab to set up a mission

**Comment by sppnk** [comment]
Yes, and everyday more systems work with LTM. Take a look to last release of [minimosd] (https://github.com/ShikOfTheRa/scarab-osd/releases/tag/v1.6.1.0)

**Comment by sppnk** [comment]
closing. I have open #156

**Comment by DzikuVx** [comment]
@sppnk I'm reopening this one since this is more likely to happen than FrSky or SmartPort

**Comment by sppnk** [comment]
ok, great

**Comment by MrD-RC** [comment]
LMT is in configurator
