### ISSUE TITLE
No Serial RX Setup

### ISSUE THREAD

**Issue by Neuroplant** [iNavFlight/inav-configurator#1003]
I setup a new Matek F722-SE 2.4.0 Taget 
(version
 INAV/MATEKF722SE 2.4.0 Feb 11 2020 / 22:53:38 (bcd4caef9)
 GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074])
and can not find setings for the Serial RX (ibus in my case) in configuraton Tab
 (FC only connected to USB at the Moment)
<img width="485" alt="No RX Setup" src="https://user-images.githubusercontent.com/25515618/82724464-b6adcf80-9cd6-11ea-9e04-fba708d454d7.PNG">

**Comment by DzikuVx** [comment]
Receiver configuration was moved to the Receiver tab
