### ISSUE TITLE
FEATURE REQUEST: Ability to load a config dump (or diff all) offline

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#1005]
It would be nice to be able to open up inav configurator "offline" (IE Without an FC plugged in) to be able to read the settings that you have easier than trawling through a config dump and decoding it.

this would be useful for checking what ports you have setup for what devices, your mixers and modes etc without having to plug in the plane. For example. if you want to show someone what you have setup in the mixer for a specific aircraft and issue, then you currently have to get the a/c plug it in etc just to take a screenshot.

Having this would be great to do something like that. The other reason is if you redo all the wiring for things like receivers and gps etc, and you can't remember what ports you had them plugged in to it can be handy for reference to just have it able to be loaded up.

Hope that makes sense

**Comment by DzikuVx** [comment]
As this idea makes sense I can say that due to how this app is built and communicates with a FC, this will never be implemented. It would require either app rewrite or some kind of FC simulator and both are too big to be implemented
