### ISSUE TITLE
Compass Callibration

### ISSUE THREAD

**Issue by nosyninja** [iNavFlight/inav-configurator#1007]
SP Racing F3 Compass does not calibrate. They magzero values remain set to 0, I also moved to cli tab to check there but magzero values are all 0. (get magzero)

I tried setting values manually to numbers other than 0 in the Cli. Calibration sets them back to 0! It seems no matter what I do, the calibration wants to set everything to zero

The mag works I get values and it shows the correct direction, I guess it's a firmware issue.

**Comment by DzikuVx** [comment]
This is  fixed in 2.5 final
