### ISSUE TITLE
FeatureRequest: Dynamically regulate throttle limit with spare aux channel

### ISSUE THREAD

**Issue by WizzX-FPV** [iNavFlight/inav-configurator#1008]
## Desired Behavior
Possibility to adjust throttle limit with spare potentiometer knob on your transmitter via spare aux channel. Even in 3D mode. 

For example inf knob is in "min" position (1000ms), than max throttle can be limited to 50% but with full resolution of throttle stick. And if knob on max (2000ms) than no limit for throttle.

I know it is possible to set it directly on transmitter, but than you loosing resolution of full throttle stick movement which is disadvantage on crawlers where you use only 20% or even less of max throttle during crawling.

* Can be used also on cinewhoops to set precise maximum throttle to reach smooth acceleration, but 
 also for rovers with reversible motor.

* Also if i can imagine that on rover you will use 3 way switch which will define 3 possible speeds limits (20%/55%/100%) what acts like a gearbox on car.

## Suggested Solution
add 3 "data entry" boxes to INAV configuration to use dynamic throttle:
1: select aux channel
2: throttle limit min %
3: throttle limit max %

![Untitled](https://user-images.githubusercontent.com/40316777/83028788-2fdc5800-a032-11ea-9c56-fb20b1bfab71.png)

If someone want to use old "fixed" way of throttle limit than he just not select any AUX channel and "throttle limit min" will stays inactive (grayed) and only "throttle limit max" can be filled.

## Who does this impact? Who is this for?
I can imagine advantage for all 
* on drones - turn down max throttle for beginners or if you go to fly indoor or more precizer gaps
* on rovers - limit max motor speed for precise low speed regulation during crawling.
* rover indoor or for children

**Comment by DzikuVx** [comment]
This can be done with logic conditions:

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/966811/158176384-324d9233-30d9-4f9b-b2e5-0deb2486e2a1.png">

Closing, thanks for suggestion
