### ISSUE TITLE
Magnetometer inverted?

### ISSUE THREAD

**Issue by Justin-J-Morgan** [iNavFlight/inav-configurator#1009]
Hello, took my wing out for a maiden today. I noticed that the magnetometer is inverted (North shows South and rotation looks reversed.) Which I think means the chip is on what I _thought_ was the bottom of the board... Is the a way to invert the compass in the configurator already? or a way to add one?

**Comment by digitalentity** [comment]
Yes, look at magnetometer alignment setting

**Comment by Justin-J-Morgan** [comment]
Where is that option/setting? I can't find it as a toggle, so is it only accessible through CLI?

**Comment by Justin-J-Morgan** [comment]
I found it in the CLI. took a bit of fiddling, but figured it out. Thank you!
