### ISSUE TITLE
Servo settings 2.5 speed and reverse not stored

### ISSUE THREAD

**Issue by DietmarM** [iNavFlight/inav-configurator#1021]
I tried to save in a tricopter with a second servo the Speed rate and revers direction - Speed was shown with -56 afterwards.

**Comment by DzikuVx** [comment]
Please provide version strings for Configurator and Firmware as well as a CLI dump where this can be reproduced

**Comment by DzikuVx** [comment]
Just tested with 2.5 and can not reproduce
