### ISSUE TITLE
Betaflight-like PID Tuning Sliders

### ISSUE THREAD

**Issue by tenten8401** [iNavFlight/inav-configurator#1026]
Is there a chance we could get pid and filtering sliders similar to how Betaflight has them? Me and a lot of others I know find them really useful for tuning, would love to see them in iNav.
![image](https://user-images.githubusercontent.com/6174343/85212625-abc07c00-b322-11ea-844a-03a1a9b73d35.png)
![image](https://user-images.githubusercontent.com/6174343/85212626-afec9980-b322-11ea-9f8e-cc1c0a4f63dd.png)

**Comment by MrD-RC** [comment]
Sliders in 5.0.
