### ISSUE TITLE
matek f405 wing engine running after 50% throttle

### ISSUE THREAD

**Issue by jetstream123** [iNavFlight/inav-configurator#1031]
Hello i have just bought an matek f405 wing and flashed with latest inav, when i try to test the engine from outputs page it starts to turn after 50% throttle how can i solve this? I have been trying to fix the issue for 2 days and i cant find any solution hope someone can help.

**Comment by giacomo892** [comment]
This is not a support channel. Still calibrate the ESCs or use DSHOT150.
