### ISSUE TITLE
Nav Mac APP 0.9.11

### ISSUE THREAD

**Issue by flyinginger** [iNavFlight/inav-configurator#1055]
## Current Behavior
feature in CLI
motor_direction_inverted = ON
does not work

CLI
when diff all
cannot save to (even)desktop

Blackbox
App crashes when flashing memory

---

- FC Board : flywoo Goku f7 mini:
- INAV version string: Mac app 0.9.11 (2.5.0)

**Comment by flyinginger** [comment]
Mac App issue, when air mode permanent, throttle sky rocket to the moon... if air mode is anable in combinaison with angle or else flight mode, all is ok

**Comment by richard-scott** [comment]
I've just had a rocket to the moon, I had 3 pos switch for channel 7, in pos 1 and 2 I think it was ok, but then when I flipped to pos3 I went up and up and up.

<img width="1259" alt="Screenshot 2022-07-07 at 10 05 31" src="https://user-images.githubusercontent.com/5149834/177736154-57909a6b-4005-4977-94e7-7841583bbbb0.png">
.

**Comment by MrD-RC** [comment]
Rocket to the moon is not an issue with the platform the configurator is running on. It is the setup of the quad, possibly too high an idle throttle. That was unrelated to the original question too.

As for the original question. `motor_direction_inverted = ON` does not reverse the motors. You need to do that on the ESCs. It just tells INAV that you have reversed the motors. In 5.x it also updates the motor direction graphic.
