### ISSUE TITLE
iFlight SucceX-E F4 Stack is listed on Release page but no target

### ISSUE THREAD

**Issue by ircmgr** [iNavFlight/inav-configurator#1057]
iFlight SucceX-E F4 Stack can be seen in the recommended hardware list but while trying to flash only 
IFLIGHTF4- TWIG and IFLIGHTF7-TWING targets exist ( tried the F4 and it doesnt work )

**Comment by BrianKoch1** [comment]
Is there a solution for this board yet?

**Comment by theuglycamel** [comment]
Also looking for this target.  The V1 board uses the BETAFLIGHT_F4 target but the v2.1 uses IFLIGHT_SUCCEX-E F4.  The V2.1 is a much more iNav friendly board with baro and i2c.  Please advise.

**Comment by bakwc** [comment]
Same here. Is it possible to run inav on "iFlight SucceX-E F4 V2.1" (SucceX-E F405)?

**Comment by ryanort** [comment]
> Same here. Is it possible to run inav on "iFlight SucceX-E F4 V2.1" (SucceX-E F405)?

+1

**Comment by ucflumm** [comment]
+1 Tried flashing it but it only shows 3 UART and exhibits strange behaviour i'm guessing i got the wrong target.

**Comment by ucflumm** [comment]
I'll attempt to make a target, but I've never done it for iNAV/betaflight or anything. I've done it for 3D printer boards using STM32 so I'll give it a shot. 
iflightf4_succexe/target.c
                            target.h

Does anyone know if there are other references to these (in iNAV/configurator) I need to add/check anywhere. I could find it with time but I think it would be easier to ask.

Sorry if I'm asking noob questions; I just feel it's alot better to help write it and test instead of asking.

**Comment by ivan586lp** [comment]
I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h)

Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)

If you try, please be careful :)

Link to archive (compiled firmware hex file and target.h):

https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing

**Comment by ucflumm** [comment]
> I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h) for iFlight SucceX-E F4 V2.1
> 
> Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)
> 
> If you try, please be careful :)
> 
> Link to archive (compiled firmware hex file and target.h):
> 
> https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing

Awesome save me heaps of time I'll try it out this weekend!

**Comment by bakwc** [comment]
Successfully flashed, have not tested yet.
I am missing barometer values (may be my board without barometer, or it just not detected, I can't setup it in beta-flight too).
Any ideas how to make baro works?

**Comment by ucflumm** [comment]
Is it showing up as red or is it greyed out?

**Comment by bakwc** [comment]
> Is it showing up as red or is it greyed out?

Red

**Comment by ucflumm** [comment]
Have you tried a full power off. Mine was red when I connected to usb first. Disconnect usb and power. Then connect battery after that plug in the usb to see if that fixes it.

**Comment by TarasTadva** [comment]
Hey! Please explain how to add a target to the configurator yourself? I successfully flashed the flight controller with the suggested HEX file, but did not use the target at all. This is mistake?

**Comment by ucflumm** [comment]
The target is used to create the hex file. Please be careful flashing verify it works first.

**Comment by nwpulver** [comment]
> 
> 
> > I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h) for iFlight SucceX-E F4 V2.1
> > Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)
> > If you try, please be careful :)
> > Link to archive (compiled firmware hex file and target.h):
> > https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing
> 
> Awesome save me heaps of time I'll try it out this weekend!

I am having an issue with this target  - ESC not talking to FC. Not sure what the deal is because it works on betaflight. Anyone else have this problem?

**Comment by ucflumm** [comment]
> > > I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h) for iFlight SucceX-E F4 V2.1
> > > Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)
> > > If you try, please be careful :)
> > > Link to archive (compiled firmware hex file and target.h):
> > > https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing
> > 
> > 
> > Awesome save me heaps of time I'll try it out this weekend!
> 
> I am having an issue with this target - ESC not talking to FC. Not sure what the deal is because it works on betaflight. Anyone else have this problem?
> 
> to elaborate: I am not getting the second set of beeps when plugging in battery. I cannot move motors with outputs tab. In betalfight this is no problem.

Did you set the motor protocol dshot600 ? Won't beep if its not set i think.

**Comment by theuglycamel** [comment]
Successfully tested 04/24/21 on fixed wing.  Thank you for the conversion!

**Comment by nwpulver** [comment]
> 
> 
> > > > I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h) for iFlight SucceX-E F4 V2.1
> > > > Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)
> > > > If you try, please be careful :)
> > > > Link to archive (compiled firmware hex file and target.h):
> > > > https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing
> > > 
> > > 
> > > Awesome save me heaps of time I'll try it out this weekend!
> > 
> > 
> > I am having an issue with this target - ESC not talking to FC. Not sure what the deal is because it works on betaflight. Anyone else have this problem?
> > to elaborate: I am not getting the second set of beeps when plugging in battery. I cannot move motors with outputs tab. In betalfight this is no problem.
> 
> Did you set the motor protocol dshot600 ? Won't beep if its not set i think.

I did. I now notice that I get the second set of beeps on reboot as it is rebooting but it does not happen otherwise. Using BLHeliS and bluejay firmware

**Comment by lavachemist** [comment]
@digitalentity did you know that the release tag 2.6.1 for INAV configurator recommends an FC that has no INAV target?

https://github.com/iNavFlight/inav-configurator/releases/tag/2.6.1

**Comment by jandaliba** [comment]
Same here... I bought it based on recomended HW and now I do not have a target... Just perfect...

**Comment by mimoklepes** [comment]
I've complied the target using target.h from ivan586lp with INAV 3.0.0 RC1 and tested today by doing 2 battery packs on a 5" quad (Nazgul5 + BN-880 GPS). So far everything seems to work great.

**Comment by EchoReeper** [comment]
> I've compiled the target using target.h from ivan586lp with INAV 3.0.0 RC1 and tested today by doing 2 battery packs on a 5" quad (Nazgul5 + BN-880 GPS). So far everything seems to work great.

I just got the shared file ivan586lp (thank you sir) to work, is there a way you can share the 3.0 version please?

**Comment by mimoklepes** [comment]
> I just got the shared file ivan586lp (thank you sir) to work, is there a way you can share the 3.0 version please?

sure, [here you go](https://drive.google.com/file/d/1IKo4rn5m6UVKGCpeJKJxkf_ezd2D1M0S/view?usp=sharing)

It is built from 3.0.0 RC1. In the meantime I've tested it for a couple of hours of flight time and everything was fine, so I'm not going to bother rebuilding it from RC2, I'll wait for the final version. 

Just one warning: The very first attempt almost ended with a disaster - the quad started to add throttle by itself, I had to quickly disarm it mid-air (it was already some 3 meters above the ground), otherwise it would just fly away. I guess the problem was that I did "diff all" on the 2.6.0 version and applied everything blindly to 3.0.0.

The second time I started from scratch using a preset from configurator and only copied the "harmless" parts of the diff like OSD, modes, rates, etc. Zero problems since then.

**Comment by EchoReeper** [comment]
> > I just got the shared file ivan586lp (thank you sir) to work, is there a way you can share the 3.0 version please?
> 
> sure, [here you go](https://drive.google.com/file/d/1IKo4rn5m6UVKGCpeJKJxkf_ezd2D1M0S/view?usp=sharing)
> 
> It is built from 3.0.0 RC1. In the meantime I've tested it for a couple of hours of flight time and everything was fine, so I'm not going to bother rebuilding it from RC2, I'll wait for the final version.
> 
> Just one warning: The very first attempt almost ended with a disaster - the quad started to add throttle by itself, I had to quickly disarm it mid-air (it was already some 3 meters above the ground), otherwise it would just fly away. I guess the problem was that I did "diff all" on the 2.6.0 version and applied everything blindly to 3.0.0.
> 
> The second time I started from scratch using a preset from configurator and only copied the "harmless" parts of the diff like OSD, modes, rates, etc. Zero problems since then.

Thanks so much! I just loaded and the motors spin (I didn't copy and paste anything over, thanks' for the tip). I will test and report back if anything happens, etc.. off to test

**Comment by Dave4675** [comment]
Hi everybody, thanks to 

> 
> 
> I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h) for iFlight SucceX-E F4 V2.1
> 
> Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)
> 
> If you try, please be careful :)
> 
> Link to archive (compiled firmware hex file and target.h):
> 
> https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing

Thanks, I used the target file to compile inav 3.0 :) 
I'm posting the zip file that contain the hex file.

[inav_3.0.0_IFLIGHT_SUCCEX_E_F4_2_1.hex.zip](https://github.com/iNavFlight/inav-configurator/files/6701757/inav_3.0.0_IFLIGHT_SUCCEX_E_F4_2_1.hex.zip)

**Comment by Ajaxwars** [comment]
Доброго времени суток всем.
Спасибо за работу над этой прошивкок.
Но есть проблема, которую не могу решить.
Прошивка заливается нормально, всё настраивается, иду полетать, всё работает кроме правого стика, ролл и питч не отвечают.
На компьютере  в программе всё работает значения меняются.
А в полёте только взлетает и нельзя никуда повернуть.
Аппа радиомастер tx16s.
Бетафлайт всё работает как надо, Летаю.
Помогите пожалуйста.

**Comment by olegshty** [comment]
> Hi everybody, thanks to
> 
> > I managed to modify the target BETAFLIGHT_F4 (src / main / target / BETAFLIGHTF4 / target.h) for iFlight SucceX-E F4 V2.1
> > Yesterday I took off on a drone (on version 2.6.0), did not test for a long time, but the GPS holds the position, the flight is stable, the acro is working, all functions are working (barometer, GPS, Compass)
> > If you try, please be careful :)
> > Link to archive (compiled firmware hex file and target.h):
> > https://drive.google.com/file/d/1-wDzZs2W_LAJGBvbQVb52oV7JjGyI9DB/view?usp=sharing
> 
> Thanks, I used the target file to compile inav 3.0 final :)
> I'm posting the zip file that contain the hex file.
> 
> [inav-iflight-succex-e-v2.1.zip](https://github.com/iNavFlight/inav-configurator/files/6701769/inav-iflight-succex-e-v2.1.zip)

Thank you for a great job, but there is a mistake in resources:
In your HEX B05: LED1 OUT
But for real LED1 OUT is B06
Could you please correct this...?

**Comment by Mcbeen** [comment]
> Successfully tested 04/24/21 on fixed wing. Thank you for the conversion!

@theuglycamel That sounds awesome. Would love to be able to do that. But where did you connect your servos? Motor outputs 3 & 4? Did you just use Dave4675's target or..? Would love to know. Thanks already!

**Comment by MrD-RC** [comment]
Stale closing. For official targets to be added to INAV. Manufacturers should follow [these rules](https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md). If a target for a flight controller does not exist. Contact the manufacturer and as them to get an INAV target made and approved.
