### ISSUE TITLE
INAV OSD for SP Racing F3

### ISSUE THREAD

**Issue by Drone-pilot** [iNavFlight/inav-configurator#1088]
Implement support in the SP Racing F3 firmware for an external OSD based on MinimOSD, for configuration via the INAV Configurator.

**Comment by DzikuVx** [comment]
We will not work on this. There is extarnal application for configuring MWOSD and similar. Both SPRF3 and minimOSD are basically end of life technologies

**Comment by Drone-pilot** [comment]
Cleanflight and Betaflight have implemented minimosd support on spracing f3, although they also stop supporting F3 series firmware updates. Please implement, it shouldn't be difficult.

**Comment by Drone-pilot** [comment]
Cleanflight and Betaflight have implemented minimosd support on spracing f3, although they also stop supporting F3 series firmware updates. Please implement, it shouldn't be difficult.

**Comment by Drone-pilot** [comment]
![IMG_20201014_204419_310](https://user-images.githubusercontent.com/73273876/97038577-b494b900-1573-11eb-8d71-28de44314027.jpg)
![IMG_20201014_071541_221](https://user-images.githubusercontent.com/73273876/97038618-bf4f4e00-1573-11eb-83b0-11ad2c1e9ab6.jpg)
