### ISSUE TITLE
Add RTH Home Altitude to the configurator

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#1094]
For fixed wing pilots, this is a helpful feature. Especially for pilots who fly high. It would be useful to have RTH Home Altitude in the GUI.

I'm going to have a go implementing this. I'm sure I have most of it worked out, but will test tomorrow. Just leaving this here in case I can't assign it to myself.

**Comment by DzikuVx** [comment]
@MrD-RC please rework it to the way it's done in #1020 with settings framework. Bear in mind you have to start from scratch as Adsvanced Tab code was just changed

**Comment by MrD-RC** [comment]
So just to confirm, all you need to do now is setup the text in the locale. Then for the variable on the FC, you set the data-setting on the html input to the CLI command variable name, and it all just works. If so, awesome. That's so much simpler.
