### ISSUE TITLE
Change color of progress bar from green to fancy blue

### ISSUE THREAD

**Issue by theArchLadder** [iNavFlight/inav-configurator#11]
After poking around and running some search scripts i finally manage to find what controls the color of the progress bars in the firmware flasher

https://github.com/iNavFlight/inav-configurator/blob/master/tabs/gps.css#L122
Yes, in the gps.css, makes sense... NOT!

Not sure what fancy blue color code to use here, perhaps @skaman82 would like to do his magic touch on this one?

**Comment by theArchLadder** [comment]
These where all the green colors my script found in inav-configurator, in case this is helpful to anyone...
![scrot_20160525-192341](https://cloud.githubusercontent.com/assets/11679497/15549726/41ff55ec-22ae-11e6-9d39-b869c89a713c.png)

**Comment by skaman82** [comment]
thanks, done in https://github.com/iNavFlight/inav-configurator/pull/12

**Comment by skaman82** [comment]
The blue color should be #39a9dc by the way

**Comment by skaman82** [comment]
This was a quick fix for the moment. I will move that styling later to a file that makes actually sense.

**Comment by theArchLadder** [comment]
Yay! I have been coding inav and flashed and test flown a ton of times and every time my eyes have been bleeding because of that green progress bar, no more though! My eyes will be so happy :smile:

**Comment by skaman82** [comment]
closing

**Comment by digitalentity** [comment]
@skaman82 thanks!
