### ISSUE TITLE
Select 50% for Black Box logging rate, reboots and shows 25% logging rate

### ISSUE THREAD

**Issue by wkiskin-teladoc** [iNavFlight/inav-configurator#1115]
This issue is for [https://github.com/iNavFlight/inav-configurator/releases/tag/2.6.0-RC1](url) 

When I select any rate above 25% logging rate and click reboot, it come back at 25% logging rate.
selected -> displayed
1/32        -> 1/32            blackbox_rate_denom = 32
1/16         -> 1/16            blackbox_rate_denom = 16
1/8           ->  1/8            blackbox_rate_denom = 8
1/5           ->  1/5            blackbox_rate_denom = 5
1/4           ->  1/4            blackbox_rate_denom = 4
1/3           ->  1/4            blackbox_rate_denom = 4
1/2           ->  1/4            blackbox_rate_denom = 4
2/3          ->  1/4             blackbox_rate_denom = 4
all values above 1/4 logging rate all set to 1/4 logging rate.

It is not possible to set the logging rate in the CLI above 1/4, it always resolves to 25%V logging rate with blackbox_rate_denom = 4 

Behavior should be it comes back at the selected rate  and should be able to set blackbox_rate_denom in teh CLI

**Comment by avsaase** [comment]
This was implemented in https://github.com/iNavFlight/inav/pull/6127 to avoid problems with logging too much data.

**Comment by DzikuVx** [comment]
Like @avsaase wrote: we preven logging faster than 1kHz to prevent many issues including stopping motors and falling down from the sky

**Comment by wkiskin-teladoc** [comment]
Thank you... It was not apparent to me from using the UI.

Can you just limit the rate options in the dropdown so it "acts" appropriately?

Cheers,

Bill
________________________________

**Comment by IgnacioHR** [comment]
Hi, Is this still an issue with new H7 processors in place?

I'm having an issue with a new 5" drone. As you can see in the picture, front engines suddenly goes up the same amount rear engines goes down! The PID reacts to correct the situation. I still don't know what is the source of the issue so I tried to record in the blackbox at higher rate to see more information and hit this "bug/feature".

iNav is running in a new H7 processor so I guess this processor could handle higher rates (I might be wrong).

I'm adding this information here just in case you think it would make sense to allow for higher rates depending on the FC processor.

<img width="1723" height="1055" alt="Image" src="https://github.com/user-attachments/assets/f279a21d-e921-4dda-98fa-a164555da7f2" />

I'll continue my research regarding the engines...
