### ISSUE TITLE
Add !Logic Condition X in Active columns *Feature Request*

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#1120]
## Current Behaviour
Currently in the mixer and programming, there is an **Active** column. In the **Active** column, you can select a Logic Condition, which when true activates the rule or programming condition.

## Desired Behaviour
I would like to see a **NOT** option in the Active select box, similar to those used in OpenTX. For example **!Logic Condition 9**. This could simplify the use of the programming framework, and negate a the use of an extra Logic Condition for a simple NOT function.

## Who does this impact? Who is this for?
Anyone who uses the programming framework

**Comment by DzikuVx** [comment]
I'd prefer not to do it as it make parsing and execution on FC part more complicated. You can always make a special condition that reverses something, no need to "user improvement" like that
