### ISSUE TITLE
FPort protocol unsupported in INAV/MATEKF722 2.6.0 Dec  4 2020 / 12:11:30 (cada68e4)

### ISSUE THREAD

**Issue by wkiskin-teladoc** [iNavFlight/inav-configurator#1133]
Flash latest stable 2.6.0 to Matek F722-STD  and no response in Receiver tab.  Performed RX binding again just to be sure, although I did get the green light on teh RX9 Slim+ the first time.

I have 2 other builds with the earlier pre-release from Nov 6 and can confirm that SBUS / SPort working fine, have not tried FPort on them.

When I re-flash back to 2.5.2 FPort works fine

Expected behavior:  Should be able to control the FC with FPort protocol

# diff all

# version
# INAV/MATEKF722 2.6.0 Dec  4 2020 / 12:11:30 (cada68e4)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# mixer

mmix reset

mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000

# servo mix

# servo

# safehome

# logic

# gvar

# feature
feature -AIRMODE
feature LED_STRIP
feature BLACKBOX
feature PWM_OUTPUT_ENABLE

# beeper

# map
map TAER

# serial
serial 0 0 115200 115200 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout

# master
set looptime = 500
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 100
set gyro_lpf_type = PT1
set gyro_stage2_lowpass_hz = 160
set gyro_stage2_lowpass_type = PT1
set dynamic_gyro_notch_enabled = ON
set dynamic_gyro_notch_q = 200
set dynamic_gyro_notch_min_hz = 80
set acc_hardware = MPU6500
set acczero_x = 30
set acczero_y = -13
set acczero_z = 12
set accgain_x = 4092
set accgain_y = 4101
set accgain_z = 4102
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = NONE
set min_check = 1050
set serialrx_provider = FPORT
set serialrx_inverted = ON
set serialrx_halfduplex = ON
set blackbox_rate_denom = 2
set motor_pwm_rate = 8000
set motor_pwm_protocol = DSHOT600
set throttle_idle =  12.000
set model_preview_type = 3
set applied_defaults = 2
set mc_airmode_type = THROTTLE_THRESHOLD
set name = CrocDal

# profile
profile 1

set mc_p_pitch = 44
set mc_i_pitch = 60
set mc_d_pitch = 25
set mc_i_roll = 50
set mc_d_roll = 25
set mc_p_yaw = 45
set mc_i_yaw = 70
set dterm_lpf_hz = 90
set dterm_lpf_type = PT1
set dterm_lpf2_type = PT1
set yaw_lpf_hz = 30
set mc_iterm_relax = RPY
set d_boost_factor =  1.500
set d_boost_max_at_acceleration =  5000.000
set d_boost_gyro_delta_lpf_hz = 65
set antigravity_gain =  2.000
set antigravity_accelerator =  5.000
set setpoint_kalman_enabled = ON
set setpoint_kalman_q = 200
set rc_yaw_expo = 70
set roll_rate = 70
set pitch_rate = 70
set yaw_rate = 60

# profile
profile 2

# profile
profile 3

# battery_profile
battery_profile 1

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

Write your command here

**Comment by DzikuVx** [comment]
sine we have this sorted out in other channels, we can close it
