### ISSUE TITLE
Change OSD SW label

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#1136]
The OSD SW label is not the most helpful. It seems to trip up quite a few new people to iNav.

Perhaps is should be changed to OSD OFF, as when active, the OSD is turned OFF?

**Comment by mattcave** [comment]
Found this Issue whilst searching “WTF does OSD SW do in iNav”. I think labelling it OSD OFF would have prevented me from having to search. I expected that it would cycle through the different alternative OSD layouts.
