### ISSUE TITLE
Reorganize battery settings on Configuration tab

### ISSUE THREAD

**Issue by avsaase** [iNavFlight/inav-configurator#1144]
I think the organization of the battery settings in the Configuration tab is a bit confusing. In the screenshot below, the items indicated in red represent settings that pertain how INAV measures battery voltage and current, which stays the same regardless of the battery profile. The blue items are about the specific battery used and change with battery profile.

![2020-12-26 14_42_39-INAV Configurator](https://user-images.githubusercontent.com/880421/103152525-23b3a700-4789-11eb-8738-d27d9a2a61b2.png)

It would be more intuitive if the blue and red items were grouped together. Something like this: 
![Battery settings mockup](https://user-images.githubusercontent.com/880421/103153187-0da8e500-478f-11eb-9483-7f6c2792fc20.png)

WDYT?

**Comment by DzikuVx** [comment]
I think it's a god idea.
