### ISSUE TITLE
[Feature request] Add MSC button to the Configurator

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav-configurator#1149]
As the title says.
Very useful feature that is now hidden behind the CLI.

An example as how this can look:
![MSC](https://user-images.githubusercontent.com/31951195/103476906-e7e89500-4db9-11eb-8bbd-c5b085157b66.jpg)

Thanks in advance for the time that goes into these things!

**Comment by MrD-RC** [comment]
In 5.x
