### ISSUE TITLE
Firmware Flasher - GITHUB Query Failed: Server Error

### ISSUE THREAD

**Issue by JustAskDave** [iNavFlight/inav-configurator#1161]
As the title indicates, trying to flash the firmware on a Maytek F405 board, the board and firmware version drop downs just sit there with Loading in them and the Server Error notice is in the info line log:

2021-01-19 @ 14:57:33 -- Running - OS: Windows, Chrome: 78.0.3904.87, Configurator: 2.6.0
2021-01-19 @ 14:57:33 -- Loaded release information from GitHub.
2021-01-19 @ 14:57:58 -- GITHUB Query Failed: Server Error

Have tried over and over, leaving the board in DFU and rebooting iNav, keeping iNav open and rebooting board, dozens of attempts but no go.

Any ideas?

**Comment by DzikuVx** [comment]
We have raised a ticket to GitHub as it looks like GitHub backend is no longer returning the list of releases

**Comment by JustAskDave** [comment]
2.6.1 - Perfect :)
