### ISSUE TITLE
Inav Configurator 2.6.1 unstable on M1 Mac - Big Sur

### ISSUE THREAD

**Issue by EmanuelStassar** [iNavFlight/inav-configurator#1177]
I am running Inav Configurator on an M1 Mac and its not very stable. Sometimes it crashes on startup, sometimes after a few minutes. It's borderline usable this way. 

I hope this app can be converted into a universal app for Mac so it can run natively on M1 processors.

**Comment by WillsGledhill** [comment]
Same for me on big sur but not M1 ive got the 2020 intel 13" pro

**Comment by bangkokopete** [comment]
not only on M1 , also here on Macbook 13" 2016 Big Sur. crashes always on start up , runs after the second or third attempt and crashes in the middle of the usage. My feeling only has something to do with com port access. 
BTW does happen on Betaflight configurator on start up as well, but only occasionally.

**Comment by mikekenyon99** [comment]
Hi - same here.  Apple M1 Mac Mini.  Pretty much useless, crashes after it has connected every time.

**Comment by al3k87** [comment]
This is a Big Sur issue with node.js, betaflight had same issue also but they have updated the version so its now stable. please fix this, is there any access to nightly builds that possible allready have this fix?
