### ISSUE TITLE
Compass calibration - add warning notice for magnets

### ISSUE THREAD

**Issue by poi2poi** [iNavFlight/inav-configurator#1180]
It might sound silly but it took me a while to figure out that my compass is being affected by the magnets built in the S800 that are supposed to hold the lid in place (it doesn't do anything),

I suggest that you add a notice next to the compass calibrator or a (?) icon to warn the pilot about magnets or speakers close to the FC when calibrating.

Nonetheless my compass doesn't work after removing the magnets ;-)

**Comment by MrD-RC** [comment]
You should not use compass in fixed wing. But the warning has been added.
