### ISSUE TITLE
Explorer LR v1 F411 resources are all wrong 

### ISSUE THREAD

**Issue by GQ4Life** [iNavFlight/inav-configurator#1192]
I tried both 2.5.2 firmware (using 2.6.1 configurator) and 2.6.1
The resource map is wrong for motors, and UARTs and almost everything. 
I used FlywooF411 firmware
Betaflight 4.2 and 4.2.8 firmwares work
Some of the betaflight resources map
resource BEEPER 1 C14
resource MOTOR 1 A08
resource MOTOR 2 B03
resource MOTOR 3 B10
resource MOTOR 4 A15
resource PPM 1 A02
resource LED_STRIP 1 A00
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 11 B06
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource SERIAL_RX 11 B07
resource ADC_BATT 1 B01
resource ADC_CURR 1 A01

Where iNAV maps the resources 
A00: ADC CH2
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: MOTOR1 OUT
A09: MOTOR2 OUT
A10: MOTOR3 OUT
A11: USB IN
A12: USB OUT
A13: FREE 
A14: FREE 
A15: FREE 
B00: MOTOR4 OUT
B01: FREE 
B02: FLASH CS
B03: MPU EXTI
B04: FREE 
B05: FREE 
B06: SERIAL1 UART TX
B07: SERIAL1 UART RX

**Comment by avsaase** [comment]
This sounds like a firmware issue so you should open an issue in [iNavFlight/inav](https://github.com/iNavFlight/inav/issues).
