### ISSUE TITLE
MacOS - Can't flash firmware

### ISSUE THREAD

**Issue by uk-Pedro** [iNavFlight/inav-configurator#1197]
Hi,

I've not managed to flash a FC with new firmware with the iNav-Configurator ever, on either of my Macs. I always have to download the firmware and then use Betaflight configurator or Cleanflight configurator to upload. If Cleanflight configurator can manage it then why can't iNav-Configurator?  I had to do this again today after upgrading iNav-Configurator to 2.6.1 and trying to flash a Matek F405SE.

Please fix.

**Comment by DzikuVx** [comment]
I belive this is fixed in 3.0
