### ISSUE TITLE
Model Flying Wing

### ISSUE THREAD

**Issue by ted-rcnet** [iNavFlight/inav-configurator#1198]
hi,
The model interests you ?

![FlyingWing](https://user-images.githubusercontent.com/2054360/111870147-4538bf00-8983-11eb-8b5f-187c029558b0.png)
![FlyingWing-g](https://user-images.githubusercontent.com/2054360/111872944-428f9700-898e-11eb-9f6b-f7157c234cb1.png)
![FlyingWing-s](https://user-images.githubusercontent.com/2054360/111872946-47544b00-898e-11eb-8339-aedb50ef0475.png)

**Comment by DzikuVx** [comment]
@ted-rcnet yes, very much! Please make a pull request for this model!

**Comment by ted-rcnet** [comment]
👍
