### ISSUE TITLE
Mission Control -- Bing Maps

### ISSUE THREAD

**Issue by Marcus-Barcus** [iNavFlight/inav-configurator#1203]
This is to do with just Mission Control in INav not a 3rd party app
When setting up Bing Maps i cant copy and paste the Key from Chrome or Notepad or
Excel or key pad ctrl-c ctrl-v
nothing happens - I tried typing it but uses odd characters 
tried turning off java script still nothing as key is gone - needs Java
Is there something in the code stopping this.
No info also what Proxies to employ for URL & Layer
Can the KEY & Proxies be applied via Cli?
Thanks

**Comment by DzikuVx** [comment]
I'm unable to reproduce this behavior
