### ISSUE TITLE
CLI "Save to file" not working

### ISSUE THREAD

**Issue by poi2poi** [iNavFlight/inav-configurator#1205]
iNav Configurator 2.6.1 with Chrome Version 89.0.4389.90 on Windows 10:

When I try to save a backup with the "Save to file" button, it will open a "Open file" dialog window instead of a "Save file" dialog.
Starting the app in administrator mode doesn't change the behaviour.

It's not possible to save the backup, only by copy & paste

**Comment by DzikuVx** [comment]
Tested with 3.0, works
