### ISSUE TITLE
Surface mode

### ISSUE THREAD

**Issue by flyinginger** [iNavFlight/inav-configurator#1210]
having issue with "yoyo" behaviour and the fact that i need to land, disarm, activate/deactivate surface mode and then re arm
INav 2.6.1
mode poshold+angle and alt hold+angle, surface on separate switch, act as a modifier of those modes
Modes on ch6 (freedomTX) MAX mixes

**Comment by MrD-RC** [comment]
This would be a [firmware](https://github.com/iNavFlight/inav) issue, not configurator.

**Comment by flyinginger** [comment]
You mean Flywoo FW of inav ? Or else?

**Comment by MrD-RC** [comment]
iNav. I put the link in the comment. Issue with flying like that aren't related to the configurator. Configuratior issues are just for the software you use on your computer.

**Comment by flyinginger** [comment]
Cheers !
