### ISSUE TITLE
Modes tab mode box highlight out of sync with mode selection

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav-configurator#1234]
V 3.0.0. The Modes tab blue highlight when a mode is active doesn't correspond with the channel selection. Seems to be completely messed up. e.g. when Prearm is active it's not highlighted but 2 other modes are highlighted instead. Same for the other modes.

**Comment by avsaase** [comment]
Caused by https://github.com/iNavFlight/inav-configurator/pull/1100?
