### ISSUE TITLE
Remove non existing feature from inav configurator

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav-configurator#125]
This feature is not a part of iNav and was removed long ago.

![image](https://cloud.githubusercontent.com/assets/5670710/22417178/41fa5f3a-e6d3-11e6-9065-cfd47c11cf95.png)

**Comment by digitalentity** [comment]
Other features that are (or will be) deprecated in 1.6: `SONAR`, `FAILSAFE`

**Comment by DzikuVx** [comment]
Sonar will be covered by #104

**Comment by DzikuVx** [comment]
done in #131
