### ISSUE TITLE
[3.0-RC1] Thethered logging file selector does not open

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav-configurator#1273]
As title says, file selector for Tethered Logging does not open when button is clicked.

**Comment by DzikuVx** [comment]
And body uses that?

sob., 22 maj 2021, 15:31 użytkownik b14ckyy ***@***.***>
napisał:

**Comment by b14ckyy** [comment]
The last time I used it was a few months ago to log RX inputs when we worked on the FrSky Failsafe glitch. 
It is a helpful feature in some cases especially for bug analyzis.
