### ISSUE TITLE
cant find 3.0.0 rc2

### ISSUE THREAD

**Issue by jonnraa** [iNavFlight/inav-configurator#1284]
tried to download the latest rc2 bur its not in the releases. still 3.0.0 for win 64.
need mamba 405 us ic2. none of the hex,s work on the dji version of the 405 board in my diatone tycan  mcx 369 (power unit) w/o dji air unit
tnx

**Comment by Mateyhv** [comment]
https://github.com/iNavFlight/inav-configurator/releases/tag/3.0.0-RC2

> tried to download the latest rc2 bur its not in the releases. still 3.0.0 for win 64.
> need mamba 405 us ic2. none of the hex,s work on the dji version of the 405 board in my diatone tycan mcx 369 (power unit) w/o dji air unit
> tnx
