### ISSUE TITLE
Mission Control Default Settings display undefined values

### ISSUE THREAD

**Issue by sakisdog** [iNavFlight/inav-configurator#1290]
Hello, After iNav Configurator RC2 i found 2 issues:
1) The default settings values display "undefined" in the input boxes
![image](https://user-images.githubusercontent.com/9437187/120797366-9d27a080-c544-11eb-8ca4-0af74565ad01.png)

2) I cannot click on the map to create a mission when i have no controller connected.

I don't know if this is expected behavior or not but i though i should mention it.

**Comment by stronnag** [comment]
Your installation is somehow broken.
Works perfectly here:
* No dependency of an FC for mission control
* Dialogue boxes behave as expected

**Comment by avsaase** [comment]
I'm having a similar problem. Once I connect and disconnect a fc I can create and edit WP's as reported in. My Default altitude and speed work as expected but the radius is undefined.

![image](https://user-images.githubusercontent.com/880421/120799390-f7bdfe00-c53e-11eb-882a-2ff041cf70d0.png)

**Comment by stronnag** [comment]
No such problem on 
* Linux 64
* Linux 32
* Win10 (VM)
* MacOS (VM)

Using 59d8bec / 3.0.0-RC2.

**Comment by stronnag** [comment]
And the radius is undefined because you haven't defined it. Set a value, save it. Guess what you get back next time?

**Comment by stronnag** [comment]
You guys are right!
Master is working
Release 3.0.0 is not.

**Comment by avsaase** [comment]
Shall we close this and keep the discussion in https://github.com/iNavFlight/inav-configurator/issues/1181?

**Comment by stronnag** [comment]
I think it's best to keep it here. This is essential for 3.0; some of #1181 is a wish list for future (post 3.0) work.

**Comment by stronnag** [comment]
@ArnoTlse Can you please put the "can't create WPs prior to a serial connection" part to the top of your list?

**Comment by ArnoTlse** [comment]
hi @stronnag ,

I have created a new branch from Master to debug it. But I do not see any problem using the master. Howerver, I reproduce the pb on the compile version 3.0.0. I have for the moment no clue of what could be the issue as it works well through NPM. 

When you say "rebuild master", it means when you create a compile version of the master ? 
How can I do that to maybe instrument a bit the code to see where could be the issue between a master running through NPM and a compile master ?

Arno

**Comment by stronnag** [comment]
I have no problem with `npm start`. I get a warning for about 0.1ms that *I think says*  "profile is based in a newer nwjs" 

Maybe this is reason (and why my old master build worked and my new one fails); the build was recently updated to nw.js 0.50.3?

I'm not JS qualified in any way, this is just speculation.

**Comment by ArnoTlse** [comment]
Ok, yes I have noticed this pop-up that have appeared recently, but as it really a furtive pop-up, I never reach to read what it says.

I need to have a dive in NPM and NWJS to see if I can have a NPM consistent to the version nwjs used now.

**Comment by stronnag** [comment]
But I don't think NPM/NWJS is a factor. I cleaned out my repo,  reinstalled `npm` and I'm in the situation:

* Release_3.0.0 : Cannot create new WP or load mission from file prior to serial open
* Master : No problem creating WP / opening mission files

The above applies for both compiled version and `npm start`  and reinstalling `npm` has removed the momentary popup.

Beginning to doubt my sanity ....  and not being much help here.

**Comment by ArnoTlse** [comment]
OK, I wonder if we reinstall the previous version of nw.js whether it is working fine or it is the same pb as now?

That you're saying is that npm start with the 3.0.0 released is also not working?

**Comment by stronnag** [comment]
> OK, I wonder if we reinstall the previous version of nw.js whether it is working fine or it is the same pb as now?
> 
> That you're saying is that npm start with the 3.0.0 released is also not working?

Well I do wonder if I've just lost the plot and am not being helpful, but now I've cleaned everything out and reinstalled npm:
 * Both compiled app and npm  works with master
 * Neither compiled nor npm works with release_3.0.0

**Comment by ArnoTlse** [comment]
Ok, thanks.
On my side, I have clone the `release_3.0.0` , launch `npm install` on it. But I get many error message then.

**Comment by sakisdog** [comment]
To add my 2 cents here, i discovered this issue after moving from iNav Configurator RC1 to RC2. RC1 seems to work as expected. So the problem was created after code modifacations to RC2.
This is a screenshot from iNav Configurator 3.0.0 RC1
![image](https://user-images.githubusercontent.com/9437187/120862015-e998cd80-c590-11eb-99f8-c7ae4f5e4f02.png)

**Comment by sakisdog** [comment]
Ok...So after a little digging i think the undefined values problem is because of this code:
![image](https://user-images.githubusercontent.com/9437187/120863080-ab041280-c592-11eb-84cc-9f66b9c9d160.png)
I think that it should catch an error in case the safehome_max_distance could not be read and return the default values.

**Comment by ArnoTlse** [comment]
Hi,

Really strange. This is already in the master and it works well. I do not know why it could work on master and not in the release_3.0.0.
Anyway, I will try to change it through a try... Catch to see if it helps solving the pb.

Arno

**Comment by ArnoTlse** [comment]
Hi @sakisdog , hi @stronnag 

On the part of code you show @sakisdog, there is already a correction done in #1267 (older = red, newer =green), that avoid loading MspHelper when no FC is connected. Maybe that's why the Release_3.0.0 does not work if the PR #1267 has been merged in the master later but not integrated yet in the release_3.0.0 ?

![image](https://user-images.githubusercontent.com/76259684/121178786-2f8ab580-c85f-11eb-8817-8d4214e7f7bd.png)

It could explain why it works well with the master and not the relase_3.0.0

Arno

**Comment by ArnoTlse** [comment]
Hi @sakisdog , hi @avsaase , hi @stronnag 

On the last [3.0.0 release](https://github.com/iNavFlight/inav-configurator/releases/tag/3.0.0) (7days ago), I think my previous PR has been included now. It works on my side. Points can be added on Mission control on first launch without any FC connected or with FC connected.

Are you still facing some issue on this or can we close this issue ?

Arno

**Comment by stronnag** [comment]
It can be closed. Working OK.

**Comment by ArnoTlse** [comment]
Ok, I cannot close it on my side. @sakisdog, if it's also ok for you, I'll let you close this Issue.

Arno

**Comment by sakisdog** [comment]
It's working fine for me too. I'm closing this issue. Thank you for your help.
