### ISSUE TITLE
inav-configurator does not support inav 3.1.0

### ISSUE THREAD

**Issue by juju988** [iNavFlight/inav-configurator#1306]
Hi all - I've built a new .hex file for a MATEKF411 using latest INAV 3.1.0. I get the following message when trying to connect to it with INAV CONFIGURATOR 3.0.0:
"This firmware version is not supported. This version of Configurator supports firmware from 3.0.0 to 3.1.0 (excluded)"

Is there a newer version of INAV CONFIGURATOR available? I can't see any on Releases page.

**Comment by stronnag** [comment]
As ever, http://seyrsnys.myzen.co.uk/inav-configurator-next/ : Unoffical, upto-date, E&OE.

**Comment by juju988** [comment]
Brilliant thank you so much
