### ISSUE TITLE
BUG: Missing Glideslope feature from OSD Tab

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#1310]
with regards to this item in the current inav 3.0 release.

https://github.com/iNavFlight/inav/pull/6939

The option to display the OSD element for the glideslope is missing.

**Comment by wx4cb** [comment]
i can ebale it via CLI with 

osd_layout 2 124 1 6 V 


for example

**Comment by OptimusTi** [comment]
![image](https://user-images.githubusercontent.com/45466510/123712252-f16e2980-d83f-11eb-9d81-58b7e7839235.png)

**Comment by wx4cb** [comment]
i don't see that at all....

2021-06-28 @ 16:09:37 -- Running - OS: Windows, Chrome: 87.0.4280.141, Configurator: 3.0.0

![image](https://user-images.githubusercontent.com/1495297/123713991-8a527400-d843-11eb-8b74-95c5c148ed5e.png)

**Comment by wx4cb** [comment]
![image](https://user-images.githubusercontent.com/1495297/123714141-c2f24d80-d843-11eb-94fe-b7cda3baea90.png)

**Comment by wx4cb** [comment]
![image](https://user-images.githubusercontent.com/1495297/123714215-e4533980-d843-11eb-9cd0-cf4c051b2f32.png)

**Comment by Mateyhv** [comment]
@wx4cb I have it the same way as @OptimusTi does.

**Comment by wx4cb** [comment]
> @wx4cb I have it the same way as @OptimusTi does.

ok so what's different about your setup than mine? i even re downloaded the configurator last night  and it's still not there.

what are the requirements to get it to show lol.

**Comment by OptimusTi** [comment]
> > @wx4cb I have it the same way as @OptimusTi does.
> 
> ok so what's different about your setup than mine? i even re downloaded the configurator last night and it's still not there.
> 
> what are the requirements to get it to show lol.

Not sure. The only check I see in the code is version number. Fresh install here.

**Comment by MrD-RC** [comment]
Did you download an RC Configurator by mistake. This was only added 3 days before the final was released. Also, check that you haven't got multiple copies, and are running the wrong instance. 

Make sure you are using this one https://github.com/iNavFlight/inav-configurator/releases/tag/3.0.0

**Comment by wx4cb** [comment]
@MrD-RC  i had re downloaded it again just to be sure. but i just downloeded another one again and ran it from a diff directory, and it is there, so something must have been weird with the install dir
