### ISSUE TITLE
Footer on OSD tab broken

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#132]
Not sticky

![przechwytywanie](https://cloud.githubusercontent.com/assets/966811/22439928/bd67f9d0-e731-11e6-8007-5c628f7f1831.PNG)

**Comment by skaman82** [comment]
I will take a look tomorrow!

**Comment by DzikuVx** [comment]
looks like something is pushing down. Scroll added to container. Spend like 15 minutes fighting with it. Failed. On the other hand, I hate CSS

**Comment by DzikuVx** [comment]
and thanks @skaman82
