### ISSUE TITLE
Configurator build info incorrect in readme.md ?

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav-configurator#1323]
https://github.com/iNavFlight/inav-configurator#building-and-running-inav-configurator-locally-for-development-or-linux-users

states using` ./node_modules/gulp/bin/gulp.js task-name` to run other tasks defined in gulpfile.js. However, this doesn't work. What does work is:

`node node_modules/gulp/bin/gulp.js task-name`

Is the current readme out of date ?

**Comment by laurin-1** [comment]
Well, that is very likely, it has been last updated on Jan 29, 2020:
https://github.com/iNavFlight/inav-configurator/commits/master/README.md
For me personally, both ./node_modules/gulp/bin/gulp.js task-name and node node_modules/gulp/bin/gulp.js task-name "work", as well as npm run gulp task-name and gulp task-name (with an already installed gulp).
However, I'm not able to actually get them to properly build with the steps described in the README, the release or release-linux64 task result in the following when starting the built ./inav-configurator:
![image](https://user-images.githubusercontent.com/87230375/128216329-dc343f5b-10b9-4abe-a4dc-fa41df741610.png)
This is the same for different node versions and also regardless of how gulp was called or which gulp was used for task-name.

Using npm start works though, but that's only temporary.
The README really needs to be updated in regards to build instructions.

**Comment by MrD-RC** [comment]
Building in Windows PowerShell works fine with `node ./node_modules/gulp/bin/gulp.js release`
