### ISSUE TITLE
BBL download has no extension

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#1338]
Issue: when downloading a log file from dataflash, the configurator fails to save it with a .TXT extension. I know this is trivial, but the blackbox explorer doesn't recognise the log without it.

Fix: Add a .txt extension when saving blackbox logs from a dataflash chip

**Comment by stronnag** [comment]
Already fixed by #1325

**Comment by wx4cb** [comment]
@stronnag which version as i'm using 3.4.0 that i just downloaded

**Comment by stronnag** [comment]
github master. If you want a pre-release, then as ever [my master/next stash](http://seyrsnys.myzen.co.uk/inav-configurator-next/), supports 3.0.x and 3.1. If you're on 3.4.0, then you're kilometres  ahead of the rest of use :-)

**Comment by wx4cb** [comment]
i meant BBE 3.4.0 and im on 3.10 for inav.  :D

**Comment by stronnag** [comment]
You're correct (as usual). The download folder is filtered by `*.txt`; however `.txt` / `.TXT` is not automagically appended to the generated file name; the user has to append it.  So #1325 does not appear to fix your issue.

![rect34](https://user-images.githubusercontent.com/158229/132318616-2e5c5e18-4a7f-46f6-a205-427ece61aa54.png)

Other OS may behave differently ....

**Comment by breadoven** [comment]
Maybe the easier solution is to just make the .txt extension part of the file name by default. I think the diff file save does the same, no separate extensions necessary in that case.

**Comment by stronnag** [comment]
yes, that would be the best, probably .TXT for backwards compatibility (and case sensitive OS).
