### ISSUE TITLE
Failsafe changes in 1.6+

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#134]
In 1.6 failsafe is going to be changed a lot:

 1. There's no Stage 1 anymore
 1. Failsafe is always enabled (feature FAILSAFE is deprecated)
 1. There is a new "do nothing" failsafe procedure which will keep enabled modes and inputs as they are.

![2017-01-31 13 37 24](https://cloud.githubusercontent.com/assets/11059099/22451479/88812e38-e7ba-11e6-9dd8-1fc01c3c030c.png)

**Comment by oleost** [comment]
Also is shows "Stage 2" as disabled. even when enabled.

This must for sure confuse alot of users and needs updating.

**Comment by DzikuVx** [comment]
Implementation in place, closing
