### ISSUE TITLE
LED strip does not work

### ISSUE THREAD

**Issue by guy111a** [iNavFlight/inav-configurator#1352]
Hello

fc is speedybe f7 v2 
last fw 3.0.2 
last configurator 3.0.2

the tab of LED  works but the leds are not flashing.
( they are good as i checked in betaflight and they worked. )

activate in configuration
go to led tab, wire ordering mode, do some stuff, save .. nothing .. 
battery is connected.

i checked in windows10, windows11, linux ubuntu.

please help

thank you

**Comment by RipperGOT** [comment]
With 3.0.1 works? Test it.
