### ISSUE TITLE
Chrome link is down!

### ISSUE THREAD

**Issue by radlab-sketch** [iNavFlight/inav-configurator#1353]
https://chrome.google.com/webstore/detail/inav-configurator/fmaidjmgkdkpafmbnmigkpdnpdhopgel?hl=en

Hi All, 

The chrome link is down and gives a 404 error. Please help as this is seriously impacting my class of 140 students (-: 
<img width="1057" alt="Screen Shot 2021-09-22 at 4 02 34 PM" src="https://user-images.githubusercontent.com/55903569/134414845-00c053f6-b9d0-4071-bb6d-ebe6e630576b.png">

**Comment by DzikuVx** [comment]
We no longer support INAV Configurator as a Chrome App. You options are:
- use standalone Linux or window app
- run locally from sources
