### ISSUE TITLE
Waypoint upload/download broken in Mission Control

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav-configurator#1366]
### Issue: 
If more than a certain amount of WP is uploaded to a FC, the waypoints get corrupted. Mission is shown valid but a download shows incomplete missions, missing WPs or even no waypoints at all. 
The amount of possible waypoints to upload to FC depends on the FC. Tests with an Matek F405 Wing showed an average of 40 points that can be downloaded before the corruption chance is 100%. On FCs with USB Brakeout board (F722-WPX, F405-WSE) not even 10 WPs can be uploaded reliably. 

### Tests done: 
**Tested on the same PC with MWP-Tools in a virtual machine:** 
- up to 60 WP can be uploaded and downloaded from FC with no issue
- Same successful uploads and downloads with F405 Wing and F405-WSE
- stored WP to EEPROM

**Switched back to Windows Host system with FC reboot and conencted to Configurator:**
- download mission does only get around 40 WP (between 37 and 42 of 60WP) on the F405-Wing on each download attempt
- More random numbers between 2 and up to 40 WP on the F405-WSE with USB breakout board
- was never able to download all WP from FC
- Created mission in Mission Control needs multiüle attempts with higher chance of corrupt missions on higher WP counts. Impossible to get a mission with 40+ waypoints uploaded at all

### Additional Info:
If a Waypoint upload attempt fails and I connect to MWPTools without reboot of FC, also MWPTools reports corrupt WP uploads. So **Configurator puts INAV in an unstable state** where no reliable WP transfer is possible anymore. 

Lowering the Baud Rate down to 38400 for USB does not change the behavior. 

For Comparison I also tested with SpeedyBee App over USB. I was able to successfully download the full 60WP mission from EEPROM in SpeedyBee app and also edit and reupload the mission without problem. 

Multiple Users report the same issue. More obvious with new FCs with external USB but in general all FCs seem to be affected. 

Demo video: https://www.youtube.com/watch?v=NWV89v5Y3L0

Affected known INAV+Configurator version: 2.6, 3.0, 3.01, 3.02 Release
Board independant, Reports seen on F405-WSE, F405-Wing, F722-WPX, F722-Wing, F765-Wing

**Comment by stronnag** [comment]
Transcript of discord discussion (fwiw). 
[wp-discord.pdf](https://github.com/iNavFlight/inav-configurator/files/7306511/wp-discord.pdf)

**Comment by b14ckyy** [comment]
@breadoven can you send me a build to test it? I have no idea if my old build environment still Works. It was a bit messed the last time I used it.
