### ISSUE TITLE
Position of target CPU is not consistent in presets

### ISSUE THREAD

**Issue by eziosoft** [iNavFlight/inav-configurator#137]
Hi 
Just a small thing. Information about CPU (F1,F3...) changes place.
![image](https://cloud.githubusercontent.com/assets/2208254/22577516/887f8786-e9c2-11e6-9179-d403311b39c6.png)

![image](https://cloud.githubusercontent.com/assets/2208254/22577492/711e52fc-e9c2-11e6-8b08-bf9895ac208a.png)

**Comment by digitalentity** [comment]
@DzikuVx how about making preset description according to the template:

```
Name: 10" general purpose
Size/class: 450-600mm general purpose
Drive: 2212-920kv, 10" props, 3S battery
CPU: F1-F7
GPS: Optional
```

What do you think?
