### ISSUE TITLE
Presets - different nav_rth_abort_threshold values for FW vs MC

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#138]
Per https://github.com/iNavFlight/inav/issues/1225

**Comment by DzikuVx** [comment]
As long as this value is not available over MSP, nothing can be done.
I'm planning to add MSP_RTH frame for 1.7

**Comment by digitalentity** [comment]
Cool! I've just opened an issue to track the user request.

**Comment by fiam** [comment]
Now that we can set arbitrary settings via MSP, which values would be appropriate for FW and MR?

**Comment by MrD-RC** [comment]
Presets have been removed. The defaults cater for platforms separately.
