### ISSUE TITLE
PID Tuning tab does not display all GPS Navigation variables

### ISSUE THREAD

**Issue by kiwi-42** [iNavFlight/inav-configurator#1380]
PID Tuning tab does not display GPS Navigation/Position XY/Integral or Derivative.
The corresponding variables nav_fw_pos_xy_i and nav_fw_pos_xy_d can be get/set in the cli, but not in the GUI.

![cli](https://user-images.githubusercontent.com/92712002/137805018-4f897396-c45e-4727-8df3-80a216580356.jpg)
![PID Tuning](https://user-images.githubusercontent.com/92712002/137805101-cb79d85f-01e4-42e4-a3b0-39da30940720.jpg)

.

**Comment by kiwi-42** [comment]
Certainly some of the more obscure parameters are not shown in the GUI, but if you are playing with nav_fw_pos_xy_p, it seems a bit arbitrary not to see the _i or _d terms.  However. it's not a biggie, just a small inconvenience.

**Comment by b14ckyy** [comment]
It is not recommended to touch the I and D gains at all. 
P is used to make nav turns more rapid or more soft. In 99.9% of the cases there is no reason to touch I and D.

**Comment by kiwi-42** [comment]
The reason for adjusting nav_fw_pos_xy PIDs was to try to solve a particular problem.  My three fpv aircraft share the same issue;  the circle-following performance in Pos Hold and RTH is poor.  With Loiter radius = 50m, in any significant wind the Distance to Home can range from 30m to 80m.  It shows characteristics of an under-damped response.  I am sure iNav can perform better than this, and the XY PIDs seemed like a good place to start.

**Comment by b14ckyy** [comment]
@kiwi-42 
the way INAV navigation controller works, won't fix this by position PID tune. 
First of all, 50m is already a very tight circle for most planes unless it is something small and slow like a ZOHD Drift or Nano Talon or a T1 Ranger.  
Next is the navigation bank angle and max bank angle. If the plane can't bank enough to get the turn it will overshoot, especially when turning into a crosswind. 
Next is the cruise throttle. If the plane is just flying too fast it also will overshoot the turn. 
Then also Horizon drift in long POSHOLD periods can influence the path as the plane might start to oscillate in altitude and therefore get massive airspeed fluctuations around the circle.

So the Navigation PIDs are THE LAST THING you should touch before all the other things mentioned above are not dialed in perfectly.
