### ISSUE TITLE
Limit FF max value

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#140]
Limit max FF value.

" compute MAX value for FF gain and inform the user that this is only MAX value and real value HAS to be smaller that that"

Max FF should give max servo deflection (500) at max stick deflection (500)

**Comment by digitalentity** [comment]
>Max FF should give max servo deflection (500) at max stick deflection (500)

Yes, but only in rate mode and this is not the final tuning value. Real tuning value will probably be much smaller than this.

**Comment by DzikuVx** [comment]
Yes, this is only the upper value user will be able to enter. It will probably we always higher than defaults for firmware or presets
