### ISSUE TITLE
1.6.0 Have to restart configurator after leaving CLI

### ISSUE THREAD

**Issue by PaulHam211** [iNavFlight/inav-configurator#142]
After leaving CLI I need to restart the configurator and unplug USB to my naze32. Otherwise I cannot see any tabs or reconnect using the connect at the top.

<img width="1095" alt="screen shot 2017-02-05 at 17 23 59" src="https://cloud.githubusercontent.com/assets/7596825/22628222/3b9cc566-ebc8-11e6-9f0b-a3ddfd88cef7.png">

**Comment by skaman82** [comment]
@PaulHam211 Thats strange – I am not able to reproduce this. Do you still have the Problem?

**Comment by DzikuVx** [comment]
This is somehow connected to Serial port API in Chrome. From time to time chrome restart is required. AFAIK there is no fix, but happens rarely
