### ISSUE TITLE
Parachute not working 4.0

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#1426]
The parachute icon for some reason doesnt indicate a failsafe and the fc doesnt always go into failsafe when used with a tbs sixty9 vtx/rx combo.

Crsf is used between the rx and the f765 wse, fresh build with the latest inav release.

The rx is going into failsafe and the fs mode is set to cut.

The OSD shows !FS! In the mode area

**Comment by wx4cb** [comment]
![20220104_133420](https://user-images.githubusercontent.com/1495297/148108496-226f1c5e-9e53-490b-8ff8-f169a847542e.jpg)
![20220104_133416](https://user-images.githubusercontent.com/1495297/148108502-158b7c49-55e4-4150-88f3-4b19eb5409c2.jpg)

**Comment by OptimusTi** [comment]
Do you have another CRSF Rx to test with?  Test two planes on INAV 4.0 - Diversity RX, Nano RX. Latest TBS firmware.
![image](https://user-images.githubusercontent.com/45466510/148111909-bcd5deb8-f949-47d2-a0f4-6862e3638b17.png)

**Comment by wx4cb** [comment]
that's what im working on now... i know it's fine with every other crossfire rx i have.... trying to see if it's specific to the 69 as this is the first one i've used. i'm updating a new nano rx now

**Comment by wx4cb** [comment]
it's just weird how the osd shows it's in FS but the configurator doesnt

**Comment by MrD-RC** [comment]
Configurator will only do what the firmware tells it to, so I believe the issue will be firmware side. But yes, it is strange that there is a mismatch somewhere.
