### ISSUE TITLE
Expo curve line not displayed properly

### ISSUE THREAD

**Issue by alexrjohnston** [iNavFlight/inav-configurator#1433]
![Screenshot 2022-01-10 at 11 17 27](https://user-images.githubusercontent.com/8748529/148757794-1706fd2f-8067-4d8d-95cf-aa9d432315af.png)
![Screenshot 2022-01-10 at 11 13 50](https://user-images.githubusercontent.com/8748529/148757798-b2b94190-5d8d-49c7-9df0-214b056157ad.png)

I am helping an established pilot set up a cinelifter and they have pointed out the following issue:

The curve line shown with with expo greater than 1.2 isn't displayed properly, there is no way there is no stick input until half way across the stick? 

Regards,
Al.

**Comment by MrD-RC** [comment]
Sounds about right to me. Expo flattens out the centre of the of the stick. The higher the expo, the flatter the centre. Over a value of 1 (100% expo), the more of the line is pinned to the central position. What I wouldn't expect to see is more pronounced on the 1.9 expo. The flat, then an angle up, that then curves. I would expect to see the flat transition in to the curve.
