### ISSUE TITLE
Add "set mode" as operation in programming framework

### ISSUE THREAD

**Issue by StuweFPV** [iNavFlight/inav-configurator#1434]
This is no major issue but I've noticed that there is no "set mode" available in the operations menu of the programming framework.

I'd like to change my flight mode based on certain conditions. The only way now is with defined switches in the mode menu and use "RC channel override" to set that position. However this "way around" uses more lines in programming and additional channels. There are other options like "select OSD"  as a operation which can be set by the same "backdoor" ->switch modes or the whole VTX commands -> switch adjustments. It seems that for some functions there are two ways of programing it but for a very basic and important one like selecting your flight mode there is only one. There might be a reason for that which i don't know but it's kinda hard to grasp if you'll find "select OSD".

I propose to add the "set mode" function to the programming framework as a operation unless i have overlooked or miss something fundamental. then please close that request.

**Comment by StuweFPV** [comment]
thank you!

**Comment by StuweFPV** [comment]
I finally got around making good use of this new feature. unfortunately the WP mode is not available from the flight mode selection.. probably the only one not on the list. any specific reason for that? It would be very useful to be able to select WP as mode and even better to change the value of "nav_wp_multi_mission_index". my use is it, to fly mission 1 and hold, when condition A is active then fly mission 2, etc.
any chance to implement that?
cheers!

**Comment by DzikuVx** [comment]
To set a mode you have to override RC channel that activates this mode. Works like a charm

**Comment by StuweFPV** [comment]
yeah i was thinking of this workaround but what is with the real switch that is still in Pos 0?? lets say 0=Acro 1=WP. I don't touch the switch and override that channel via condition. would i have to toggle the switch before next time use? he keeps sending the signal of position 0 whilst i override??
another idea i had was use virtual RC channel (my TX only goes to 12) so CH13 as WP activator in addition to the physical switch.

but i don't get the logic... ANY flight mode except WP is selectable from the list in the programming framework. why WP not?? you could argue that for all other modes you could just do a override RC channel... so why only include 90% of the options in the drop down? why not 100% even only for consistency sake?
thanks

**Comment by StuweFPV** [comment]
what defines the drop down content? user 1&2 but no WP..
![missing WP](https://user-images.githubusercontent.com/61394342/194352389-d3de290f-7feb-451e-a015-8d093afb5eeb.jpg)
