### ISSUE TITLE
[Dev] Chrome Debugger mode not working in 5.0.0 version of Inav Configurator

### ISSUE THREAD

**Issue by ArnoTlse** [iNavFlight/inav-configurator#1438]
Hi,

I'm having trouble to get "inspect code" by right clicking on the Inav Configurator app with the 5.0.0 version of the configurator. In version 3.0.0 it was working fine.  Now, in 5.0.0 version, there is nothing occuring by right clicking.

What I expect like in 3.0.0 version : 
![image](https://user-images.githubusercontent.com/76259684/150699015-f2494d5b-bc89-4fe6-96e2-5d56999c70d2.png)

Does anybody know how to make it work again or if there is another way to debug Configurator when launched ?

ArnoTlse

**Comment by DzikuVx** [comment]
This by design. You have to manually install SDK version of NW.js
`npm install nw@0.50.3-sdk --nwjs_build_type=sdk`

**Comment by ArnoTlse** [comment]
Hi Pawel,

Thanks for the answer. 
I have several unsuccessful shot to install this version. I have to remove the node_modules folder and reinstall through the command you indicate, and now it works.

Arno
