### ISSUE TITLE
[OpenQuestion] use ExpressLrs receiver to configure Inav Flight controller through Inav Configurator

### ISSUE THREAD

**Issue by ArnoTlse** [iNavFlight/inav-configurator#1442]
Hi,

Does anyone know If it is possible to use an ExpressLRS receiver connected to the Flight Controller as a door to configure wirelessly the flight controller through INAV configurator ? And if so, how to do it ? And if not, what could be the blockers ?

As today, we are able to configure expressLRS RX & TX in wireless mode (with a hot spot generated by the RX or TX, or by allowing RX & TX to be connected to a local hot spot), I wonder if we can use this way to connect INAV configurator to the Flight Controller through the Receiver?
I know that there is some external stuff such as the Speedybee usb key to do so. But it could be great to do it directly through ExpressLRS stuff as it embarks already Wifi features in it without adding additionnal hardware.

Arno

**Comment by DzikuVx** [comment]
This is very much a question to ELRS if they offer a transparent serial passthrough of any kind
