### ISSUE TITLE
Fails to start in Ubuntu 20.04

### ISSUE THREAD

**Issue by voxtelnismo** [iNavFlight/inav-configurator#1443]
INAV configurator fails to start in Ubuntu 20.04 and some flavors (tested in Kubuntu and Budgie).

Issue: default Linux installation is missing libatomic.so.1

Solution: sudo apt install libatomic1

**Comment by rjmelchione** [comment]
Followed the installation instructions on Ubuntu 20.04.5 LTS (including install of libatomic1). However inav-configurtor still fails to start.  

Any guidance/assistance for how to resolve this would be greatly appreciated.

**Comment by stronnag** [comment]
Please explain what you mean by "fails to start", in particular please paste the output from running it from the shell prompt.

**Comment by rjmelchione** [comment]
![Screenshot from 2023-01-23 16-47-24](https://user-images.githubusercontent.com/1707402/214188970-f359dfea-bcd3-43f3-bd43-d63361af1069.png)

**Comment by rjmelchione** [comment]
I
![Screenshot from 2023-01-23 16-49-31](https://user-images.githubusercontent.com/1707402/214189591-fb118d9f-ec25-48e2-aa57-b67b1eb503b9.png)

**Comment by rjmelchione** [comment]
I believe I have followed the install instructions properly. However, when I attempt to launch inav-configurator I get an error that the inav-confiurator is not found.

**Comment by stronnag** [comment]
You need to learn some basic Linux. The current working directory is not conventionally on `$PATH`.

**Comment by rjmelchione** [comment]
Fair enough. I didn't realize the current directory needed to be added to $PATH. I assumed the current director would be in the execution order and did not need to be explicitly added to the $PATH. This is what happens when you assume. I will fill in my knowledge gaps for Linux. Thank you for the assistance.

**Comment by stronnag** [comment]
You can run the configurator from it's directory by explicitly specifying the  path, for example:

```
$ cd ~/rc_models/inav/inav-configurator
$ ./inav-configurator
```

If that works, please close the issue.

**Comment by rjmelchione** [comment]
Yes, works perfect. Thank you. 

I do not appear to have permission to close the issue. It appears to have been opened by voxtelnismo.
