### ISSUE TITLE
no backup and restore in 1.6.0

### ISSUE THREAD

**Issue by D17E** [iNavFlight/inav-configurator#145]
hi....
after the uato update to 1.6.0 from my inav config, the config not shown the backup and restore again....
and now my cpu load up to 1020....and can not enter to configuration tab..
i use inav 1.5.1 with spr f3 deluxe
i am trying to reflashing my board.....and connect to minim osd...the case happend again....

what wrong with my config...?

**Comment by DzikuVx** [comment]
There is no Backup/Restore in Configurator 1.6. Function was not working reliably and was not backuping/restoring most of settings.
Suggested backup restore is via CLI dump/diff commands.

Solution: flash again with full chip erase and setup again

**Comment by D17E** [comment]
thank you..
