### ISSUE TITLE
Inav configurator win64 4.1.0 NW.JS

### ISSUE THREAD

**Issue by knobbytrav** [iNavFlight/inav-configurator#1453]
Hello...when I try to run this on my Samsung windows 11 laptop, I get a screen with a huge NW.JS in the middle and what looks like a compass in the lower left corner.  It won't load normally.  I did get it installed and running on my work PC using the same downloads, so I am not sure what the deal is
<img width="341" alt="inav2" src="https://user-images.githubusercontent.com/94574102/154089245-e329118b-73fc-4d9e-b544-81e5cccefb87.png">
.

Help!

thanks!

**Comment by MrD-RC** [comment]
You need to download it from here https://github.com/iNavFlight/inav-configurator/releases

**Comment by knobbytrav** [comment]
I just re-downloaded it and tried again with the same results.

**Comment by DzikuVx** [comment]
tested win64 version, works just fine.

**Comment by knobbytrav** [comment]
> tested win64 version, works just fine.

On windows 11?

**Comment by DzikuVx** [comment]
Yes, on windows 11

**Comment by knobbytrav** [comment]
It must be something local on my machine... very frustrating. Any suggestions? I've gotten several clean downloads and done several installations. I am at a loss. Computer is showing there are no updates available either.

**Comment by DzikuVx** [comment]
Try this https://github.com/iNavFlight/inav-configurator#inav-configurator-start-minimized-what-should-i-do

**Comment by knobbytrav** [comment]
Just tried it....I'm still getting the nws screen.  This is driving me bonkers!

**Comment by MrD-RC** [comment]
@knobbytrav was this ever resolved? Is 5.1 working ok?

**Comment by knobbytrav** [comment]
No... I can't get any versions to work on this machine.  I just tried a reinstall of 5.1 to no avail...and I also just installed 6.1 to see.  End result is the same....the NW JS screen shot I posted is all I ever get with it.
