### ISSUE TITLE
INAV Configurator support multiple languages？

### ISSUE THREAD

**Issue by YI-BOYANG** [iNavFlight/inav-configurator#1454]
Hei guys, does the INAV Configurator program support multiple languages? I know it supports i18N like Betaflight Configurator, but INAV is currently only available in English, so I had to make a Chinese language branch of my own! Still, I hope to support multiple language versions in the future!

**Comment by YI-BOYANG** [comment]
<img width="910" alt="INAV中文" src="https://user-images.githubusercontent.com/46438966/154389615-70fc5e81-aac8-425b-ab6f-9538a52d52f6.png">

**Comment by DzikuVx** [comment]
Translations are possible but we do not plan to support any other than English translation.
