### ISSUE TITLE
Remove rc_rate from configurator

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav-configurator#146]
This has been gone since INAV 1.2

![image](https://cloud.githubusercontent.com/assets/5670710/23041381/176df428-f495-11e6-9ea8-293284b04ac3.png)

![image](https://cloud.githubusercontent.com/assets/5670710/23041399/28e871d8-f495-11e6-938c-b82a075dc6fc.png)

**Comment by DzikuVx** [comment]
done in 050dab3ee1af07a0407e43ef76bb49a2ca810ff3
