### ISSUE TITLE
Master fails to execute on all (64bit) platforms

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#1463]
Running current master on any platform (linux64, osx64, win64) results in a stuck window like:
![Screenshot-32](https://user-images.githubusercontent.com/158229/155350928-6679995a-8c4b-4c97-9bbe-42694c45d02d.png)
Untested on 32bit.

The last working build is from 777aa586e3b6793061ca49adda5c67bd73de1f84

However, `git bisect` shows the culprit as
```
$ git bisect bad
093fc22701aac1d1a4b531e9fd84d5477abe8281 is the first bad commit
commit 093fc22701aac1d1a4b531e9fd84d5477abe8281
Author: Darren Lines <darren@darrenlines.uk>
Date:   Sat Feb 12 17:16:31 2022 +0000

    Enhance and extend units conversion
    
    1. Fixed rounding error.
    2. Added conversions for:
    a) vertical speed
    b) metres
    c) temperature
    3. Added support on Failsafe and OSD pages.
    4. Sorted out alignment issues, due to different implementations.

 _locales/en/messages.json         |  10 +-
 js/settings.js                    | 151 ++++++++++++++++++++------
 main.css                          |  14 ++-
 src/css/tabs/configuration.css    |   4 +-
 src/css/tabs/failsafe.css         |  11 +-
 src/css/tabs/firmware_flasher.css |   1 -
 src/css/tabs/osd.css              |   4 +-
 src/css/tabs/pid_tuning.css       |   1 -
 src/css/tabs/transponder.css      |   1 -
 tabs/advanced_tuning.html         |  12 +--
 tabs/failsafe.html                |  22 ++--
 tabs/failsafe.js                  | 218 +++++++++++++++++++++++---------------
 tabs/osd.html                     |  18 ++--
 13 files changed, 299 insertions(+), 168 deletions(-)
```
Although authored prior to 777aa586, the failing commit was merged immediately after it.

**Comment by DzikuVx** [comment]
@stronnag it's runnig correctly on my PC. have you run `npm update` ?

**Comment by stronnag** [comment]
I think so, I also tried on two VMs (Ubuntu LTS, Debian Test) where it had never been built before via `npm install`. But let me double check.

**Comment by DzikuVx** [comment]
Win11 , win64

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/966811/155354516-2ea506a5-6b96-4b1f-af06-f3f3acb541fd.png">

**Comment by DzikuVx** [comment]
testing with release version
`node .\node_modules\gulp\bin\gulp.js release --platform=win64`

**Comment by DzikuVx** [comment]
OK, it's not working when build with `nw-builder`, fails exactly like you showed @stronnag

**Comment by DzikuVx** [comment]
yup, let me dig in what changed in NW.js so it's happening

**Comment by MrD-RC** [comment]
I get the same npm start works fine. building a release fails.

**Comment by DzikuVx** [comment]
Interesting, rolling back to `^0.50.3-sdk` does not resolve the problem

**Comment by DzikuVx** [comment]
OK, I know what's wrong, will fix
