### ISSUE TITLE
Multiple toggle buttons for DJI HD FPV "Hide unsupported elements"

### ISSUE THREAD

**Issue by tonyyng** [iNavFlight/inav-configurator#1471]
Each time you change the current layout, a new toggle button gets added for "Hide unsupported elements"

![image](https://user-images.githubusercontent.com/5619549/155888815-19119fd6-f7da-4324-96bf-b6c73565b208.png)

**Comment by MrD-RC** [comment]
I noticed this the other day. Thanks for spotting the cause.

**Comment by tonyyng** [comment]
Do you know if DJI HD supports more than one layout?  It would be a useful feature.
