### ISSUE TITLE
Windows Installer / Linux packages

### ISSUE THREAD

**Issue by Scavanger** [iNavFlight/inav-configurator#1472]
A scriptable install system (Nullsoft / InnoSetup) under Windows and packages for Linux (rpm / deb) could easily be integrated into gulp and would make installation under windows easier.

**Comment by wx4cb** [comment]
easier than just opening the zip file and dragging  the folder somewhere ?

**Comment by Scavanger** [comment]
The uninstaller would also clean up and not leave any "corpses" in the user directory.

**Comment by wx4cb** [comment]
the issue i can see with uninstallers is that it can only uninstall
what it put there (ie what it knows about). that's why windows leaves
a whole bunch of crap in program-files et al when you uninstall an app
if the application has created files in there that are not in the
installer log.

**Comment by Scavanger** [comment]
Just an idea, it is not really necessary, it is just a function for convenience.

**Comment by DzikuVx** [comment]
The thing with Installer/Uninstaller is that it makes having multiple versions on one machine much harder.

**Comment by erstec** [comment]
Two versions of distributions for every OS should be released.
One as a .zip, lets call it 'portable', for users want to have several version at a time (btw, this is not problem for MacOS as you can have as many version as want even using installer).
Next one, lets call it 'installer', as package (.exe .deb .rpm. dmg), for users who prefer this method.

@DzikuVx 
In addition, there is nothing impossible to have multiple versions at same time even with installer for Linux and Windows too.
For Windows - target installation folder and App UUID need to be changed every release (tested and ok).
For LinuX - only target folder (not tested, but I believe it will work).
It just requires some additional effort preparing first RC.

https://github.com/iNavFlight/inav-configurator/pull/1541 prepared and tested, for all platforms.

**Comment by stronnag** [comment]
> For LinuX - only target folder (not tested, but I believe it will work).

it works, I have an old version for a CC3D :)

**Comment by erstec** [comment]
> > For LinuX - only target folder (not tested, but I believe it will work).
> 
> it works, I have an old version for a CC3D :)

sure!

anyway, every user can choose preferred distribution, as every have own preferences, so we don't need to stop releasing .zip's or like that. For build script it is not big job to make both :)

Proposed PR are for unified uuid/name/folder (as, for. ex. BF do it now), but as I described before - I will add "differences" if we (dev's) decide that it needed and woth effort.

**Comment by ysoldak** [comment]
Having a `.deb` will make it possible to install  and use INAV on Chromebooks, perfect field companions, much easier.
Once installed with `.deb`, it is possible to launch the configurator app from quick search and/or pin it to the launch bar, instead of digging in the terminal.
Telling from experience with latest BF, installed from `.deb`

To install `deb` on Chromebook, one needs enable "Linux development environment", but that's minor.
