### ISSUE TITLE
cant install on windows 11

### ISSUE THREAD

**Issue by ozzy877** [iNavFlight/inav-configurator#1473]
trying to run i get this message.
The code execution can not proceed because nw_elf.dll was
not found. reinstalling may fix problem.
its the first time I'm trying to install both 32 and 64
same message.
please help

**Comment by gho1b** [comment]
You should make sure all files already extracted with equal trees by the zip file

**Comment by ozzy877** [comment]
Thank you

**Comment by ozzy877** [comment]
Thank you for the instructions. installed and ready to use
