### ISSUE TITLE
Unable to open serial port without internet connection

### ISSUE THREAD

**Issue by chucky-whiskers** [iNavFlight/inav-configurator#1474]
In version 4.0, my fc (Matek F405-Wing) will not appear in configurator without a working internet connection. It says unable to locate serial port, and I am basically at a standstill. Is a working internet connection necessary for basic operation of the configurator, even with local files?

**Comment by MrD-RC** [comment]
Works fine for me. I was at the flying field using Configurator 4.0 on Sunday. No internet connection there.

**Comment by chucky-whiskers** [comment]
Awesome! That means it is most likely a driver issue or just the computer
and not as permanent of a problem. At least I know where to start looking.
Thank you so much!
