### ISSUE TITLE
Blackbox Tab - catch up with CF

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav-configurator#15]
See CF Configurator
![config2](https://cloud.githubusercontent.com/assets/11768024/16054213/759fc756-326c-11e6-9452-5622b6ac757f.png)

**Comment by digitalentity** [comment]
Yes, this requires some changes to INAV-Configurator. I'll look into it once I return from my trip,

**Comment by oleost** [comment]
Is this not already included in iNav?  Can be closed?

**Comment by DzikuVx** [comment]
It's ported, closing
