### ISSUE TITLE
INAV 4.1.0 does not update the take off elevation

### ISSUE THREAD

**Issue by tguillaume02** [iNavFlight/inav-configurator#1512]
When I setup my take off home on mission controller, the elevation is not updated or keep the last elevation point
Exemple: 
Lat: 2.8156422 Lon: 50.0669514

![image](https://user-images.githubusercontent.com/11637270/166941406-fbaee72d-e17f-4476-a1fb-247c96611125.png)

**Comment by breadoven** [comment]
Does the Home elevation update if you click on the "set Home" button or move the Home point around ?

Also, is this a Home loaded from a Mission file or a new Home point placed on the map ? I assume you have an internet connection when this happens ?

**Comment by MrD-RC** [comment]
No response from OP in over 6 months. Seems to work fine in current master. Closing.
![image](https://user-images.githubusercontent.com/17590174/204081018-86ceac57-203e-4c22-ab15-5f670210956b.png)
