### ISSUE TITLE
iNav 5.0.0 Modes not showing in Configurator

### ISSUE THREAD

**Issue by billjow** [iNavFlight/inav-configurator#1534]
Have downloaded iNav Configurator 5.0.0, flashed it to my Cinewhoop using a Mamba F722-2IC flight controller, executed the DIFF ALL file from iNav 4.1. Going through the tabs, I could only see non-navigation modes so my Arm, Horizon (I don't bother with Angle) flight mode, and my Beeper. I normally have Nav WP, RTH, Altitude Hold, Waypoint Planner, Pos Hold etc. set up. I can't test fly it at the moment, so cannot tell if they are there, but just not visible. Screenshot below shows what is enabled, if I slide the Hide unused modes back, I get other options, but not the nav ones. As far as I can tell, my GPS and compass is working (if the latter is not, I always get incessant beeping and an Unable To Arm - Compass Failure message).

****

## Current Behavior
![iNav 5 0 0 modes showing](https://user-images.githubusercontent.com/99428035/170866868-4ae36628-a844-431d-b42b-b94c86fb7d93.jpg)

 [https://pastebin.com/ASjBVg3T](url)

# version
# INAV/MAMBAF722_I2C 5.0.0 May 26 2022 / 17:52:06 (8d70c7a1)
# GCC-10.2.1 20201103 (release)

**Comment by DzikuVx** [comment]
You have "hide unused modes" selected

**Comment by billjow** [comment]
As I explained in the text of the original issue, I was showing the modes that were still visible to me and I explained "if I slide the Hide unused modes back, I get other options, but not the nav ones." This issue should not be closed as it has nothing to do with whether the Hide Unused Modes option is selected or not.

**Comment by billjow** [comment]
Hi Pawel,

 

I have commented on the original issue, which I can no longer find. (Did you delete it?).

 

I explained in the original text to the issue that I was showing which modes were showing to me i.e. that all my nav modes had disappeared. I further explained that if I slide the Hide Unused Modes off, other modes became available, but not the relevant nav modes.

 

Please re-read my original explanations – this issue should not be closed as it has nothing to do with the Hide Unused Modes slider. 

 

Kind Regards,

 

Bill

 

Bill Jowitt

Tel: 07790 491385
