### ISSUE TITLE
INAV 5 CONFIGURATOR Multi WP Mission Fail to load

### ISSUE THREAD

**Issue by abimaputra78** [iNavFlight/inav-configurator#1536]
**
****

## Current Behavior

INAV 5.0 CONFIGURATOR failed to load and discrepancy of multi WP Mission. Reading with open street map was also diffcult for drone rural flying

## Steps to Reproduce

1. Setup for mission 1 and 2
2. update all and save to eeprom and save to pc
3. Reload with different mark number and sometimes mission 2 was missing 
4. Reload mission file from pc result same no. 3 above
5. No elevation or contour in the map

## Expected behavior

No discrepancies between Planned Missions and saved missions in the pc and the FC

## Suggested solution(s)

1. Using a Topographic Map was a ++ value since elevation and contour available. 
2. Valid saved multi wp mission during reload

## Additional context

---

- FC Board name and vendor: Holybro KAKUTE H7 
- INAV version string: 5.0 RC1

**Comment by breadoven** [comment]
> 3, Reload with different mark number and sometimes mission 2 was missing

What do you mean by different mark number and reload ? Reload from where ?

**Comment by abimaputra78** [comment]
From saved abc.mission from PC or load from FC (not eeprom one)

**Comment by breadoven** [comment]
Multi missions only work if saved to EEPROM. The Wiki description for Multi Missions might help:

https://github.com/iNavFlight/inav/wiki/Navigation-modes#multi-missions

Also you can't use the `Save Waypoint Mission` stick command if a multi mission is loaded otherwise it will overwrite the multi mission with a single mission.

https://github.com/iNavFlight/inav/blob/master/docs/Controls.md

**Comment by b14ckyy** [comment]
@breadoven @DzikuVx 
You should open this again. The description of the opener was really bad but I guess I found what he wanted to report and Jonathan has reproduced as well. 

If a Multi Mission is created and uploaded to FC (not EEPROM yet) and then downloaded, it is still a multi mission with selectable mission Index. But then storing the mission to EEPROM removes the Index markers. So after saving and loading from eeprom all multi missions are loaded as a single mission

Mission 1:
![image](https://user-images.githubusercontent.com/33039058/173199366-d57b5784-4df4-4a56-ac7c-7cb1c19573f0.png)

Mission 2:
![image](https://user-images.githubusercontent.com/33039058/173199378-03dbf935-f6a9-4436-828c-9f4f72d5d33b.png)

Uploaded all missions: 
![image](https://user-images.githubusercontent.com/33039058/173199398-820cd797-7bbe-40ed-826f-1ddb6076064e.png)

Saved to EEPROM and then loaded from EEPROM: 
![image](https://user-images.githubusercontent.com/33039058/173199415-e9484898-bf76-4769-b9e6-a27fef9fa421.png)

**Comment by abimaputra78** [comment]
Yes agree with that. 😉

**Comment by b14ckyy** [comment]
@abimaputra78 sorry I have deleted my comment because this is actually an INAV bug. Not configurator. https://github.com/iNavFlight/inav/issues/8112
