### ISSUE TITLE
inav 4.1 Blackbox bug

### ISSUE THREAD

**Issue by motz1117** [iNavFlight/inav-configurator#1545]
I had the problem, if i turned the save space from sd card to serial the configurator hung up. i could only change this in the CLI
from this "set blackbox_device = SERIAL" to this "set blackbox_device = SDCARD"

**Comment by b14ckyy** [comment]
@motz1117 can you please add more info? 
What FC, what INAV version (version string in CLI) 
Just checked with 5.0-RC3 and had no issues after selecting serial.

**Comment by MrD-RC** [comment]
No response from OP after almost 6 months. Closing.
