### ISSUE TITLE
5.0 RC2 - Waypoint download broken in Mission Control - again

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav-configurator#1553]
Might be related to #1366 as it also only seems to affect boards with External USB primarily. 

I have a 53 Waypoint mission planned in MWPTools. Upload and download works there without any problems. 
Uploading the mission from a File to the FC and storing to EEPROM seems to work reliable, just takes very long time (21s). But download is corrupted in most cases. INAV Version is 5.0-RC3
When I download the mission from FC now in configurator, sometimes the Mission gets corrupted. Like this: 

![image](https://user-images.githubusercontent.com/33039058/173198151-8963a194-bb90-487d-8606-fe0f5bdcfea3.png)

Sometimes more settle like this: 
![image](https://user-images.githubusercontent.com/33039058/173198168-d1055f4b-5ac4-47d7-a32d-1c334bcb7ffe.png)

Downloading in MWPTools within WSL-g works flawless: 
![image](https://user-images.githubusercontent.com/33039058/173198352-7a067679-adfc-421f-ba76-f2eced322aeb.png)

**Comment by breadoven** [comment]
Is this still an issue @b14ckyy or can it be closed ?

**Comment by b14ckyy** [comment]
> Is this still an issue @b14ckyy or can it be closed ?

I think we can close. Seems like the error checks are working. The External USB Port FCs still have issues, shown by sometimes long times until WP are transferred but I got no corrupted missions so far, so I guess that's ok
