### ISSUE TITLE
Changed code signature in macOS v 5.0.0?

### ISSUE THREAD

**Issue by suschizu** [iNavFlight/inav-configurator#1562]
hello @DzikuVx - can you confirm that the code signature has changed between macOS release 4.1.0 and 5.0.0?
(dl https://github.com/iNavFlight/inav-configurator/releases/download/5.0.0/INAV-Configurator_macOS_5.0.0.zip)

I've received following warning:
`EXPECTED Alberto Garcia Hierro (RWR56DABHQ) but FOUND Ernest Stepanov (BTPSFW65UC)`

Thanks

**Comment by DzikuVx** [comment]
That's correct!

**Comment by stronnag** [comment]
Add to Release Note?
