### ISSUE TITLE
Pitch Yaw Roll Rates not displayed in GUI but shown in CLI 

### ISSUE THREAD

**Issue by Purple-Badger** [iNavFlight/inav-configurator#1567]
There's a possible bug in configurator GUI where roll, pitch and yaw rates are not displayed. Info below to help verify:

**Board:** Matek F411 WSE 
**Configurator version:** 5.0.0
**Target:** 5.0.0 - MATEKF411WSE 2022-6-25 and custom build (SS1 LED and SS2 Ch6 active)

**Behaviour:** Pitch Yaw Roll Rates are not displayed in GUI ('undefined' is shown instead), but seem to be present on the FC and can be shown in CLI. Additionally, pitch, yaw and roll rates can be changed through the GUI and verified through CLI, but will not be displayed in the GUI (continues to show 'undefined')

**Testing of behaviour:** Complete fresh download of standard build (5.0.0 - MATEKF411WSE 2022-6-25) and then flashing to FC using chip erase still exhibits above behaviour on default settings.  Fresh full recompile of custom build, and then flashing to FC using chip erase still exhibits above behaviour on default settings. 

**Settings dump:**
# version
# INAV/MATEKF411SE 5.0.0 Jun 27 2022 / 11:00:01 (GITDIR-N)
# GCC-10.2.1 20201103 (release)

# start the command batch
batch start

# reset configuration to default settings
defaults noreboot

# resources

# mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.000

# servo mix
smix reset

smix 0 1 1 100 0 -1
smix 1 2 0 50 0 -1
smix 2 3 0 50 0 -1
smix 3 2 6 -50 0 -1
smix 4 3 6 50 0 -1

# servo
servo 1 900 2100 1500 100
servo 2 900 2100 1500 -100
servo 3 900 2100 1500 -100

# safehome

# logic
logic 0 1 4 25 0 1 0 0 0
logic 1 1 10 25 0 2 0 0 0
logic 2 1 11 25 0 3 0 0 0
logic 3 1 9 25 0 4 0 0 0
logic 4 1 -1 3 1 7 0 1250 0
logic 5 1 -1 2 1 7 0 1249 0
logic 6 1 -1 3 1 7 0 1500 0
logic 7 1 -1 2 1 7 0 1499 0
logic 8 1 -1 3 1 7 0 1750 0
logic 9 1 -1 2 1 7 0 1749 0
logic 10 1 -1 7 4 5 4 6 0
logic 11 1 -1 7 4 7 4 8 0
logic 12 1 -1 2 2 9 0 450 0
logic 13 1 12 22 0 0 0 0 0
logic 14 0 2 0 0 0 0 0 0

# gvar

# pid

# feature
feature MOTOR_STOP
feature GPS
feature PWM_OUTPUT_ENABLE
feature FW_AUTOTRIM

# beeper

# blackbox
blackbox -NAV_ACC
blackbox NAV_POS
blackbox NAV_PID
blackbox MAG
blackbox ACC
blackbox ATTI
blackbox RC_DATA
blackbox RC_COMMAND
blackbox MOTORS

# map

# serial
serial 0 2 57600 57600 0 115200
serial 30 1024 115200 115200 0 115200
serial 31 2048 115200 115200 0 115200

# aux
aux 0 0 0 1600 2100
aux 1 2 4 1875 1950
aux 2 12 4 1450 1550
aux 3 53 4 1775 1850
aux 4 11 4 1575 1650
aux 5 10 4 1350 1425
aux 6 28 4 1675 1750
aux 7 21 1 1550 1750
aux 8 54 1 1250 1450
aux 9 42 1 1925 1975
aux 10 42 1 1625 1675
aux 11 42 1 1325 1375
aux 12 43 1 1875 1925
aux 13 43 1 1575 1625
aux 14 43 1 1250 1300
aux 15 40 3 1925 1975
aux 16 40 3 1425 1475
aux 17 40 3 1225 1275
aux 18 40 3 1750 1800
aux 19 41 3 1875 1925
aux 20 41 3 1350 1400
aux 21 41 3 1150 1200
aux 22 41 3 1675 1725
aux 23 13 3 1150 1325
aux 24 13 3 1675 1850
aux 25 47 3 1800 2100

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout
osd_layout 0 0 26 2 V
osd_layout 0 1 1 2 V
osd_layout 0 2 0 0 V
osd_layout 0 3 8 6 V
osd_layout 0 4 8 6 V
osd_layout 0 7 14 2 V
osd_layout 0 9 3 10 H
osd_layout 0 11 1 5 V
osd_layout 0 12 1 3 V
osd_layout 0 14 24 4 V
osd_layout 0 15 24 7 V
osd_layout 0 22 14 15 V
osd_layout 0 23 7 15 V
osd_layout 0 25 23 6 V
osd_layout 0 26 24 8 V
osd_layout 0 28 23 15 V
osd_layout 0 30 1 14 V
osd_layout 0 31 24 3 V
osd_layout 0 33 3 9 V
osd_layout 0 34 12 1 V
osd_layout 0 35 1 4 V
osd_layout 0 37 9 4 H
osd_layout 0 38 6 2 V
osd_layout 0 40 1 15 V
osd_layout 0 41 24 13 V
osd_layout 0 42 1 13 V
osd_layout 0 48 16 15 V
osd_layout 0 85 4 7 V
osd_layout 0 97 9 13 V
osd_layout 0 100 4 8 V
osd_layout 0 105 24 2 V
osd_layout 0 108 24 5 V
osd_layout 0 124 24 9 V
osd_layout 1 0 26 2 V
osd_layout 1 1 1 2 V
osd_layout 1 2 0 0 V
osd_layout 1 3 8 6 V
osd_layout 1 4 8 6 V
osd_layout 1 7 17 15 V
osd_layout 1 9 3 10 H
osd_layout 1 11 1 4 H
osd_layout 1 12 1 3 V
osd_layout 1 14 25 3 V
osd_layout 1 15 24 7 V
osd_layout 1 22 15 15 V
osd_layout 1 23 7 15 V
osd_layout 1 25 23 6 V
osd_layout 1 26 24 8 V
osd_layout 1 28 23 15 V
osd_layout 1 30 2 14 V
osd_layout 1 31 21 2 H
osd_layout 1 33 2 8 V
osd_layout 1 34 12 1 V
osd_layout 1 35 6 3 V
osd_layout 1 37 9 4 H
osd_layout 1 38 6 2 V
osd_layout 1 40 1 15 V
osd_layout 1 41 18 14 H
osd_layout 1 42 1 12 H
osd_layout 1 48 16 14 H
osd_layout 1 85 3 7 V
osd_layout 1 100 4 8 H
osd_layout 1 105 24 2 V
osd_layout 1 108 24 4 H
osd_layout 1 124 1 11 H
osd_layout 2 0 26 2 V
osd_layout 2 1 1 2 V
osd_layout 2 3 8 6 V
osd_layout 2 7 17 15 V
osd_layout 2 9 3 10 H
osd_layout 2 11 1 4 H
osd_layout 2 12 12 1 H
osd_layout 2 14 25 3 V
osd_layout 2 15 18 2 V
osd_layout 2 22 15 15 V
osd_layout 2 23 7 15 V
osd_layout 2 25 28 6 V
osd_layout 2 26 24 8 H
osd_layout 2 28 23 15 V
osd_layout 2 30 1 14 V
osd_layout 2 31 25 2 H
osd_layout 2 33 3 9 H
osd_layout 2 34 12 1 H
osd_layout 2 35 1 3 H
osd_layout 2 37 9 4 H
osd_layout 2 38 6 2 V
osd_layout 2 40 1 15 V
osd_layout 2 41 25 12 H
osd_layout 2 42 1 12 H
osd_layout 2 48 16 14 H
osd_layout 2 85 13 2 V
osd_layout 2 100 4 8 H
osd_layout 2 105 24 2 V
osd_layout 2 108 24 4 H
osd_layout 2 124 24 9 H

# master
set gyro_main_lpf_hz = 25
set dynamic_gyro_notch_q = 250
set dynamic_gyro_notch_min_hz = 30
set gyro_zero_x = 9
set gyro_zero_y = -1
set gyro_zero_z = -16
set ins_gravity_cmss =  989.136
set acc_hardware = MPU6000
set acczero_x = 64
set acczero_y = -21
set acczero_z = -236
set accgain_x = 4072
set accgain_y = 4082
set accgain_z = 3984
set align_mag = CW270FLIP
set mag_hardware = NONE
set baro_hardware = SPL06
set serialrx_provider = CRSF
set motor_pwm_rate = 4000
set motor_pwm_protocol = DSHOT150
set failsafe_procedure = RTH
set align_board_yaw = 900
set platform_type = AIRPLANE
set has_flaps = ON
set model_preview_type = 30
set small_angle = 180
set imu_acc_ignore_rate = 9
set imu_acc_ignore_slope = 5
set applied_defaults = 3
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set airmode_type = STICK_CENTER_ONCE
set nav_wp_radius = 5000
set nav_rth_allow_landing = NEVER
set nav_rth_altitude = 15240
set nav_rth_home_altitude = 4572
set nav_fw_climb_angle = 16
set nav_fw_dive_angle = 16
set nav_fw_loiter_radius = 5000
set nav_fw_control_smoothness = 1
set nav_fw_launch_velocity = 150
set nav_fw_launch_accel = 1500
set nav_fw_launch_motor_delay = 100
set nav_fw_launch_timeout = 10000
set nav_fw_launch_max_altitude = 4572
set nav_fw_launch_climb_angle = 20
set osd_units = UK
set osd_crosshairs_style = AIRCRAFT
set osd_left_sidebar_scroll = ALTITUDE
set osd_right_sidebar_scroll = SPEED
set osd_sidebar_scroll_arrows = ON
set name = Nomad
set stats = ON
set tz_automatic_dst = EU
set vtx_band = 3
set vtx_channel = 2
set vtx_power = 3

# profile
profile 1

set fw_p_pitch = 15
set fw_i_pitch = 5
set fw_d_pitch = 5
set fw_ff_pitch = 90
set fw_p_roll = 15
set fw_i_roll = 3
set fw_d_roll = 7
set fw_ff_roll = 60
set fw_p_yaw = 20
set fw_i_yaw = 0
set fw_ff_yaw = 100
set max_angle_inclination_rll = 450
set dterm_lpf_hz = 10
set fw_turn_assist_pitch_gain =  0.500
set nav_fw_pos_z_p = 15
set nav_fw_pos_z_d = 5
set nav_fw_pos_xy_p = 60
set d_boost_min =  1.000
set d_boost_max =  1.000
set fw_level_pitch_trim =  5.000
set rc_expo = 60
set rc_yaw_expo = 45
set roll_rate = 30
set pitch_rate = 15
set yaw_rate = 9
set manual_rc_expo = 50

# profile
profile 2

# profile
profile 3

# battery_profile
battery_profile 1

set vbat_cell_detect_voltage = 420
set vbat_min_cell_voltage = 280
set vbat_warning_cell_voltage = 300
set battery_capacity = 3400
set battery_capacity_warning = 1020
set battery_capacity_critical = 340
set throttle_idle =  5.000
set nav_fw_min_thr = 1000
set nav_fw_max_thr = 2000
set nav_fw_launch_idle_thr = 1200

# battery_profile
battery_profile 2

# battery_profile
battery_profile 3

# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

#

**Comment by MrD-RC** [comment]
Issue identified. Working on a fix.
