### ISSUE TITLE
OSD (inav 1.6 release): Toggle buttons for Home Dir and Home Distance are inverted

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav-configurator#157]
Toggle button for Home Dir activates Home Distance, and viceversa. [See video](https://youtu.be/em8tzH-JVjc)

**Comment by fiam** [comment]
This is definitely fixed in the current release, I've just tested it. I probably fixed it myself without noticing when I rewrote the handling of OSD indicators.
