### ISSUE TITLE
Feature reqest: Create page backup setting to file and restore setting from file

### ISSUE THREAD

**Issue by Fameing** [iNavFlight/inav-configurator#158]
Hi,

Add a new Page or block in setup page backup setting to file and restore setting from a file.

**Comment by DzikuVx** [comment]
Fot the time being please  use `diff all` CLI command

**Comment by Fameing** [comment]
But the best one button to restore the configuration, and a button to avoid updating the configuration file directly.

**Comment by DzikuVx** [comment]
See #145

**Comment by Fameing** [comment]
CLI command to do several operations to save the current configuration file. For beginners not immediately clear how to restore the configuration.

**Comment by DzikuVx** [comment]
I'm not saying that this function will not come back. I'm just saying that old implementation was removed as not working like expected and was not really backuping and restoring.

Backup/Restore will come back if __working__ solution will be found
