### ISSUE TITLE
tmotor f7 hd why can't it connect to inav?

### ISSUE THREAD

**Issue by Pacha240** [iNavFlight/inav-configurator#1584]
tmotor f7 hd flight controller. The firmware is being installed, but then I can’t connect to the drone and go into the settings. com4 is detected but does not enter. although it enters betafly, why can't it connect to inav?

**Comment by MrD-RC** [comment]
Need more information:
- Computer OS
- What have you tried to make it work?

**Comment by slackista** [comment]
TMOTOR F7 HD is not fully supported by INAV. Even If you make build yourself, mapping is broken. Ask me what I know 😉
