### ISSUE TITLE
WRTH by activating WP

### ISSUE THREAD

**Issue by FXvBH** [iNavFlight/inav-configurator#1597]
When I activate WP, I see WRTH in the goggles. The mission is then not flown. Been trying to figure out what's going wrong for 2 days, but can't find anything. Does anyone have an idea what's going wrong? Everything looks good, Arming is working, no problems. But he doesn't do a mission anymore. Flight controller is MATEK F405SE.

**Comment by stronnag** [comment]
You have not loaded the mission into volatile memory.

**Comment by FXvBH** [comment]
If you mean "loaded from EPROM to FC" then I did. Also hung on the laptop, tested whether it came into the FC from the EPROM. If the mission with "load from FC" was neatly put on the map, without taking the power off again test flight, and then again WRTH.

**Comment by stronnag** [comment]
Blackbox log then please

**Comment by FXvBH** [comment]
Hi stronnag, Sunday we will test it and read the black box. You hear.

**Comment by FXvBH** [comment]
We read something about converting man.mode to navwp.mode.
This can cause a problem. Now from man.mode to hor.mode and then navwp.mode.

We didn't get WRTH in the goggles now, but wp. So an improvement

cruise motor up didn't really help.


But the plane wobbled quite a bit. Engine not powerful enough? (Volantex asw28)

Tuesday we do the matek405-se wing in another plane, you hear.

**Comment by FXvBH** [comment]
H Product:Blackbox flight data recorder by Nicholas Sherlock H Data version:2 H I interval:32 H Field I name:loopIteration,time,axisRate[0],axisRate[1],axisRate[2],axisP[0],axisP[1],axisP[2],axisI[0],axisI[1],axisI[2],axisF[0],axisF[1],axisF[2],fwAltP,fwAltI,fwAltD,fwAltOut,fwPosP,fwPosI,fwPosD,fwPosOut,rcData[0],rcData[1],rcData[2],rcData[3],rcCommand[0],rcCommand[1],rcCommand[2],rcCommand[3],vbat,amperage,rssi,gyroADC[0],gyroADC[1],gyroADC[2],accSmooth[0],accSmooth[1],accSmooth[2],attitude[0],attitude[1],attitude[2],motor[0],servo[0],servo[1],servo[2],servo[3],servo[4],servo[5],servo[6],servo[7],servo[8],servo[9],servo[10],servo[11],servo[12],servo[13],servo[14],servo[15],navState,navFlags,navEPH,navEPV,navPos[0],navPos[1],navPos[2],navVel[0],navVel[1],navVel[2],navTgtVel[0],navTgtVel[1],navTgtVel[2],navTgtPos[0],navTgtPos[1],navTgtPos[2],navSurf H Field I signed:0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 H Field I predictor:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,9,0,0,0,0,0,0,0,0,0,0,0,4,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 H Field I encoding:1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 H Field P predictor:6,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,3,3,3,3,3,3,1,1,1,1 H Field P encoding:9,0,0,0,0,0,0,0,7,7,7,0,0,0,0,0,0,0,0,0,0,0,8,8,8,8,8,8,8,8,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 H Field H name:GPS_home[0],GPS_home[1] H Field H signed:1,1 H Field H predictor:0,0 H Field H encoding:0,0 H Field G name:time,GPS_fixType,GPS_numSat,GPS_coord[0],GPS_coord[1],GPS_altitude,GPS_speed,GPS_ground_course,GPS_hdop,GPS_eph,GPS_epv,GPS_velned[0],GPS_velned[1],GPS_velned[2] H Field G signed:0,0,0,1,1,1,0,0,0,0,0,1,1,1 H Field G predictor:10,0,0,7,7,0,0,0,0,0,0,0,0,0 H Field G encoding:1,1,1,0,0,0,1,1,1,1,1,0,0,0 H Field S name:flightModeFlags,stateFlags,failsafePhase,rxSignalReceived,rxFlightChannelsValid,hwHealthStatus,powerSupplyImpedance,sagCompensatedVBat,wind[0],wind[1],wind[2],IMUTemperature,baroTemperature,sens0Temp,sens1Temp,sens2Temp,sens3Temp,sens4Temp,sens5Temp,sens6Temp,sens7Temp,escRPM,escTemperature H Field S signed:0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1 H Field S predictor:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1 H Field S encoding:1,1,7,7,7,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0 H Firmware type:Cleanflight H Firmware revision:INAV 5.0.0 (d2adf35c) MATEKF405SE H Firmware date:Jun 20 2022 11:00:33 H Log start datetime:2022-08-07T10:58:59.906+00:00 H Craft name: H P interval:1/32 H minthrottle:1042 H maxthrottle:1850 H gyro_scale:0x3f800000 H motorOutput:1042,1850 H acc_1G:2048 H vbat_scale:110 H vbatcellvoltage:33,35,42 H vbatref:1243 H currentMeter:0,317 H looptime:1000 H rc_rate:100 H rc_expo:70 H rc_yaw_expo:20 H thr_mid:50 H thr_expo:0 H tpa_rate:0 H tpa_breakpoint:1500 H rates:20,20,20 H rollPID:5,7,0,50 H pitchPID:5,7,0,50 H yawPID:6,10,0,60 H altPID:40,5,10 H posPID:75,5,8 H posrPID:0,0,0 H levelPID:20,5,75 H magPID:60 H velPID:0,0,0 H yaw_lpf_hz:0 H dterm_lpf_hz:110 H dterm_lpf_type:2 H dterm_lpf2_hz:0 H dterm_lpf2_type:0 H deadband:5 H yaw_deadband:5 H gyro_lpf:0 H gyro_lpf_hz:25 H gyro_lpf_type:1 H dynamicGyroNotchQ:250 H dynamicGyroNotchMinHz:30 H acc_lpf_hz:15 H acc_hardware:3 H baro_hardware:0 H mag_hardware:0 H serialrx_provider:9 H motor_pwm_protocol:0 H motor_pwm_rate:400 H debug_mode:0 H features:810028246 H waypoints:8,1 H acc_notch_hz:0 H acc_notch_cutoff:1 H pidSumLimit:500 H pidSumLimitYaw:350 H axisAccelerationLimitYaw:10000 H axisAccelerationLimitRollPitch:0 H rpm_gyro_filter_enabled:0 H rpm_gyro_harmonics:1 H rpm_gyro_min_hz:100 H rpm_gyro_q:500 vA!$ vC#$ vC)$ vC3& vC7( vCA* vCE* vAO, vAU. vAY0 vA_6 vAa8 vAe> vAiB vAkD vAoF vAqF vAsH vAuH vCuH vCwH vCwH vE{F gx4I #0ti 5Vti )]ti -,tl [R%I  1to %Ff7 ki(" ik.6 im2< go8> eq<: cq>6 asD. auF* _yN  c{l" a}p& 1o+I V%'I z!!) |))) |33+ 4* D ~;;+ 8,$D :,(D <.(F @.(F B.(F  D.(F "F.(F $H,*F &J,,F *L,.D ,P*0D .R(4D 2T(6D 4V&8D 6Z$:D 8\$<D <^"<D >b <F  4=1 ".;1 $*;1 &&91 (E!-6 *C#-8 ,C%-< ,A'-> .A)-@ 0A--D 0?/-F 2=1-J 4;3-L 677-N 859-R :5;-T <3=-X <1?-\ >/C-^ @-E-d B+G-f D'I-j F%K-n H#M-p J!Q-t L!S-v N!U-z P!U-~ R#W- T#Y- V%Y- X%[- X'[- Z']- \)]- ^)]- ^)]- `+]- ~`+]- |b-]- |b-[- zd/[- xd-Y- vf+Y- vf)W- th'W- rh%U- rj!S- /`.!l /X.#b /V.%^ /P0%X /L0%V /F0!T zz(1 xr(1 tf(1!4% rZ*1%4# nN*1+2! l@*1-2! j0(112 f"(/52 */72 */92 */;2 ,/=2 */A0 */A0 (/C0 $/E0 xqqE rmmG !/K, lkkK %-I, heeQ '+G, faaU )+E, d[[[ +)A, `WW_ +'?* ^OOc #-%=* ^IIg '/#9* \AAk -/#7* \77o 5/!3* \//q \))u \##w d))y f//y l11y r++{ v''} 3~E# =jE# !1:= #1<= '1@; ~)1D; |-1H; z11L; x51N; v91R; r;1T; n?1Z9 lC1^9 hE1`9 fG1d9 fG1f9 fI1l7 dK1p7 dM1r7 `M1x7 \O1z7 XO1~5 $%$" &%$& ,%&, 0#&0 6#&6 <#&< >#&@ D#&H H#(L N#(R T!&X X!&Z ^!$^! `!$`! f!$h! l!$n c &` _"(^ [$(X W&(V S&(P M((L K((J G**F E**D A,*@ =.*< 7.*: 1.*6 +.*4 #.*0 g;&} W;*i O;(c ?;,Q 7;,G %;,7 ,,;( .4;( 4B;"( 6H;$2  Xr; "`x9 $dx9 &l|9 &p|9 n:/xf+ j:1rd+ b:3h`+ \:3b^) T<7XX) J<7NT) F<7HR) <<9>L) 6<98J) ,<;.F) "<;">) +<7%%)%u /<5)-)'} 9<53;)% =<57C)' E<3?S)' O<3Gc)' S<3Ki)! [:3Sw)! _:3Y}) i:1a q:1i u:3o }83y ]K2w IK4_ ?K2Y -K0I 'K&M 8=-1 2=)5 "=%A !w {45 y w45 dc  &G ha &&G la"*&G pa"0(G va"8(G x_":*G ~_">,G _ B.G }("~\ {,"x\ y0"v\ u2"p\ q6$n^ k8$j^ e<$d^ _@$b^ WB$\^ SF$X`! MH$T`! IJ$N`! EL$J`! ?P$F`! 9R$B`! 3R$>b!| /T$8b +V$6b )X$0b 'Z$.b #\$(b !^$$b `$ b w0 \ y0$\ {0&\ }0*\ 0>^  0B^  0F^  }0T` }0V` }0Z` {0\` {0`` y0db w0db u0fb u0hb s0jb s0jd q0jd q0ld o0ld m0jd k.jf g,jf c,jf _*jf Y(lh S&lh M&lh G$lh C$lh ?$lj ;"lj  7"lj "5"jj &3 jj (1 hl (/ fl (- fl () dl (' bn &# `n &! ^n t!b[Q t!^WQ t!XSQ t!ROQ t!NMQ t!HGQ t!FEQ t!@AQ t!<=Q t!8;Q t!27Q !t!07Q !F0!R J0#R N0'R P0)R R0/R T03P V05P X0;P Z0=P \0AP \0GP \0IP \0OP \0QN ^0UN ^0[N ^0]N \0aN \.cN Z.iL Z.mL X.oL X.sL V.uJ T.yJ T.}J "K.{. "M.u. $O.s. &S.o. &U.m. (U.g, (W.c, (Y.a, *Y.[, *[.Y*  *[.S*  *[.O* *[.M* *[.G* (].E* (].?( &[.;( $[.9( $[.3( "Y.1(  Y.-(  W.'( W.%( W.!( "z& 05& "09& $09& (0=$ *0A$ ,0C$ .0E$ .0G$ 00I$ 00K$ 02M$ 02M" .0O" .0Q" ,0Q" *0S" *0S  (0S  &0U  &0U  $0W  $0W  #$2Y '$2Y )&2Y -&2W /&2W 1(2U 5(2S 9(2S =(2S ?(2Q C(2Q E&2O E$2O E$2O E"2M E 2M B~z  D|z" F|z$ F|x$ H|x$ H|x$ H|x" Jzx  '0t  '0t  '0v  )0x  )0z" )0|" '0|" \{{] \ww] ^ww] ^ww[ ^{{[ ^}}[ ^}}[ b}}[ byy] dss] hmm] hee_ l___ l[[a nWWa nSSc tld! nMMg rlf% nIIi rlh' nEEk plj) lCCm pll+ l??o nll- j==q lln- h99s llp/ h99w jlr/ h77y jlt1 f33{ hlv3 f11} hjx3 f//} fjz3 djz3 dj|3 bj~3 0#.- 0%.+ 0'.+ 0).) 0+.' .-.% 0-.% 0/.# 21.! @b~  @b~$ Bd~( Dd~. Dd~2 Ff|6 Hf|: Hh|@ Jj|D LjzH NlzJ PnxP RpvT TptZ Trr\ Vtp^ Xtn` Zvld ^xjh `xhl dxfp hzdt j|bx n|`| )Q+& h 1Q)* f";S), d$EU)0 b$MU'4 `&UW'6 ^([Y': \(a['> Z*c['B X*g]'D V,i]%F T.m_%J R0qa%L P0ua%P N2wc#T L4{c#V H6{e#Z F8}e!\ 5&&5 9007 988; ;@@? =FFA +)-F =HHE !1-x ;LLI 9RRO 7^^S 5llW 1~~] /xM- /nG- /fA- /\;- /R7- -F1- -:++ -,%+ a"'z k&'r s*'h 4oo< {.'d :cc: @UU8 FGG4 L992 R//0 X%%. z{1C j}1A X{1; D{19 4y/5 "w/3 %a-) ']-' +W-' -S-' 1Q-' 5M-) =I-) GG+) QC+) [A++ 6)+0E e?++ o;++ }y9)- ))=* #1E- -9Gx %9KL ';MR 6Oxo/ 4Qno/ 0Sfm/ ,U^m/ *WXm/ &YPm/ $[Hm-  ]@k- ]6k- _.i- _$g- 41)op ]%7- "-); ])5- [/3- Y31- W51- U91- U=1+ SA1+ QG1+ OK3+ MQ3+ KW3+ I[3+{  I_3+{  Ge5+w Ei5+u Cm5+s #)`N Ao5+q Ao3+o ?m3+m =k1+i =g1+i !%.k ;e/+e 9c/+e 9_-+c 9[-+a 7U++_ 7O)-] 5I%-] 5G%-] 3E#-[ 1G#-[ 1I#+[ /K#+[ -M%+[ +O%+[ )Q%+[ 'S'+[ 'S'+[ %S)+[ #S)+] !S)+] Q)+] M)+] I)-_ C)+_ ;'-_ 3%-a -#+a '!+a 2"-  4$/" 6&/" 8(1" :*5" !:.7" #<0;$ '>2A" +@6E" f||! /@8K" 3B:Q" 5B<Q  5D>M  3D@C  f||) 3DB; frr+ 3DD3 dll/ 5DF/ djj1 7FH- bll5 7DL/ ^nn9 9DN/ \pp; 9DP/ Xll? ;DT- VllC 9DV) RffG 7DZ% N\\K HNNO DDDS @88Y <..] 8&&c 6  g h++g h??a jYY[ lqqU lhR~ nhRx phRt rhRn rhTh rjT` tjTZ vjTT xjTP xjTN zlTJ |lTH ~lTH ~uua |ooc xiie xaag xYYi zQQi ~MMk |,!z ~,#h |*#f z(#d x(#b v$#` t"#` v8!%X t6#'X t6%'X r2'%Z r.)%Z p()%Z p"+%\ NuuG LmmI LeeI J__I l#1!p JYYI l%1!r HUUI ~l'1!t HUUI ~~l'1 HSSI ~|l'1 FQQI |zl'1 DOOI zzl)1 BKKI xxl+1 BGGK vvl/1 @??K rvl31 >55M ntn91 >))M jrnA1 <!!M hrnE1 fpnI/ dpnI- bnnG- blnE+ `lnC+ `jnA+ ^hp?+ \hpA+ XfpC) VfrG) TdtI) RdtK' PbtK' N`vM' L`xM% L`xM% J^zO# H^zO! F^|M D^|M B^~M @^~M L&&q N,,s R00u V22w Z66y \66{ `88}  svz "kvx "cxt $[xr #Sxl #Kxf %Ex` (?xX &9zR $1zJ "+|@ #%|8 #Lf* %\f* %df( 'vf* )~f( Rww2 Poo0 Pkk, Ngg( Lee" b"+3- `(-5- `,/9- ^03=+ "#Gc `47=+ `8;=+ ~`:A;+ xb>G9+ <-7C rb@M9+ ,--M lbBS7+ hbBY5+ bbB_1+ ^bBa/+ ZbBc-+ Vd@e)+ Rd@g#+ Lf@i Hf>k Df>m @h<m <h:o 8j:m 6l8k 4n6g 2p4e 0r4a .t2] *v0Y (z0W $|0W +  ~.Y"+ .[&+ .[(+ ,[*+ ,[,+ ,Y,+ ,Y,+ ,W.+ .W.+ .W.+ .W.+ 0U.+ 0S,+ 2Q*+ 4M&+ 6K$+ ~]]= ~aa? |cc? zcc? z__A z__A x[[C xYYE t"!/UW vYYE v !/SW tWWE v !/QW rYYG x #/OW r[[G x #/MW r[[G x #/KY p[[I #/IY pYYI #/GY pYYI #/EY p[[I !/CY r__I | !/?Y t__K rccK reeK rggK rggK rggK tggM tccM xaaM z__M |[[M ~WWM !/:] !/:] !/>] !/@] !/@] !/D] #/D[ #/F[ #/H[ #/J[ #/L[ #/N[ #/P[ #/RY #/RY #/VY !/VY !/XY !/ZW !# W !/Pv #/Pv %/Rx '/Rx )/Rx +-Tx --Tx -+Tx /+Tz /+Vz /+Vz /+Vz 1)Vz /)Vz /)V| /)V| -'V| -'V| +'V| +'V| )'V~ )'V~ +'X~ +%X~ +%Z~ <O/y :O/u 8Q/o 6Q/k 4S/c 2U/] 0W/Y ,[/S (]/Q $_/I (oo} ,gg{ 2__{ 8WWy >OOy DGGy J??y R55y V11y Z--y `))y f))y j''y l))y n)){ p++} %G-" #G-& #G-, !G-2 !I-6 !S-Z %S-\ 'Q-` )O-b 'O-h 'O-l %O-n #O-r !O-t !M-x 0 1\ 4$1X :*1P >.1H @21D D61< F:18 J<10 LB1( NF1$  b/! #--, #/-4 #5-: %9-B '=-L 'C-P 'I-X #M-^ !S-f #)YH W v+ Y"x+ Y"x+ [$z+ ]&z- _&z- c(z- e(x/ i*x1 k*x3 m,v5 q,v7 s.t9 u.r9 w0r7 y0p9 }2p9 ?"AQ& A$?M& C(?K& E*AG& G,AC( !I0?A(  #I2?=(  %K6?9(  'K8?7(  )M:?3*  +M<=/*  +M@;-*  -OB;)*  {nnq /OD9%* wnns /OF7!* snnu 1OH5 ollw 3OL3 kll{ 3ON1 gjj} 5MP/ 5MR- 7MV+ 7KX+ 9KZ' 9I\% 9G^# n X ? z33} "^nh &^rh (\xh ,Z|h 0X~f m' s i' q e'"k a'"i ])"c W)"_ S)"[ O)"U K)"S E)"O A+"I =+"G 7+"A 5+"? /+"; ++ 7 '+ 5 r B[ n"Fa j"Hi d$Lo ^$Nw ,$$U .22Y 0>>_ 0JJa 0TTg 2``k 4nnq 6zzw >2#) @2%) B2)) }D2)) uF2-) oH2/+ kJ21+ gL25+ aN25+ ]N29+ WN2;+ OP2=+ IN2?+ AN2A+ ;N2C- 3N2E- +L2E- #J0G- J0I- H0K- F0M/ D0M/ B0O/ *3Gww 9>4G ;"HA 7 3] "7"R I,2  C"2" 1 ,l /".f -".^ ) .Z ' .R 2W.} 2W.} 2W.} 2W.} 2W.} 2Y.} 0Y.} 0Y.} .[.{ 0[.{ 0[.{ 2[.{ 4[.y 4Y.y 4Y.y 4W.y 4W.y 4W.y 6U.w 8U.w 8U.w 6S.w 6Q.w 4O.u 2M.u 2K.u 2G.u 2E.u 0C.u 0A.w 2?.w 6?.w 8=.y :;.y <9.{ <5.} :3.} '+x0/ %-n2/ !/b2/ 1V4/ 1J4/ 1@6/ 388/ 30:/ 3(>/ 3 @- 5#F+ 5+D+ 73B+ 79>+ 7A>+ 9E<+ 9I<+  9K<+ $9M<+ fyyh &;M<+ jwwh (;O<+ lssh ,;O<+ pqqh .;M<+ rooh 2;K<+ tqqh 49I<+ xqqf 89G<+ zoof :9E<+ ~mmf >9E:+ @7E:+ D7E:+ F5G:) H5I:) L3M8) N3O8) P1Q6' R1U6' T/Y2' V/[0% X-_.% Z-a,% \+c,% ^+e*% `)g*# b)i(# ~f'k(# zh'm*! vj%m(! tl%m(! pn#m(! ln#m&! fp!o$ br!s" Rxx- Rdd+ RNN' T@@% T22# V((! #s w |##6 BH!yy! BJ!}y 0"Ow$ ,$Ku$ *&Gs$ ((Aq$ &,=q$ $.7m$ "03k$  23g$  47c$ 8;a& :A]& <GY& >GW& >EU$ @=Q$ @3O$ B)M"  11% sx06 ]x4N Sx6Z ?x4l 7v2r 4tAf UtM- ctM= &nrE &dtE &RtA $Ht?| $6t=l $$t=Z $'t5 $9t3 &At3 &Qt3 &at1 $gr1' $wr17 o}}c iuue eoog _iii [eek Waam Q]]o 2<iw2N KYYq 2>iq2N CUUu 0@ii2N ;QQu 0Bi_2P  3MMw 0DkW2P  )CC{ 0FmM2N  0HqC2N  0Js;2L  0Lu32J  0Lu+2H  2Nu#2D" 26"'0 22")* 2*"- 2""1 ~<\s z>\s 2 v@^s(2 rB`q.2 nFbo42 lHbk:2 jLdg@2 hNdaF2#"=? fRf]L2/"?K bVh[T25"?Q ^Zh[Z2?"?] \^j[^2E"?c Z`lYd2O"?m VdnWh2["A{ TjnWn2a A PnpUt2k A LrrWz2q C HvrW~2} C F|tY ,w/*} ,o/*u ,i1*q ,a1(k ,[1(g ,S1&_ ,K1&W ,E3&S ,=3&K ,73$G ,/3$? ,%3"7 %"Z{ ,!3 3 '.lc 5,@k }0^1 y0d1 u0h1 q0p/ m0t/ g0z/ (!^` \-#!? j/-!A x/3!C 1?!E 1E#G 1Q#G 1]#I 1c#I 1o#I 1u#K "($6 o~d/ qx\/ stV/ unN/ whF/ wb@/ y\:/ {V2/ {P,/ {H&/ }@ / _+uY: c+kY< e+gY< #i+]Y<{ 'm+WY<w +o+M[<m -q+C[>a 1s+?[>] 5w+5[>S ;y+/[>M ?{+%[>C %!eg #%]% #%g] ) [< )*[< )4[: )8[8 +B[6 +F[6  +N[6( +XY40 -/f2 +\Y24 +dY0: /-LX +hY0< 1/TK +nY.B +vW,H +zW*L Ue{+ Ugy+ }..~ Siw+ {44| Qku+ {<<z Omq+ yDDx Moo+ wLLv Kqm+ uRRt Isi+ sZZr Gug) q``p Ewc) offn Cya) mnnl A{]) kttj ?{[) gxxh ={W) e~~f ;{U) 9{Q) 7{M) 5{I+ 3{E+ 1yC+ /y?+ -y;+ +w9+ 'w5+ %u3+ #s/+ m%+~= k#+|= k!+x= 9~~E =xxG ?vvI CppK EnnM GhhM KddO M``Q O\\S QXXU STTW URRY WNN[ WJJ] YHH] [DD_ [BBa ]<<c ]88e _22e _,,g 6=1 / a&&i :;1 / >;1"/ B91"/ D91"/ F71$/ H71$/ H51$/ J31$/ L11$/ N/1$/ P+1$/ P)1$/ P%1"- P#1"- &1 :A( y (5 @A(&{ *9 L?*4} .; R?*<} 2? ^?*J} l?.Z{ r?.by =.pw =.vu "J 6 &J 0 *H , ,H & ,H " &".pX _qqy caa{ +)|a Vze/ 159Q 51;I !);] ,|a- (ra1! "`a-/ Xa-7 !'9I Fa-G 4_-Y /%35 ._'[ ;!/w 9%/a ;#-[ 9D+! ?D-+%_ GD/5/_ KD1;5_ SB3E?_ YB5KC_ aB5UK_ iB7_Q_ oB7eU_ w@7o]_ {@7u__ 4q c 4m"c 4e(c 6[,c 6U.c 6M4c 6I6c 6A:a 49@a 45Ba 6+Ha 6'Ja 4!Pa ( ~_ !;2I !A8I !C8I !I>I !K@I !Q@I %;-Z +=-^ 1?-` 7A-f ;C-j ?G-l CI-r EO-t GS-z %I&# !7<, !9$L !9@z );*K +z('z +x('v +p()n +l()j +f(-` +^*-X -Z*-V -R*-P -P*+N -H*)J -B*'F ->,%D +8,%@ +6,%< +0,#6 +*,#2 +(,!0 +",!, Q(+#,% S(+%,# S(++,## Q(-1,!' M(-3, I&-9, C$-;, ?"-?, 9 -E* J 1y N"1y R$1{ T&1{ X&1} Z&1} \&1} "ee<  gg6  MM2 $OO2 J"1{ (SS2 L$1} *SS2 N(1} ,WW2 .YY2 0]]2 4aa4 6cc4 8ee4 <cc4 >cc4 @cc4 B__4 F__4 J]]4 L__4 N__4 Paa4 R__4 T[[2 XUU2 ZQQ2 \MM2 `II2 dGG2 fEE2 jCC4 nCC4 rEE4 vII6 vOO6 |WW6 ~__6 |==. x;;. t77, r77, p55, n55. n33, l33. l33. l11. l//. l--. j)). j'', j%%. j##, j!!, h%%0 l--0 p330 r990 v==. xAA. xEE. xGG. xII. zII. zGG. |CC. ~??. ~;;. ~77. ~11. ~)). ~##. x""$ x**$ x22" x::" vBB  vFF  {~2o x  - x""- x((- %j0; x,,- )l0; z22/ -l09 z66/ 1n09 z::/ 5n07 x>>/ 7n07 x@@/ ;l07 xDD/ =l07 xDD/ =l07 vDD/ =j07 vHH/ Aj07 tNN3 Kj07 vZZ5 Wl27 vjj5 cl29 vrr5 ml29 v||5 sl27 yl27 M= k G= e ;= Y /= M $\\! "ZZ! "ZZ!  XX!  XX#  XX# J\\! J``! Ldd# Ndd% Nhh' Rpp' Txx' X~~) $ ~A $"~? $"|? $"|? &"|? &$z? &$x= &&x= &&v= &&v= &(t; &(r; $(r; $*p; $*p9 "*n9 ",l9 ",l9  .j7  .j7  .h7  0h7  0f7  0f5 #pp3 %pp3 %pp3 'nn3 )nn3 )ll5 +ll5 +jj5 +jj5 +ll5 -jj5 -jj5 -jj5 -jj5 -ll5 -ll5 -ll5 -nn5 +nn5 +pp5 )rr5 )rr5 'rr5 %rr5 %rr5 #pp3 !ll3 !jj3 t!)j0 #{{. n!)l2 #ww. j!)l2 #qq. d!)n2 #kk. ^!)p2 #ee, Z!)p4 #aa, T!)p4 #[[* P!'r4 #WW* L!'r4 #QQ* !II( !CC& 61c~ 61c~ 61e~ 61e~ 61e~ 61g| 61g| 61g| 61g| 61i| 41iz 41kz 21kz ~01mz z01ox v.1ox t,1qx r*1sx ,}}6 r(1sx *}}4 *uu$  2Cr $2Gr (2Ir ,2Mr 02Qp 42Sp 82Yp <2[p @2ap B2en D2in F2on J2qn L2wn P2{l |||3 ~tt3 <||1 8zz1 ,vv3 $tt3  VV3 $RR3 *PP3 0NN3 6LL3 <LL3 DLL5 JLL3 PJJ3 XHH3 ?R2! ^HH3 ?X2# dFF3 =^2' jFF3 =d2) pFF3 =h2- tFF3 =n21 zBB3 ;r25 7v29 7z0; 5~0? ^0}3 j""/ ^0{3 h**/ '^2w5 h22/ /\2u5 h::/ 7\2q5 hDD/ ?\2m7 hLL1 G\2k7 hVV1 O\2g7 h\\1 U\2e7 f``/ YZ2a7 fdd1 [Z2_9 dff1 ]X2]9 bhh1 ]X2[9 bff1 [V2Y9 `bb/ WT2W9 ^^^1 QR2S; \XX1 KP2S; ZPP1 EN2O; XJJ1 ?L2O; VDD1 ;L2K; V@@3 7L2I; V<<3 3J2G; T883 1J2C= T443 -J2A= T223 +J2== T223 +L2;= V223 +L29= T223 -L25= T443 /J23= T443 /J21= T443 /J2/? R443 -H2-? R223 +H2+? P..3 )F2)? N**3 %D2'? L&&3 B0%? J  3 @0%? >0#? <0#? <0!? N0"? N0$? L0(? V  1 L0*? V$$1 L0,? V&&1 #L20? T,,/ 'J22? T../ +J24? R44/ /H28? R66/ 1H28? P88/ 3F2<= P<</ 5D2>= N<</ 5D2@= L>>/ 7B2B= J>>/ 7@2D= J@@/ 9@2F= HBB/ ;@2H= HBB/ ;>2J; HBB/ ;>2L; FDD/ ;>2N; FBB/ ;<2P; FBB/ 9<2R; DBB/ 9<2T; D@@1 9<2V9 D@@1 9:2X9 D>>1 7:2Z9 B>>1 7:2Z9 B<<1 5:2\9 @::1 382^9 @881 182^7 >881 162`7 >881 /62`7 <441 -42`7 :221 +40b7 8..1 '20b5 8**1 %20b5 8((1 !00b5 8&&1 00d5 6""1 00d5 6  1 00d3 00d3 00f3 00f3 00f3 00f1 00h1 00h1 00h1 20j/ 20j/ 20j/ 20l/ 20l/ 20l- 20l- 40n- 40n- 40n+ 40n+ 40p+ 40p+ 40p+ 40p) 20p) 20r) 20r) 20r' 20r' 20r' 20r' 20r% 20r% 00t% 00t% 00t% 00t# 00t# 00t# 00t# 00v! 00v! 00v! 00v! !YY' #[[' #]]' #__' %__' %]]' %]]' %]]' %]]' %]]' ']]' '__' '__' )__' )__% +aa% +aa% +aa% -cc% -cc% -cc% /ee% /gg% /ii% /kk% /kk% /mm% /mm% /mm% /mm% /mm% -oo% -oo% -oo% -qq% +ss% +ww% +yy% )}}% $y!H #m%D $c)> #Y-8 #S12 %O9. %I?( %AE" #55* %33* )33( -//( /++( n0%x f0%p T0+X L0-N :0-< *0)0  0+$ v#0/# p50/5 l?0/? hO0-M f_0'Y fg0'_ hw.+u !'#9 r  + p""+ l$$+ j""+ h$$+ f""+ ~  / ~  / ~""/ ~&&/ |&&1 |**1 |**/ |,,/ |,,/ |,,/ |,,/ |,,/ |../ |../ |,,/ |,,/ |,,/ |**/ |**/ |((/ |((/ |((/ |((/ |((/ ~((/ ~&&/ ~((/ "2,U $2.U &2,S (2,S (2,S *2,S *2*S ,2(S .2(S 22&S 42&S 62"S 82 S x2!Q z2%S z2)S z2+S z2/S |21S |23S |27S ~29S ~2;S ~2=S ~2?U ~2YW ~2[Y ~2]Y |2]Y |2_Y |2aY |2aY |2c[ |2c[ z2e[ z2g[ z2g] z2i] z2i] x2i] v2i] v2k_ v2i_ {v2i_ ut2i_ st2ia qt2ia or2ga ~zz3 mr2ga ~vv3 ip2ea |rr3 ep2ec |nn3 an2cc zll3 _l2cc xhh3 ]l2ac xhh3 [l2ac vff3 [j2_e vff3 ]j2]e thh3 ]h2]e rff3 [f2[e pdd3 Yd2Ye nbb1 W`2Wg l^^1 S^2Wg jZZ1 O^2Ug hVV1 K\2Sg fRR1 GZ2Qg dLL1 CX2Og bHH1 ?V2Oi `DD1 ;V2Ki `@@1 7T2Ki ^<<1 3R2Ii \881 1P2Gi Z441 -P0Ei Z221 +P0Ck X001 )N0Ck X..1 )L0?k V001 )L0=k T001 )J2=k T00/ +J29k R22/ -H29k P22/ -H25k P441 /F23m P88/ 1F21m N::/ 3D2/m N::/ 5D2-m L::/ 5B2)m L::/ 3B2'm J::/ 3@2%m H88/ 1>2#m F66/ 1<2!m D66/ B66/ B44/ @22/ >22/ <00/ :../ 8../ 6,,- 4**- 4((/ 2&&/ 0$$/ 0$$/ .""/ .""/ ,""/ ,""/ ,""/ ,""/ ,""/ ,$$/ &2 m .$$/ &2 m .$$/ &2$m .$$1 (2&m .  1 (2(m (0,m (0,m (00m (00m *04m *06k ,06k ,08k .0:k 00<k 20>k 20@k 20Bk 40Bk 40Di 40Fi 60Hi 60Ji 60Ji 60Li 60Pg 5D$X 76cs 72y1 9,+O 5$6a ,90E 63.$ 4/,I F/,Y H-(s 2+,i> #E0{ -/Je /1P; .3bWk $) b cJJ( uRR, {RR, }PP. {<<, q::, q66& q44$ y@@  %%1% !'5g 1'59 9!7T EDxQ mzzP End of log (disarm reason:4)

**Comment by stronnag** [comment]
1. You cannot enter WP mode from manual
2.  Only post BBL as an attachment.

**Comment by FXvBH** [comment]
Hi Stronnag.
Thank you.
Greetz Frans
