### ISSUE TITLE
Change in D-Term mechanics rusulting reset values to 1.00

### ISSUE THREAD

**Issue by slackista** [iNavFlight/inav-configurator#1600]
```
CONFIGURATOR 5.0.0
FCFIRMWARE 5.0.0
```
To reproduce:

* PID Tuning -> Mechanics -> D-Term mechanics
* Change any value in `D-Term mechanics` Section
* Save
* Refresh

`D-Boost Min. Scale` and `D-Boost Max. Scale` are reset to `1.00`

Only way to change `D-Boost Min. Scale` and `D-Boost Max. Scale` is via CLI.

**Comment by MrD-RC** [comment]
Fixed in 5.1.

**Comment by slackista** [comment]
No PR # link?
