### ISSUE TITLE
Matekf722-se

### ISSUE THREAD

**Issue by oleg05-60** [iNavFlight/inav-configurator#1609]
With software, it's betaflight 
The quadcopter pulls to the side.
What can be done in this case?
Thanks 
![1662389309239234786640070593287](https://user-images.githubusercontent.com/63141570/188475185-3c76e5b5-d926-4f88-b401-b55229b9b9de.jpg)

**Comment by MrD-RC** [comment]
You may be better off checking out BetaFlight setup videos. Or ask BetaFlight. The BetaFlight Discord server would probably be your best option https://betaflight.com/
