### ISSUE TITLE
conflict between onboard barometer and external mag 5883 FC MAMBA F405US_I2C 

### ISSUE THREAD

**Issue by Bookwormjim** [iNavFlight/inav-configurator#1617]
flight controller MAMBA F405US_I2C (MAMBA Basic F405 MK3 stack)
when I connect an external GPS+mag Matek M8Q-5883 to I2C pins, mag and onboard baro do not work.
Baro works without magnetometer, magnetometer works on another FC Matek.
The FC manual says that you need to enter CLI commands
set mag_i2c_device = 1
set mag_bustype = i2c

But, INAV says that he does not know such commands.
I tried these commands in betaflight and the problem got fixed.
I didn't find any similar commands in the list of INAV CLI commands, maybe I didn't look well.

**Comment by DzikuVx** [comment]
This is not INAV Configurator issue. It's not even INAV issue as I2C is multi device bus by default. The issue seems to be caused by your setup
