### ISSUE TITLE
OSD Elements Causing Settings Issue

### ISSUE THREAD

**Issue by joshfisk3** [iNavFlight/inav-configurator#1618]
Flight Controller: Matek F722 WPX
Inav Version: 5.1
Configurator Version: 5.1
OS: Windows 11

Changing element items while having the HD video format option selected and using HDZero VTX on a port seems to have issues first saving and secondly will occasionally reset many of the settings on the flight controller as well as causing the settings validated pre-arm check to fail. This issue seems to happen mostly when changing the system messages and fly/on-time timer osd elements. Any change to these elements causes the issue described.

The receiver channel map is reset to RET and Receiver Mode section is completely cleared out.
![Screenshot 2022-09-14 083814](https://user-images.githubusercontent.com/28787095/190199788-d3306272-d3cf-481d-8b85-776434f07ddf.png)

![Screenshot 2022-09-14 083528](https://user-images.githubusercontent.com/28787095/190199781-574e42ea-f4e3-4161-8b66-dcd413de0ba6.png)

Edit: After calibration is completed and the settings validated is showing a red x, using the cli no longer works. For example, attempting to use the CLI and typing status results in no output in the console. If I am able to get into the CLI before calibration is completed I am able to execute commands but the status command does not return any invalid settings.

**Comment by MrD-RC** [comment]
I don't have HDZero. But have enabled HDZero in ports, and switched to HD on the OSD Page. I can't replicate this problem at all. I have disabled elements, moved them, had them straddling the red line. Nothing wipes any settings, nor locks up the CLI.

All I can recommend trying is:
- Make sure you are using the correct target. For that FC it's pretty obvious (**MATEKF722WPX**) so I don't think its' that. But always worth checking.
- Make sure you have switched off the FrSky Pixel OSD on the ports page. Maybe having two external OSDs on UARTs could be causing strange things to happen.

**Comment by joshfisk3** [comment]
I think you were right on the Frsky Pixel OSD. After removing that seems to be working just fine as well as helped with wtfos issues I was having. Thank you for that advice.
