### ISSUE TITLE
Problem: Calibrate magnetometer button greyed out

### ISSUE THREAD

**Issue by avirotstein** [iNavFlight/inav-configurator#162]
Calibrate magnetometer button in the inav configurator (1.6.2) is greyed out unless first clicking sensors tab and then clicking back to the setup tab

**Comment by AustinSaintAubin** [comment]
Problem remains in Configurator 1.7.0 w/ firmware ( INAV/SPRACINGF3MINI 1.7.0 Apr 19 2017 / 09:28:25 (65cbad0) )

**Comment by dragon1020** [comment]
Problem remains in Configurator 1.7.1. :(

**Comment by Ogocology** [comment]
So sorry to post on an old issue.
I have this problem at the moment and I cant figure out exactly how to make it go away.

Any help please?

**Comment by cdsisf** [comment]
![problema gps](https://user-images.githubusercontent.com/37956843/38163610-dbc37876-34ee-11e8-8fcb-d7f062e7d83e.jpg)
the same problem here, here are my connections

**Comment by Ogocology** [comment]
Hello,For the calibration grey out issue, the temporary fix is to click on any other tab ( like configuration first) then go back to calibration. That solved it for me.
Your GPS showing red possibly means you got the connection wrong. Switch the TX and RX connections and check.
Br,Ogocology
    On Saturday, March 31, 2018, 2:22:03 PM GMT+1, cdsisf <notifications@github.com> wrote:  
 
 

the same problem here, here are my connections

**Comment by cdsisf** [comment]
Changing Tab does not solve the problem. You really are right, by doing this I will activate the button but after finishing the calibration time I can not record the calibration. Maybe it's the MAG that has something wrong. The MAG appears in blue but if turned upside down it turns red. Although it seems that the MAG (HMC5983) is recognized, in the Tab of the sensors shows no sign of life.
