### ISSUE TITLE
does inav configurator work on windows 11

### ISSUE THREAD

**Issue by csessa5** [iNavFlight/inav-configurator#1670]
i am new to fpv and intend to use inav to run my flight controller.  I tried downloading the zip files but the extension install does not work.  I am using windows 11 on a dell laptop.  it is the only choice I have.

So i need to know if this should work and i am doing something wrong or if i have to wait for the configurator to be updated to work with windows 11.

**Comment by MrD-RC** [comment]
It works fine on Windows 11. You need to download from here https://github.com/iNavFlight/inav-configurator/releases
