### ISSUE TITLE
Servo tab not allowing mixer source inversion

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#168]
We don't have access to source inversion for servo mixer inputs.

![image](https://cloud.githubusercontent.com/assets/11059099/23831916/1f26a478-0776-11e7-9f79-9d852f331590.png)

I suggest replacing the marked area (which is **channel to forward**) with mixer source inversion flags.
```
    INPUT_STABILIZED_ROLL = 0,
    INPUT_STABILIZED_PITCH,
    INPUT_STABILIZED_YAW,
    INPUT_STABILIZED_THROTTLE,
    INPUT_RC_ROLL,
    INPUT_RC_PITCH,
    INPUT_RC_YAW,
    INPUT_RC_THROTTLE,
    INPUT_RC_AUX1,
    INPUT_RC_AUX2,
    INPUT_RC_AUX3,
    INPUT_RC_AUX4,
    INPUT_GIMBAL_PITCH,
    INPUT_GIMBAL_ROLL
```

**Comment by oleost** [comment]
I'm example using aux to servo to be able to trim in flight by adjusting servo midpoint with aux channel.

Also how are one able to control which aux Channel to move servo gimbal feature if you remove it?

**Comment by digitalentity** [comment]
@oleost good point. Then we need something else for source inversion config - `smix reverse` in CLI

**Comment by oleost** [comment]
But what do you need it for? We have servo reverse by setting -100 ?

**Comment by digitalentity** [comment]
It's not servo reversing, it's servo input reversing.

**Comment by oleost** [comment]
Yes it's reversing the output from mixer to servo if I understand correctly.

**Comment by digitalentity** [comment]
@oleost no, it's reversing the input:

RC/Stabilisation -> `smix reverse` -> servo mixer -> `servo rate` -> servo

**Comment by oleost** [comment]
Yes what I meant.
