### ISSUE TITLE
problem Flash inav 6 H 743 Matek

### ISSUE THREAD

**Issue by Fabwize** [iNavFlight/inav-configurator#1680]
hello, I can't flash my H743 Wlite Matek  and F411 WTE in Inav 6.
i come from inav 5.1
In DFU mode I load the firmware, but it won't install. 
I proceeded as described on the realese inav 6. 
when I go back to inav 5.1, the 2 FCs work
should we wait for the next version?

**Comment by MrD-RC** [comment]
Are you using Configurator FP2, if using INAV 6.0?

**Comment by Fabwize** [comment]
@MrD-RC  yes FFP2 work from yesterday. thanks.
