### ISSUE TITLE
Using Inav-Conf without connection

### ISSUE THREAD

**Issue by ammikey** [iNavFlight/inav-configurator#1684]
Would it be possible to make the Inav configurator program more like EdgeTX companion? In that the flight controller setup could be done without being connected to the FC then sent to the FC when setup up is complete. Being able to load a previous setup and review what may need to be adjusted before actually connecting to the flight controller would be a great help in fine tuning my setups.
Thanks Mike J.

**Comment by MrD-RC** [comment]
SITL is being worked on by @Scavanger which will allow use of the Configurator without a physical FC.
