### ISSUE TITLE
can not communicate with the FC

### ISSUE THREAD

**Issue by csessa5** [iNavFlight/inav-configurator#1687]
I have downloaded Inav for iMac.  it all seems to work up to the point of flashing the FC.  I am seeing messages I do not understand so I need some help getting this resolved.

I am using a Mateksys f204-WMN and Inav 6 loaded to an iMac. 

When i go to the FC page i first see a message:  Connected to: /dev/tty.Bluetooth-Incoming-Port

Then it changes to :    MSP connection successfully closed

I select the proper board and version and load firmware (online).  I get message "Loaded Online Firmware: (545426 bytes)"

Then I plug in the FC.  Press the Flash button and get this message:  Connected to: /dev/tty.Bluetooth-Incoming-Port.

Then nothing.  The bluetooth seems wrong but I am stuck.  Likely an installation issue but well over my head.

Help.

**Comment by JekleFPV** [comment]
You got quite a lot further than I did then. On mine it won't even start. Icon bounces for a second and then the dot underneath disappears again...

**Comment by RobinatiNav** [comment]
I have iMac and MackBook Pro both running OSX Monterey and I have no problem with iNav 6. My FC is Matek H743-WLITE.

<img width="1199" alt="Snímka obrazovky 2023-02-24 o 11 11 42" src="https://user-images.githubusercontent.com/123115426/221152884-fc529d9c-ac98-4e51-b873-9590d3410e98.png">
<img width="1198" alt="Snímka obrazovky 2023-02-24 o 11 12 14" src="https://user-images.githubusercontent.com/123115426/221152898-724b7e5c-2788-4d51-833f-b82d14c93395.png">
<img width="1199" alt="Snímka obrazovky 2023-02-24 o 11 14 58" src="https://user-images.githubusercontent.com/123115426/221153074-d6b5368b-bb31-46ad-8ebe-85f0dabae47e.png">

**Comment by mmosca** [comment]
> You got quite a lot further than I did then. On mine it won't even start. Icon bounces for a second and then the dot underneath disappears again...

Right click on the configurator and select open. I think some security settings prevent "downloaded" apps do launch the first time.

**Comment by RobinatiNav** [comment]
Yes, you need to allow this 3rd party app to be running in your OSX

**Comment by Kamdozer** [comment]
Similar issue on Mac with latest OS. Downloaded Configurator 6.0, managed to flash the Inav 6.0 official version from 2.6, after unplugging all peripherals due to problem going in DFU. After successful flash can not connect - just a message MSP port opened successful and after that closed. Led stay red all the time, never changes to blue. No idea what to do now...
