### ISSUE TITLE
The mission planner map appears blank

### ISSUE THREAD

**Issue by DiehardFPV** [iNavFlight/inav-configurator#1688]
Hello, I encountered this problem when using the INAV5.1 configurator
The maps seem not load but the waypoint can be set
<img width="1120" alt="微信截图_20230112135949" src="https://user-images.githubusercontent.com/69829019/211989399-ef070d9d-1acb-453f-b796-70a341e7c5d6.png">
Should i use API key?
![image](https://user-images.githubusercontent.com/69829019/211989583-116a15e3-9f62-40db-b4aa-0484b5a3cfba.png)

**Comment by DzikuVx** [comment]
It's all described in the Readme under how to use bing maps
