### ISSUE TITLE
Configurator wants firmware update with a new firmware installed

### ISSUE THREAD

**Issue by Ndwoo10** [iNavFlight/inav-configurator#1700]
![INAV](https://user-images.githubusercontent.com/98816299/213401530-e6f89ca5-f034-46fe-b2fe-e7b3dc67f76e.png)
Currently using configurator version 5.1.0 (fresh install)
flashed INAV 6.0.0 to a TMOTRF7V2 to a Tmotor F7 FC
Configurator states i need a firmware upgrade to use tabs other than CLI

**Comment by MrD-RC** [comment]
This is normal, and the way it has been for years. You should absolutely always match the major version number of the firmware and configurator. If same major and minor versions numbers are available, match those too.
