### ISSUE TITLE
iFlight Blitz F7 V2 AIO board support

### ISSUE THREAD

**Issue by CadenjPerry** [iNavFlight/inav-configurator#1726]
I figured the iFlight Blitz F722 or F7 Pro existing targets would work but neither do. After flashing the FC won't even show up as a com port until I put it back into DFU mode. I got the FC for an INAV build and it would be great to get that working. A Betaflight target already exists, I just don't have the know-how to get it ported to INAV

**Comment by DzikuVx** [comment]
Please contact iFlight customer support
