### ISSUE TITLE
weird behaviour when Tx signal is lost on the ground

### ISSUE THREAD

**Issue by RobinatiNav** [iNavFlight/inav-configurator#1730]
When on the ground and armed if Tx signal is lost the flight mode is switched from Manual to Angle and servos/control surfaces act weird. See attached picture, please.

<img width="1183" alt="Snímka obrazovky 2023-02-20 o 8 18 38" src="https://user-images.githubusercontent.com/123115426/220039137-591e67e8-58fa-4352-912a-7946210cefcf.png">
<img width="1184" alt="Snímka obrazovky 2023-02-20 o 8 18 23" src="https://user-images.githubusercontent.com/123115426/220039147-7879b484-60ac-4dd8-8933-1e2313a44e92.png">
<img width="1184" alt="Snímka obrazovky 2023-02-20 o 8 17 49" src="https://user-images.githubusercontent.com/123115426/220039148-42bd4eac-35b9-4fe3-81da-c602b6a22719.png">
<img width="1183" alt="Snímka obrazovky 2023-02-20 o 8 16 54" src="https://user-images.githubusercontent.com/123115426/220039149-9ec3e1c9-9b88-48e3-9a4f-79357ee59670.png">

**Comment by MrD-RC** [comment]
This is an issue with your failsafe setup on the receiver. At no point in these screenshots does INAV think it is in failsafe. The parachute failsafe indicator is never red. It looks like you have your receiver failsafe set up so that the channels go to certain positions.

**Comment by RobinatiNav** [comment]
I have failsafe disabled in Rx.

**Comment by MrD-RC** [comment]
Then when you lose RC link, the receiver will do whatever the hell it wants. You can't expect this to work correctly if the failsafe is not correctly set up.

**Comment by RobinatiNav** [comment]
This is crazy. I tried 3 different Jeti Rx with failsafe disabled and got the same result. I'm flash and clear FC and make new configuration and then come back

**Comment by MrD-RC** [comment]
Don't disable failsafe. That is the problem. I don't know what the correct failsafe setting is on Jeti. On FrSky is is no pulses or hold. On Crossfire it is cut. So if you have any options like that, they may be worth trying.

What you need to happen is when you switch off your transmitter, the little parachute top centre should turn red. When you turn the transmitter back on, it should return to grey.

**Comment by MrD-RC** [comment]
@DzikuVx do you know what setting Jeti should use for failsafe?

**Comment by RobinatiNav** [comment]
Thanks Darren, I am getting crazy. I tried HOLD, Out OFF, and Fail-Safe (particular value for each servo output) but none of those worked :(

**Comment by DzikuVx** [comment]
No, I no longer own Jeti. Probably Out OFF should be correctly detectable by INAV

**Comment by RobinatiNav** [comment]
OK, what should I see when TX signal is lost apart from RED parachute? What flight mode? I have set RHT in failsafe settings but RTH would not work on the ground.... I am completely gone here. I do not understand that

**Comment by MrD-RC** [comment]
The red parachute is the best tell tale on the ground. In flight if the failsafe setting is RTH, that's what it can do. There was a procedure for testing on the ground. But in all honesty, I just use the parachute these days. 

I believe the procedure was something like:
1. Prop off
2. Arm
3. Raise the throttle 
4. Run with the model and transmitter for 50 metres
5. Switch off the transmitter 

Then you should see the motor increase and the elevator pitch up.

**Comment by MrD-RC** [comment]
@RobinatiNav just out of interest. What happens on the receiver page? Could you make a screen grab with and without RC link connected.

It sounds like failsafe may be working, going by !FS! in the OSD. Emergency landing would also be correct.

**Comment by RobinatiNav** [comment]
it remains the same

<img width="1282" alt="Snímka obrazovky 2023-02-20 o 12 54 24" src="https://user-images.githubusercontent.com/123115426/220099978-1c823944-f970-40db-b956-9df59e8f0a17.png">

**Comment by RobinatiNav** [comment]
Is it possible to get nav modes active on the ground? just for testing. I managed it somehow and it looked like it woked. The rad parachute was there and throttle at cruse speed, pitch as up. I do not know ho I did it

**Comment by RobinatiNav** [comment]
I unplugged the Rx from the FC to know if it is for sure the RX failsafe doing problems but it behaved the same like when only Tx signal was lost. The manual mode was switched to the angle mode but no red parachute.

**Comment by RobinatiNav** [comment]
I tried something. I went aprox. 10m away from my iMac to arm the FC from some distance, then came back and simulated the Tx signal loss. See result on pictures: 

<img width="1282" alt="Snímka obrazovky 2023-02-20 o 15 55 22" src="https://user-images.githubusercontent.com/123115426/220140382-14201ff5-57eb-47f7-90e9-43533f86e2ff.png">

<img width="1281" alt="Snímka obrazovky 2023-02-20 o 15 55 45" src="https://user-images.githubusercontent.com/123115426/220140364-5483baa3-caba-4e71-990e-dc3f727208b5.png">

**Comment by RobinatiNav** [comment]
I have one important question at the end. When failsafe (RTH) is activated two modes are active simultaneously. RTH and ANGLE. In case the GPS signal is not present for some reason RTH will not work but ANGLE will do like when testing on the table. In this scenario the throttle will by cut off, pitch and roll will act weird for no reason, and plane will go down almost immediately. Why is it working like that?

**Comment by RobinatiNav** [comment]
Hi Darren,

could you please check weird behaviour when Tx signal is lost on the ground <https://github.com/iNavFlight/inav-configurator/issues/1730> my last comment. I think I found a bug. Thank you

Robert.

**Comment by RobinatiNav** [comment]
After huge investigation I can say the angle mode I don't see it is doing what I expect from it is probably not a fault but performed emergency landing. I do not like it goes down in spiral but I can confirm it is safe. Tell me if I am wrong.
