### ISSUE TITLE
Mag align helper

### ISSUE THREAD

**Issue by ltwin8** [iNavFlight/inav-configurator#1746]
## Current Behavior
graphical mag align helper is not very useful, leaves room for misinterpretation, does not state what the default gps orientation is (cw270flip like m8q5338??) where is the arrow and so on.

## Desired Behavior
implement a mode like the various auto tune mode on fixed wings, instruct pilot to fly northways for eg. 100m STRAIGHT, instruct pilot to fly east fo 100m STRAIGHT and then assign the axis that has icremented accordingly to the fitting axis X Y and Z

## Suggested Solution
implement a solution described above that is only required to be used once, maybe with an (uncalibrated mag) and then snap to the closest 45deg (im not that good at linear algebra but i think it should be possible to calculate magnitude of changing vector and its phase)

## Who does this impact? Who is this for?
everyone using GPS

## Additional context
I fly a small craft with FC arrow facing to front, M8Q-5883 facing to back and thus the setup should be CW270FLIP as per manual but substract 180deg, so CW90FLIP? however it is sadly not the case

**Comment by RomanLut** [comment]
I would suggest making existing features to work properly rather than adding new ones.
Magnetomeneter alignment tool is fixed by https://github.com/iNavFlight/inav-configurator/pull/1799
This issue should be marked as feature request.
