### ISSUE TITLE
6.0 Mac Dmg Installs v 5.1?

### ISSUE THREAD

**Issue by peterbrady** [iNavFlight/inav-configurator#1748]
I downloaded the 6.0 release from the releases page: and received INAV-Configuration_macOS_6.0.0.dmg which has 132,946,219 bytes. After installing and running it reports that it is v5.1

**Comment by RobinatiNav** [comment]
I installed the same and it looks like this:

<img width="1280" alt="Snímka obrazovky 2023-03-29 o 19 28 23" src="https://user-images.githubusercontent.com/123115426/228619902-7f789e56-a770-41bc-8bf2-33d5565901d9.png">

**Comment by RobinatiNav** [comment]
> I installed the same and it looks like this:

Actually, it is not installing but drag and drop.
> 
> <img alt="Snímka obrazovky 2023-03-29 o 19 28 23" width="1280" src="https://user-images.githubusercontent.com/123115426/228619902-7f789e56-a770-41bc-8bf2-33d5565901d9.png">

**Comment by peterbrady** [comment]
Apologies. I did have a previous version, 5.1 installed. Not sure why the DMG installer did not overwrite for me, but it works after deleting the old version. Closing now.
