### ISSUE TITLE
"Control sticks" have mixed up Throttle and YAW.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav-configurator#175]
Left stick up and down moves YAW, while left stick right and left moves throttle.

![image](https://cloud.githubusercontent.com/assets/5670710/24334429/4931e97c-126a-11e7-83c4-90bf3cf82e25.png)

![image](https://cloud.githubusercontent.com/assets/5670710/24334430/524090fe-126a-11e7-8b63-6c2bc856e47c.png)

**Comment by digitalentity** [comment]
Change channel map to AERT1234

**Comment by oleost** [comment]
@digitalentity ?

**Comment by digitalentity** [comment]
Oh, I didn't realize that you are using configurator's native MSP_RX.
