### ISSUE TITLE
Dji head tracker functioning via iNav

### ISSUE THREAD

**Issue by happylandings** [iNavFlight/inav-configurator#1762]
Wanted feature.

I am wondering, would it be possible to use Dji Goggles 2 head tracker for controlling a gimbal in iNav? The head tracker data from Dji Goggles 2 could go through e.g. the O3 air unit to the flight controller and then it can be (I believe) manageable. What do you think, is it possible?

**Comment by DzikuVx** [comment]
of course it is possible
