### ISSUE TITLE
No PPM option found in INAV 6 configurator for operating Flysky FS-i6S with FS-IA10B receiver

### ISSUE THREAD

**Issue by Pratham340** [iNavFlight/inav-configurator#1769]
Connected PPM single wire to Mateksys F722-WING (RX2) worked just fine with Betaflight but when tried with INAV there was no option for PPM and just wasn't working. Any help from anybody would be highly appreciated! :)
![Screenshot 2023-04-28 143630](https://user-images.githubusercontent.com/71821987/235105733-f233ec6a-3091-404a-95ae-56057db781ab.png)
![Screenshot 2023-04-28 143608](https://user-images.githubusercontent.com/71821987/235105744-0e7e83a8-f0d0-4d1b-b0cc-96f5d229ed1b.png)

**Comment by stronnag** [comment]
By design. PPM was removed from the firmware some time ago.

**Comment by Pratham340** [comment]
Hi Stronnag,
I am new to this and I have started putting my hands into this recently.
Then how do people with FS-i6s or i6x or i6 use INAV for their multi-copters or fixed wings?

**Comment by stronnag** [comment]
One of:
* IBUS
* Use an older version of INAV
* Upgrade to more modern RX/TX

**Comment by Pratham340** [comment]
How do we use IBUS?

**Comment by Pratham340** [comment]
Thanks, I got it.
