### ISSUE TITLE
How do we use GSM SMS option in telemetry under ports tab?

### ISSUE THREAD

**Issue by Pratham340** [iNavFlight/inav-configurator#1772]
Hi guys,
How do we use the 'GSM SMS' option in the telemetry of ports tab in INAV? I have a 4G LTE GSM module with 3 pins RX, TX, and GND.
PLEASEEE Help me! :) Your help would be highly appreciated.
![Screenshot 2023-04-30 203220](https://user-images.githubusercontent.com/71821987/235360389-023ede10-546a-4d66-bed7-f4f2dda25b7e.png)

**Comment by stronnag** [comment]
Something wrong with the [INAV documentation](https://github.com/iNavFlight/inav/blob/master/docs/Telemetry.md#cellular-telemetry-via-text-messages) ?
