### ISSUE TITLE
Manual mode: airplane goes straight down

### ISSUE THREAD

**Issue by boomerschnecke** [iNavFlight/inav-configurator#1776]
Hello all,
once again the issue, that the airplane goes straight down with around 45 degree with manual mode
With other modes it flys. (more or less...)

BUT its pumping like hell if throttle is a higher speed. And Im flying a ZOHD Drift with 2s. Means there is not to much power anyhow.

Whats wrong?
WITHOUT the FC the airplaine flys great.
So there must be any effect by the FC
FC is Matec F405 TE with newest SW and INAV 6.1

**Comment by MrD-RC** [comment]
Do you have DVR of this happening? Can you also post screenshots of your mixer and outputs pages.

With manual, the PIDFF loop is completely bypassed. All that INAV does is take your inputs, add any specified expo and rates, applies any logic conditions, puts it through the mixer, then through the outputs.

**Comment by boomerschnecke** [comment]
Hi Darren, should I send some screenshots or the diff all file? If screenshots could I send this to you email account directly? Or should / can I upload this here directly?

**Comment by boomerschnecke** [comment]
![Mixer1](https://github.com/iNavFlight/inav-configurator/assets/122038465/b0f7c1a6-0fb5-4e9e-be4d-31fa014c3a55)
![Mixer2](https://github.com/iNavFlight/inav-configurator/assets/122038465/f56f9901-26ef-4990-9900-5257e8afc66b)
![modes1](https://github.com/iNavFlight/inav-configurator/assets/122038465/7588512c-08e2-4907-94d9-dbcccdb571b6)
![modes2](https://github.com/iNavFlight/inav-configurator/assets/122038465/85da428c-7c09-4210-b81d-f42fdab17520)
![modes3](https://github.com/iNavFlight/inav-configurator/assets/122038465/1d72b5a0-d0a8-4af5-aecd-da43d2b2a256)
![modes4](https://github.com/iNavFlight/inav-configurator/assets/122038465/bd33516c-8c17-4fc1-9f70-967df197f827)
![Modes5](https://github.com/iNavFlight/inav-configurator/assets/122038465/8d6f036b-4025-422f-a404-1647aae63840)
![outputs1](https://github.com/iNavFlight/inav-configurator/assets/122038465/bd3d0736-46dc-4e15-ae18-0f45b9b1ddb8)
![outputs2](https://github.com/iNavFlight/inav-configurator/assets/122038465/e0620387-d086-4ff2-adfd-b5402f2c49e3)
![Ports](https://github.com/iNavFlight/inav-configurator/assets/122038465/ca57eca7-b469-4a1c-839c-16e1b7e4846b)
![adTuning1](https://github.com/iNavFlight/inav-configurator/assets/122038465/b599692e-c105-4c52-afb3-a77187228162)
![adTuning2](https://github.com/iNavFlight/inav-configurator/assets/122038465/995b8c4f-3e50-4e95-860e-bee3f48a9b43)
![adTuning3](https://github.com/iNavFlight/inav-configurator/assets/122038465/74bfc2ff-d59a-4a68-91e5-8a6f44235911)
![Calibration](https://github.com/iNavFlight/inav-configurator/assets/122038465/b92e85ee-f4b5-41d4-9070-c2faac344315)
![configuration2](https://github.com/iNavFlight/inav-configurator/assets/122038465/76879574-55f2-4860-ab56-37a8f2eba8f3)
![configuration3](https://github.com/iNavFlight/inav-configurator/assets/122038465/3572de84-c48e-448f-b3ea-6eef9849cf0d)

**Comment by rsilk1949** [comment]
Is the plane balanced on the centre of gravity marks with the battery installed. This is critical in manual mode.

**Comment by MrD-RC** [comment]
I couldn't see anything in the screen shots. But it has to be a physical/mechanical issue. If manual has issues but the other modes (assuming Angle or Horizon) are flying ok. They are compensating for something in the setup.

As suggested, check CG. I'd also add make sure there is no trim on the transmitter. If you flew it without an FC before, maybe you still have some trim in there. I know this model only needs a little elevator throw. So with some setups, a little accidental trim on the transmitter could cause big problems.
