### ISSUE TITLE
inav-configurator 6.0 mixer page show error

### ISSUE THREAD

**Issue by rcdrones** [iNavFlight/inav-configurator#1777]
Thank you comunity make great fc SW.

today i find a minor bug:
![inav6bugshow](https://github.com/iNavFlight/inav-configurator/assets/10257343/0ff65ba6-7e7e-47d6-b6f9-f56b6bdce0c7)

thanks , Jian

**Comment by MrD-RC** [comment]
I don’t see a bug. The servos are where they should be.

**Comment by rcdrones** [comment]
S11 is board pin‘s name. 
Servo 9 should in S11 . (actually i use  OSC to confirm is info, S11 have right PWM wave)

-------------
But inav-configurator 6.0 show  Servo 9 in S7 is minor bug.

**Comment by MrD-RC** [comment]
That’s not how it works. You cannot specify pin output. The servo index, 9 in this case, only specifies the order of the servos. Not the output pin. INAV decides the output pin and displays it in the output mapping table. Servo 9 should be outputting to signal pin 7. 

What you see on screen is correct.
