### ISSUE TITLE
iNav 6.1 no baro on Matek F722SE

### ISSUE THREAD

**Issue by mrcottonmouth** [iNavFlight/inav-configurator#1781]
Just like the title says. I upgraded to 6.1 from 6.0 and the barometer says hardware error. Downgraded back to 6.0, no issues.

**Comment by Jetrell** [comment]
Did you work it out ?

I loaded 6.1 onto a MatekF722SE target (wing version). And the baro appears to work.

![baro](https://github.com/iNavFlight/inav-configurator/assets/47995726/0ae47161-46fb-4f74-b9fe-30785b903538)

**Comment by Jetrell** [comment]
Did you work it out ?

I loaded 6.1 onto a MatekF722SE target (wing version). And the baro appears to work.

![Untitled](https://github.com/iNavFlight/inav-configurator/assets/47995726/b54bcc32-4550-4669-9da2-74879d2bf2d0)

**Comment by mrcottonmouth** [comment]
I don't know why 6.1 didn't work for me. I flashed 6.0 and back to working

**Comment by mrcottonmouth** [comment]
This is the quad board
