### ISSUE TITLE
Inav 6.1 Display Error on Debian 11 & LXQt

### ISSUE THREAD

**Issue by jfruitet** [iNavFlight/inav-configurator#1785]
I have installed Google Chrome and INAV Configurator  6.1 on a emachines under  Debian 11 with LXQt as Desktop Environment.

INAV start but the upper and left menue frames are not  correctly displayed.

Is this a known issue ?

JF - Nantes - France
![INav-display-error](https://github.com/iNavFlight/inav-configurator/assets/1632466/7785da7c-a96a-4a3e-a5bb-c1a0d0448037)

**Comment by jfruitet** [comment]
![Inav_Dispaly_error](https://github.com/iNavFlight/inav-configurator/assets/1632466/61cf6ce0-31e6-4ebb-8af1-6266011c6e40)

**Comment by jfruitet** [comment]
This is a little better but the upper frame still errorness.

**Comment by stronnag** [comment]
This is a problem with your setup / hardware / video drivers.
The INAV-Configuator works perfectly on Debian Stable using any of Gnome, Xfce or LXQT desktops for me.

**Comment by jfruitet** [comment]
Thanx.
I'll look that stuff.

**Comment by jfruitet** [comment]
Have I to install node.js ?
See "https://github.com/iNavFlight/inav-configurator" 
Building and running INAV Configurator locally (for development or Linux users)

**Comment by jfruitet** [comment]
I think is the Graphic Card. To old... and to smal definition.
