### ISSUE TITLE
Blackbox space data incorrect show

### ISSUE THREAD

**Issue by knoppixmeister** [iNavFlight/inav-configurator#1788]
Blackbox onboard SD card free space incorrect show.
Less space is left on sd card then more legend title shifted to right out of the screen.

Affected versions: 7.0.0 (probably 6.1.0 and 6.1.0_fix too).

![Screenshot from 2023-06-10 19-03-12](https://github.com/iNavFlight/inav-configurator/assets/567882/a9e8db3f-7989-475f-a6db-5924ab61e91f)

-------------------------------------

Shoud be like this:
![INAV_conf_7 0 0_fixed_bb_spaces](https://github.com/iNavFlight/inav-configurator/assets/567882/ab18b5ca-758c-4b5b-bbcd-0a0fb54ecec4)

**Comment by DzikuVx** [comment]
INAV can utilize only 4GB of a SD card. It's not a bug but a well known limitation.
