### ISSUE TITLE
Create calibration tab file

### ISSUE THREAD

**Issue by cnHeider** [iNavFlight/inav-configurator#18]
Calibration tab, makes other tabs unusable until disconnect.
![2016-06-18-102339_1366x768_scrot](https://cloud.githubusercontent.com/assets/509350/16169887/3f33a158-353f-11e6-934b-6ce70684b77c.png)

**Comment by DzikuVx** [comment]
This tab is not working yet. Unfortunately we know

**Comment by DzikuVx** [comment]
"Calibration" tab progress should be part of #20

**Comment by skaman82** [comment]
@digitalentity Any progress on this? I can help create the GUI for this if I know how you like to implement the process.

**Comment by digitalentity** [comment]
@skaman82 Blank calibration page is part of #20 

I want to have 3 calibration options on this tab:
**1. Accelerometer calibration**
Here I'd like to have one button "Calibrate" and 6 pictures of UAV in different positions (like in the wiki). By default all of them would be grey. FC will tell the Configurator which position it is calibrating and Configurator should light that picture by some color when it's working and if it's successful it should change color to green.
Also I want to have 6 boxes to show or type in current calibration values for accelerometer - accelerometer zero and accelerometer gain.

**2. Level calibration**
The button "LEVEL CALIBRATION" will simply take current tilt angles and adjust board alignment in such way that angles are zeroed. Maybe duplicate pitch-roll board alignment values here as well.

**3. Compass calibration**
Just a button and 3 input boxes to show or type in Mag zero values.

TIA for your help!

**Comment by skaman82** [comment]
Will prepare the HTML/CSS for this in the next days

**Comment by skaman82** [comment]
@digitalentity my part is ready
<img width="1551" alt="bildschirmfoto 2017-01-11 um 19 51 28" src="https://cloud.githubusercontent.com/assets/11768024/21861996/af55f71a-d837-11e6-957f-6c6ea37a35d9.png">
