### ISSUE TITLE
Servo outputs shown incorrectly if servo number is skipped

### ISSUE THREAD

**Issue by jeffhendrix** [iNavFlight/inav-configurator#1805]
When a servo number is skipped, inav (the flight controller fw) will skip outputs, but configurator shows them as not skipped.
Please try this on the bench before closing as not an issue.
This is very easy to reproduce and will show the problem.
Create a simple 4 channel airplane.
![screen1](https://github.com/iNavFlight/inav-configurator/assets/7000366/cd4383b5-155c-4b4c-b9c8-88e5d30bb7aa)
Notice how Servo 1 is on S3 (on the FC), Servo 2 on S4, Servo 3 on S5 and Servo 4 on S6
Add a new mixer rule for servo 5 and notice that it will map it to S7 on the FC.
![screen2](https://github.com/iNavFlight/inav-configurator/assets/7000366/1baeac2d-81a7-4acb-8c94-b834705df7bb)
Plug a servo into S7 on your FC and verify that it moves when you move the channel.
Now change the servo number to 6 and notice that it shows servo 6 on output S7
![screen3](https://github.com/iNavFlight/inav-configurator/assets/7000366/390505ab-eb7c-4c72-bf02-eb3fd9b7a038)
But that channel from your radio will no longer control that servo (the one plugged into S7). 
You will have to move your servo to S8 to get that signal.

Here's another way to see the same problem.
Start with a 4 channel airplane and add 2 servos (Servo 5 and Servo 6). I mapped their outputs to RC channels 9 & 10
![screen4](https://github.com/iNavFlight/inav-configurator/assets/7000366/8031ba90-77ba-407f-a5c4-85e0e452e4e6)
Plug in servos to S7 and S8 and verify that those radio channels correctly move those servos.
Now delete servo 5
![screen5](https://github.com/iNavFlight/inav-configurator/assets/7000366/c8f90981-2da6-4504-a1e1-6083743528a8)
You will be left with Servo 6, but it will move to output S7 in configurator
![screen6](https://github.com/iNavFlight/inav-configurator/assets/7000366/4b31d10b-9e00-4b23-b3e8-b1426656b6a3)
But moving that channel (in my case RC 10), it will move the servo on S8 and nothing will move the servo plugged into S7.

Also, if you change the servo number to something that would map it to an output that's larger than what you have on the controller, that signal won't come out any of the output ports. I changed mine to 10 and none of the servos on my FC will move, even though inav configurator shows it as port S7
![screen7](https://github.com/iNavFlight/inav-configurator/assets/7000366/a87ee390-c2eb-4c62-b6e1-d4f863772bf7)

If you look in the inav code at the function writeServos(), you will see that it uses the servo number to map to an output. It starts with the lowest servo number and maps that to the 1st output, then counts from there. (if your 1st servo number is 4, that gets mapped to the 1st servo output). It then counts up from there. So if any servo numbers are skipped, those outputs are skipped.

**Comment by MrD-RC** [comment]
In that case. Something had changed in the firmware. As you used to be able to skip index numbers. But it would not skip the output. It would act the same way as seen on the output mapping table. At some point there must have been a change in the firmware, which was not reflected in the configurator.

**Comment by DzikuVx** [comment]
This is a known limitattion. Servos has to be defined sequencialy in order to firmware to correct assign outputs. And it's a firmawere nor configurator limitation. Thanks for reporting
