### ISSUE TITLE
TRICOPTER: motor diagram incorrect

### ISSUE THREAD

**Issue by samsab1** [iNavFlight/inav-configurator#1816]
hello Everybody
i try on inav6.1 to set my new F405 V3 speedybee on a tricopter
several problems in front of me.
first one is that all 3 moteurs are showing turning all in the same way CCW! it's just not correct.
second pb, is that i don't know how and where connect the servo driving the yaw action

best regards

**Comment by mmosca** [comment]
Can you post a picture of your mixer tab?

It should show what output was assigned for your servo.
