### ISSUE TITLE
Incorrect Output Mapping

### ISSUE THREAD

**Issue by shota3527** [iNavFlight/inav-configurator#1821]
@mmosca 
Thanks for the efforts on smarter pwm mapping. But on the latest master of firmware and configurator.
1. Servo is not displayed if platform type is multi-rotor/tri copter
![image](https://github.com/iNavFlight/inav-configurator/assets/38871576/d121f2c9-0f55-4d10-a8e7-b34694922af5)

1. Incorrect output mapping if servo index jumped. In actual mapping, servo index 2,3 is mapped to S2,S3.  servo3 should be on S3 in the GUI.
![image](https://github.com/iNavFlight/inav-configurator/assets/38871576/b64f0d5f-f930-468b-9e31-e6b5c04aaf93)
```
# resource
IO:
----------------------
...omitted
C06: SERVO1 OUT
C07: SERVO2 OUT
C08: SERVO3 OUT
...omitted
# smix
smix 0 1 2 100 0 -1
smix 1 3 0 100 0 -1

# mmix
```

How about using getMotorCount() and getServoCount() in the firmware to get the correct count as a solution?

**Comment by mmosca** [comment]
was this after save and reboot?

**Comment by mmosca** [comment]
And what target was it?

Was it on master?
I certainly have seen that bug in development, but though it was fixed.

**Comment by stronnag** [comment]
Same UI artefact (master of F/w and configurator).  Set in the CLI. MATEKF405.
![image](https://github.com/iNavFlight/inav-configurator/assets/158229/c03e1c23-7608-4b0a-bab1-f40584441e64)

**Comment by shota3527** [comment]
> And what target was it?
> 
> Was it on master? I certainly have seen that bug in development, but though it was fixed.

It is matekf405, but I have seen something similar on matekf405wte.
The reboot has no effect.

For Incorrect output mapping if servo index jumped, I think it existed a long time ago

**Comment by mmosca** [comment]
let me try to reproduce it here

**Comment by mmosca** [comment]
#1822 should fix this.
