### ISSUE TITLE
Update the Readme.md

### ISSUE THREAD

**Issue by CrypticRevenger** [iNavFlight/inav-configurator#1857]

**Comment by MrD-RC** [comment]
With what?!

**Comment by CrypticRevenger** [comment]
> With what?!

updated in correcting the grammar, verbs, articles , spellings, preposition ,pronoun.

**Comment by MrD-RC** [comment]
When you create an issue. You should really describe what you want changed. Just saying Update the Readme.md is meaningless on its own.

**Comment by CrypticRevenger** [comment]
> When you create an issue. You should really describe what you want changed. Just saying Update the Readme.md is meaningless on its own.

sorry for the inconvenience.

**Comment by MrD-RC** [comment]
No worries. If you're making the PRs yourself. There's no need to create an issue for them. Especially if they're just typos.
