### ISSUE TITLE
Mag declination setup vs inav_auto_mag_decl

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav-configurator#187]
On the Configuration tab we have "Magnetometer declination" to set up.
If I understand correctly it does nothing if inav_auto_mag_decl set to ON (default setting, which can't be changed in configurator).
Shouldn't we allow to set both parameters, or at lest provide some help tip to the user here?

**Comment by DzikuVx** [comment]
Auto mag declination  is ON on all platform. If required can be changed in CLI
