### ISSUE TITLE
Apply more suited maximum angles on fixed wing presets

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav-configurator#189]
Apply these settings on the fixed wing models we have:

max_angle_inclination_rll = 600
max_angle_inclination_pit = 450

If you tell me the two lines I can enter it in all the presets and do the PR.

**Comment by DzikuVx** [comment]
If I remember correctly, we do not have those values in MSP yet

**Comment by oleost** [comment]
Okey, added to the Wiki then at least.
