### ISSUE TITLE
"Enable control" button required for MSP Receiver type?

### ISSUE THREAD

**Issue by matt856** [iNavFlight/inav-configurator#1890]
I have been testing with 2 different FCs with the exact same results if someone could please assist me.

Firmware for FC 1: inav_6.1.0_SKYSTARSF405HD.hex
Firmware for FC 2: inav_6.1.0_KAKUTEH7V2.hex

Currently I have a 915 MHz telemetry radio connected to a UART on my FC which has MSP enabled. This is allowing me to connect INAV wirelessly to the FC via the telemetry radio connection. However my goal is to run a standalone Python program to control the drone. Therefore I have also enabled the MSP receiver type via the receiver tab. I have been attempting to then control (arm/disarm) the drone via the YAMSPy example file simpleUI.py (https://github.com/thecognifly/YAMSPy/blob/master/Examples/simpleUI.py). I am able to connect to the board using the Python UI and view the current RX channels, modes, flags, etc. _Note: The one change I have made from the default example file is to include the other aux channels, not just aux1 and aux2 as shown in the example._

The problem is that the failsafe mode is constantly enabled which is preventing arming. The only way I have been able to get out of the failsafe mode is by using the following steps:

1. Power ON the FC via battery so the drones telemetry radio connects to the ground radio.
2. Plug in the USB to the FC and connect in INAV. Red parachute icon showing indicating the failsafe mode is activated. 
3. Go to the receiver tab and it looks like the RX channels are in the failsafe state as if not receiver is connected. _This makes sense because the Python program has not been started yet so the RX channel commands have not been sent via MSP._
4. Run the Python UI program and wait for the connection. Python program should be sending the RX channels now. Upon the UI connection the "Mode" row indicates "Angle" and "Failsafe" modes are active. The UI also shows the RX channels are in the appropriate ranges.
5. Back in INAV on the receiver tab, the RX channels are now in the appropriate ranges as seen in the Python UI. Then in INAV, click the "control sticks" button to open the virtual joysticks popup window.
6. Press the "Enable controls" button in the virtual joysticks popup window. **FAILSAFE IS CLEARED!!!**
7. Now I can close the virtual joysticks popup window and the failsafe remains cleared. I can now use the Python UI to control the drone as expected (arm/disarm).
8. If the Python UI is closed, the RX channels in the INAV receiver tab go back to the failsafe state as if not receiver is connected and the red parachute icon shows back up indicating the failsafe mode is activated again.

My thoughts: Since I can close the the virtual joysticks popup window after pressing the "Enable controls" button, and the failsafe remains cleared, that should mean that the Python UI was sending the RX channels the whole time it was running. 

Question: When I press the "Enable controls" button what is happening? And is there a way I can clear this failsafe without needing to connect to INAV via the USB connection and press this "Enable controls" button so I can just plug in the drone and run the Python program?

Dump file for the Skystars FC attached. Please let me know if you need any additional information.

[INAV_6.1.0_cli_Failsafe_skystars_11-10-23.txt](https://github.com/iNavFlight/inav-configurator/files/13323623/INAV_6.1.0_cli_Failsafe_skystars_11-10-23.txt)

**Comment by RomanLut** [comment]
You have to send MSP_RC command with frequency at least 5Hz, otherwise Failsafe mode will be enabled due to "no RX".
