### ISSUE TITLE
7 Final release gives issues

### ISSUE THREAD

**Issue by 0crap** [iNavFlight/inav-configurator#1896]
~~- Battery profiles do not update when switching~~
~~- Settings validated checkmark stays red (even when known good diff all is applied)~~
- After full erase and flash it hangs after apply defaults for wing **- Still a bug in final release. -**

Tested with ~~INAV-Configurator_win64_7.0.0-RC2.zip~~ INAV-Configurator_win64_7.0.0.exe and Matek [H743-Wing V2](http://www.mateksys.com/?portfolio=h743-wing-v2)
None of these issues with Configurator 7 RC1.

**Comment by RoadyFPV** [comment]
same here it shows reboot ez tune tab is there. after u close configurator and connect again ez tab is not there. and settings validated is red. cli status show ez_filter_hz error

**Comment by RoadyFPV** [comment]
same in release version

**Comment by 0crap** [comment]
> same in release version
> 
> stuck in: Device - Saving default settings

Confirmed here as well.
That is just sloppy.
No reason not to do a RC3 for the Configurator to see if this was fixed.
Now it's still there in the final release. Nice...

**Comment by Yury-MonZon** [comment]
Same here on linux x64 7.0 version Matek F411WTE

**Comment by RoadyFPV** [comment]
its not a cosmetic error, after u click on x and start configurator again ez tab is missing

**Comment by RoadyFPV** [comment]
thanks for the clarification. in the rc version, ez tab was also displayed for airplane. i will check it again.
and the boot stuck on savig defaults?

**Comment by 0crap** [comment]
>.... and the boot stuck on saving defaults?

This is still a bug as mentioned in the opening post.
