### ISSUE TITLE
7.0 final, unable to initiate a freshly flashed FC

### ISSUE THREAD

**Issue by vevere** [iNavFlight/inav-configurator#1921]
Tested on:
- SpeedyBee F405 Wing
- AtomRC F405_NAVI

Step1: flash inav 7.0.0 with Full chip erase (no problem)
Step 2 : after reboot, select "Airplane with a tail" or "Airplane with out a tail" 

then the step of applying the defaults settings never ends:
![image](https://github.com/iNavFlight/inav-configurator/assets/26826853/e4c8e57c-bcf8-4c5b-96ff-f08ca329c5f5)

I can cancel this task with the top white cross but I'm not able to know is any default parameter is missing or not

I can reproduce the problem without flashing, juste hit "reset settings" on the Setup page and the problem is the same

**Comment by ChristopherBrusie** [comment]
I can confirm this same issue with the SoeedyBee F7 v2 target.

**Comment by eLEcTRiCZiTy** [comment]
This is similar to new issue described here: [inav-configurator/issues/2090](https://github.com/iNavFlight/inav-configurator/issues/2090)
