### ISSUE TITLE
[BUG] nw.js update breaks BLE

### ISSUE THREAD

**Issue by Scavanger** [iNavFlight/inav-configurator#1943]
The last nw.js update to 0.81 has broken the BLE functionality. 
Seems to be broken since nw.js 0.75.

See: 
https://github.com/nwjs/nw.js/issues/8160

**Comment by Jetrell** [comment]
@Scavanger And any user running Win7/8 will now loose compatibility as well.

**Comment by Scavanger** [comment]
@Jetrell 
Yes, but staying on the old version forever doesn't make sense in the long run and Electron doesn't support WIn 7/8 either.

**Comment by DzikuVx** [comment]
We have Electron now :)
