### ISSUE TITLE
SUGGESTION - Add button Access Blackbox

### ISSUE THREAD

**Issue by jonathanoeijoeng** [iNavFlight/inav-configurator#1947]
This is only suggestion.
It would help a lot especially for beginner like who want to access blackbox file in flash memory on FC.
I know we can just type msc in CLI but it took me sometime to find that command.
Maybe if we add box in blackbox tab so user can click it and automatically run msc, this can very helpful for many users

Regards,
Jonathan

**Comment by MrD-RC** [comment]
There is a button on the CLI page to access the blackbox. Currently it just says **MSC**. But I have proposed the following change.
![image](https://github.com/iNavFlight/inav-configurator/assets/17590174/a03ac84e-ea21-4486-b43f-89eeaaf335a4)
