### ISSUE TITLE
Show VTX power in mW on OSD

### ISSUE THREAD

**Issue by jonathanoeijoeng** [iNavFlight/inav-configurator#1953]
I would like to have VTX power in mW and not 1-4 on OSD so I can have R:5:800 and not R:5:4

Thank you

**Comment by b14ckyy** [comment]
INAV does not use VTX tables and there are no plans to do so. Therefore it will only show power levels but not mW. 

Also reading power level values from VTX is only supported in SmartAudio but even there only on a few VTX.
