### ISSUE TITLE
Mission Control in 7.1 RC1 Waypoint altitude calculation is wrong (Sea Level Reference)

### ISSUE THREAD

**Issue by jureopacak** [iNavFlight/inav-configurator#1987]
In Mission Control in 7.1 RC1 while using _Sea Level reference_ **Grd Dist (m)** is always default **Alt (cm)**. There is no recalculation while params are being changed.

Worst case scenario is when Sea Level reference is used and you try to change it, in that case validation error is shown.

![image](https://github.com/iNavFlight/inav-configurator/assets/7392703/aff73f37-d297-4402-8955-0cf602d084d0)

This works fine in 7.0.1.

![image](https://github.com/iNavFlight/inav-configurator/assets/7392703/7768f690-cbb6-4788-9d90-59924bd7b0c6)

**Comment by breadoven** [comment]
There was a bug which should have been fixed now by #1979.

**Comment by b14ckyy** [comment]
Tested in 7.1 final and seems to be fixed
