### ISSUE TITLE
F7 flashing

### ISSUE THREAD

**Issue by sambas** [iNavFlight/inav-configurator#199]
F7 flashing would need this patch:
https://github.com/betaflight/betaflight-configurator/commit/e4794221b95c8a682b790e8f23148984479f87aa

**Comment by DzikuVx** [comment]
@sambas I was able to flash F7 with INAV configurator without any problems

**Comment by sambas** [comment]
It's the 722 that has issues

**Comment by DzikuVx** [comment]
Implementation in place, @sambas test please
