### ISSUE TITLE
Release 7.1.0 blank screen "Schrodinger  bug"

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#1994]
## Overview

Like Schrödinger's cat, this bug is both alive and dead at the same time

 ## Description

Building the current (2024-03-12) release_7.1.0 branch, the following is observed:
 
* If run from the build directory the application runs correctly, e.g

```
gulp release --platform linux64
cd  apps/inav-configurator/linux64
./inav-configurator
```
or even
```
gulp release --platform win64
cd  apps/inav-configurator/win64
wine ./inav-configurator.exe
```
works just fine. However:

* Create an archive (`*.tar.gz` or `*.zip`), unpack the archive and run it, results in a somewhat blank display (Linux or Windows):

![Screenshot from 2024-03-12 15-58-27](https://github.com/iNavFlight/inav-configurator/assets/158229/cdc32882-7fa1-4690-88d8-40956b153206)

In fact, just copying the build output folder `apps/inav-configurator/linux64` to anywhere else on the file system (outside of the checked out build source) and running `inav-configurator` from there results in the great white window.

## Spoiler

```
$ git bisect good
21f0507ed4490da72ba22bfeaa12fbbd07974803 is the first bad commit
commit 21f0507ed4490da72ba22bfeaa12fbbd07974803
Author: Scavanger <andreas.kanzler@outlook.com>
Date:   Wed Mar 6 10:43:28 2024 -0300

    Add lost require

 tabs/mission_control.js | 2 ++
 1 file changed, 2 insertions(+)
```

**Comment by Scavanger** [comment]
Yes, that was me, XD

Damn nw.js.

I used a require, in nw.js it works with "npm start" and in the "out" folder, if you copy the app out nw.js can't resolve the node module and the white page appears.

Fix is on the way.
