### ISSUE TITLE
Failsafe Minimum Distance - unit unknown and misleading

### ISSUE THREAD

**Issue by slackista** [iNavFlight/inav-configurator#2017]
Configurator `7.1.0`

Text: `Failsafe Minimum Distance in centimeters`
Unit in field: `m`
Tooltip: `Metres`

Please describe in this issue what is the unit because it's safety-type configuration.
![meters_or_centimeters](https://github.com/iNavFlight/inav-configurator/assets/20584264/7d2237ee-2dfc-4f70-9c09-f51bae93b59a)

**Comment by MrD-RC** [comment]
I see metres and metres.

**Comment by MrD-RC** [comment]
Duplicate of #2019 1995
