### ISSUE TITLE
Missing Ser2TCP in MacOSX for SITL

### ISSUE THREAD

**Issue by mmosca** [iNavFlight/inav-configurator#2045]
This is a reminder and placeholder for me to build Ser2TCP for 8.0 release, if 
iNavFlight/inav#9365 and #1849 don't get merged.

**Comment by stronnag** [comment]
I'd just  merge https://github.com/iNavFlight/inav/pull/9365 and https://github.com/iNavFlight/inav-configurator/pull/1849 and bd done with it
* [#9365](https://github.com/iNavFlight/inav/pull/9365) works fine merged with latest FC master 
* The Electton configurator no longer works with separate  `ser2tcp` at least on Linux.

I really think https://github.com/iNavFlight/inav/pull/9365 and https://github.com/iNavFlight/inav-configurator/pull/1849 is the path of least effort for the future.
And it's one less dependency (`ser2tcp`) to maintain across multiple OS.
