### ISSUE TITLE
[Master] unable to enter cli tab with SITL

### ISSUE THREAD

**Issue by RomanLut** [iNavFlight/inav-configurator#2053]
Unable to enter cli with SITL.

Reproduction:
1. Start SITL
2. Connect to SITL
3. Switch to CLI tab
=> Interface resets to home screen.

Tested with current Master branch, sitl executable from configurator master and sitl executable built from inav master, windows.

**Comment by stronnag** [comment]
Same happens on Linux. This is not a SITL issue, as that works OK with the CLI outside of configurator.

**Comment by DzikuVx** [comment]
Fixed in #2054
