### ISSUE TITLE
Model type presets save and reboot not working

### ISSUE THREAD

**Issue by BigTradioman** [iNavFlight/inav-configurator#2093]
With 2 different F405  wing boards, Matekmand SpeedyBee  I have flashed the latest firmware then on connection to the configurator I have selected flying wing presets, clicked save and reboot, the window’s 11 pc then hangs. I have left it for up to 15 minutes but it does not save or reboot. I have to X out to return. No presets have been saved.

**Comment by sensei-hacker** [comment]
This was a known issue fixed in the latest Configurator.
