### ISSUE TITLE
EzTune - Response maximum

### ISSUE THREAD

**Issue by gvonder** [iNavFlight/inav-configurator#2095]
Hi, 
I try to tune an old 3s drone where i need high P gain. I like the new EzTune but it's not possible to go further than 200. Is it possible to change that ? 

![image](https://github.com/iNavFlight/inav-configurator/assets/84014577/c85a2b78-c945-42cf-a3d0-eab4f39098f2)

**Comment by DzikuVx** [comment]
EzTune is designed to work with majority of "standard" setups. If yours is so special it needs so high gains, you should use classic approach instead
