### ISSUE TITLE
Motor unresponsive after upgrade 6 to 7.1.2

### ISSUE THREAD

**Issue by flyinginger** [iNavFlight/inav-configurator#2107]
Reproduce:
flashing inav 7.1.2 and clean in configuration onto flywoo F745nano. All config ok but motor #2 won't move anymore
Expected
All motor work and move on to fine tuning
Fix , work around
Reinstall inav 6.1.1

**Comment by sensei-hacker** [comment]
Can we see a screenshot of your mixer, please?

**Comment by mmosca** [comment]
Stale issue.

**Comment by windelwilli** [comment]
Would be great if u would share the solution, got the same problem ;-)

**Comment by sensei-hacker** [comment]
> Would be great if u would share the solution, got the same problem ;-)

Can we see a screenshot of your mixer, please?

**Comment by windelwilli** [comment]
![Image](https://github.com/user-attachments/assets/e42b5c8f-2393-468d-9c50-1e8c33e97636)

**Comment by windelwilli** [comment]
![Image](https://github.com/user-attachments/assets/25b680d9-b080-4f23-a267-7e425f4accb6)

**Comment by windelwilli** [comment]
Why isn't the servo 3 green and why is there a warning on the Motor tab ?

**Comment by sensei-hacker** [comment]
You have the motor set to -100% throttle.  Negative.
You want the motor to rev up for braking, and the motor to stop to make the plane go?  That should probably be 1 not -1.

I see you have a rule for the third servo, and a rule for the fourth servo.  What happened to the first servo and the second?  You probably want servo #1 and servo #2 if you have only have two servos. You can't have a fourth servo without having a first and second. :)

**Comment by windelwilli** [comment]
![Image](https://github.com/user-attachments/assets/c6e87af1-3d9b-4110-83fe-0df54f8f84ab)

**Comment by windelwilli** [comment]
![Image](https://github.com/user-attachments/assets/de12184c-9e4f-409d-a590-226e0599362c)

**Comment by windelwilli** [comment]
Servo 1 and 2 didnt solve ist... 

And other combination look like this

**Comment by windelwilli** [comment]
![Image](https://github.com/user-attachments/assets/bcf269f8-9003-4c1d-9a6c-7a7e7ff82ec4)

**Comment by windelwilli** [comment]
![Image](https://github.com/user-attachments/assets/18b4d563-aeee-4f0e-8773-6ff0816f8031)

**Comment by windelwilli** [comment]
Is the green and red importand to work correctly ? Because if i choose 2 and 3 then physically it do wat it have to do... bitte then there isnt the green one like in the first picture

**Comment by sensei-hacker** [comment]
> Is the green and red importand to work correctly ? Because if i choose 2 and 3 then physically it do wat it have to do... bitte then there isnt the green one like in the first picture

Green and red is not important, if it does what it needs to do.

It looks like the numbering got a bit confused. To make the numbering and colors correct, it _MAY_  help to delete both servos, save and reboot, then add them again.

**Comment by windelwilli** [comment]
The reeboot and add the servos again hit it.... now everything is green and red and everything is okay.... have done..... thx
