### ISSUE TITLE
[MASTER] Advanced setting, OSD and Mission Control won't load, MSP error

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav-configurator#2110]
Not possible to load Advanced Settings, OSD and Mission Control tabs with current master connected to INAV current master firmware.

Throws up the following MSP error which I'm pretty sure is nothing to do with anything I've done. Also not sure when it became a problem exactly but must be a fairly recent issue:

![Screenshot (261)](https://github.com/iNavFlight/inav-configurator/assets/56191411/78197214-5bf5-4993-afce-47445a376df9)

**Comment by breadoven** [comment]
It happens every time on the tabs mentioned above for an F722 board configured as a multirotor. However, testing on an F411 board configured as a fixed wing it only happens on the OSD tab, although this is using a slightly out of date version of the current master.

**Comment by JulioCesarMatias** [comment]
This is also happening to me. I just reported this on the Dev Team.

**Comment by JulioCesarMatias** [comment]
I managed to reproduce the problem you described, but when clearing the configurator cache, everything worked normally.

![Captura de Tela 2024-06-15 às 11 20 21](https://github.com/iNavFlight/inav-configurator/assets/25625982/2b4316b7-98ae-441f-8f6b-3ba68b9dea5a)

**Comment by breadoven** [comment]
Ah well done that fixes it. Is that cache reset button a recent addition ?

Thanks !

**Comment by mmosca** [comment]
> Ah well done that fixes it. Is that cache reset button a recent addition ?
> 
> Thanks !
> 
> Can't help but think this is going to catch people out who won't know to click that button.

Yes. It is Pawel doing some magic to speed up the configurator. Shouldn't be a problem on release code, but changing back an forth between different branches or older snapshots of master can cause issues if you don't reset the cache

**Comment by stronnag** [comment]
It would be neat of the cache included the build id (commit hash) and if the cached build id didn't the current id, then automagically clear the cache. Would save a load of support issues for "nightly" builds.

**Comment by breadoven** [comment]
I added something to flush the cache on disconnect ... but maybe that somewhat defeats its usefulness.

**Comment by mmosca** [comment]
A better approach would probably be to fetch missing item on cache miss. []s,Marcelo Bezerra ***@***.***>On 15 Jun 2024, at 22:07, breadoven ***@***.***> wrote:﻿
I added something to flush the cache on disconnect ... but maybe that somewhat defeats its usefulness.

**Comment by rts18** [comment]
I attempted to run builds of both masters from yesterday.
These are the results.
The OSD, Outputs, Failsafe, Tuning, Advanced, MissionControl and GPS tabs hang.

![Output tab](https://github.com/iNavFlight/inav-configurator/assets/78670415/f93fe0c5-11b6-447a-9206-e7eef0471753)

And worse. The configuration tab does not load any sensors.
I set them to auto and saved. Nothing changed.
![Capture](https://github.com/iNavFlight/inav-configurator/assets/78670415/2eaac8a5-9ee5-443e-ad44-148bb58fd129)

The configurator was run on a computer with Windows 10 OS.

>However, testing on an F411 board configured as a fixed wing it only happens on the OSD tab.

I have noticed the same. Every FC target I tested worked differently. Some fail to load a few tabs. And others fail to load a dozen tabs. 
I attempted to clear the cache, with no change here.

**Comment by DzikuVx** [comment]
The issue may appear when setting descriptors changed. In general, once final release is out, there should be no problems as then settings will not change. For now, in case of any problems, flush the cache 
@breadoven cache flush on disconnect completely breaks the idea
@stronnag the idea of build id if probably the best.
