### ISSUE TITLE
Fixed wing, set failsafe_throttle_low_delay = 0

### ISSUE THREAD

**Issue by moggiex** [iNavFlight/inav-configurator#212]
Howdy,

Remove if this has already been completed.

For fixed wing models, can you set `failsafe_throttle_low_delay = 0` so that on long glides the model doesn't failsafe itself?

Matt

**Comment by oleost** [comment]
Hi.

Please have a look here: https://github.com/iNavFlight/inav/pull/1799

Cloosing this one as its an duplicate.

**Comment by moggiex** [comment]
Thanks @oleost !
