### ISSUE TITLE
Unit confusion in Failsafe help text

### ISSUE THREAD

**Issue by MrMap** [iNavFlight/inav-configurator#2132]
Some time ago I opened an issue #1995 regarding distance unit - now fixed and closed.
But now I found a residual piece of the unit confusion in the help text associated (hover over popup help text). It still mentions cm while it should now purely be meters, if i got this right.

![Failsafe unit mixup 2024-07-01 232213](https://github.com/iNavFlight/inav-configurator/assets/5843103/a6ce4066-07da-4697-8928-f0f0c60d892e)

**Comment by b14ckyy** [comment]
thats correct. Flagged to be fixed

**Comment by b14ckyy** [comment]
Nevermind. The option was removed from the GUI anyway. Closing
