### ISSUE TITLE
[INAV 8.0] Sensor status is not always updated

### ISSUE THREAD

**Issue by mmosca** [iNavFlight/inav-configurator#2150]
When connecting / disconnecting to a fc, the sensor status bar on top does not always update.

The GPS sensor or the magnetometer may not turn blue, for example.

**Comment by MrD-RC** [comment]
There seems to be a few issues with the states not being collected properly. I have also noticed that the failsafe parachute (https://github.com/iNavFlight/inav-configurator/issues/2232) and modes auto channel detect (https://github.com/iNavFlight/inav-configurator/issues/2233) no longer work too. I have a feeling that this is all related to the move to electron?

**Comment by 0crap** [comment]
Seen that as well with 8.0 RC1 on the Sensors tab, when monitoring the Barometer.
The green line is moving (Baro) but the blue line (Alt) is not.
Alt is stuck at zero.

Flashing target (MATEKF405) with 7.1.2 and using Configurator 7.1.2 shows the blue line (Alt) moving around as normal.

**Comment by MrD-RC** [comment]
I believe this is fixed in RC2.

**Comment by 0crap** [comment]
Awesome!

**Comment by 0crap** [comment]
> I believe this is fixed in RC2.

I tested 8.0 RC2 and the Baro Alt is not updating for me.

I started testing with the FC on 7.1.2 and at that point the Baro Alt is updating correctly on Configurator 8.0 RC2.
As soon as I update the FC to 8.0 RC2 it's not updating anymore.
So this makes me believe it could be a FC firmware issue?
Let me know if you want me to open a new GitHub issue on the FC part.

A minor Configurator improvement could be to set the default scale to 100 on the Gyro part.
For me the default value of 2000 shows a flatline, when set to 100 it looks much better.
(But maybe this is only an issue with the FC I'm using, which is a MATEKF405)

![8 0 RC2](https://github.com/user-attachments/assets/06657a33-5994-4029-9d08-ecb849966798)

**Comment by b14ckyy** [comment]
Different topic. Please open a new Issue ticket with your information. I think I have a similar issue but never checked the sensor page again. Will add to that.

**Comment by 0crap** [comment]
Will do!
(The Gyro Scale to 100 default remains a minor Configurator issue.)

**Comment by b14ckyy** [comment]
Oh btw it could be intended that the Alt is not updating when disarmed. The raw gyro altitude below is what actually matters i think.

**Comment by 0crap** [comment]
Done.
https://github.com/iNavFlight/inav/issues/10510

**Comment by 0crap** [comment]
> Oh btw it could be intended that the Alt is not updating when disarmed. The raw gyro altitude below is what actually matters i think.

It all works and updates fine with v7.1.2, also on the bench disarmed.
