### ISSUE TITLE
Stuck on "Saving default settings"

### ISSUE THREAD

**Issue by pranas** [iNavFlight/inav-configurator#2152]
I was using iNav Configurator 7.1.1 (on macOS 14.5) to flash MATEKF411TE with 7.1.2 (with full chip erase). On the first connect, I select "Airplane with a Tail" and the configurator gets stuck on "Saving default settings". I can re-flash or click "Reset settings" and the issue is there as well. I can close the message and continue configuration but how can I be sure that all default settings were applied fully?

<img width="898" alt="Screenshot 2024-07-20 at 09 54 45" src="https://github.com/user-attachments/assets/ec10d315-c024-4f69-9735-7d8a281c5fbd">

**Comment by pranas** [comment]
Reverting back to iNav Configurator 7.1.0 fixed the problem so it seams specific to 7.1.1.

**Comment by sensei-hacker** [comment]
Yeah that's a known issue with 7.1.1.
You can close it after 20 seconds, or use 7.1.0
