### ISSUE TITLE
Preset for 10" quad sets rate_accel_limit_roll_pitch to 400

### ISSUE THREAD

**Issue by marbalon** [iNavFlight/inav-configurator#216]
...and this make my quad unflyable ;-) Paweł please other presets...

**Comment by DzikuVx** [comment]
Niah, it's not a bug :)

**Comment by digitalentity** [comment]
@DzikuVx how come it's not a bug? 400 deg/s/s is slow as hell!

**Comment by DzikuVx** [comment]
@digitalentity it depends how you want to fly! All my big quads fly like that. But I do understand, that some users might not like it so we might change it

**Comment by digitalentity** [comment]
Let's make it a dab faster, and add a warning to description - so slow response with this preset won't come as a surprize to a user :smile:

**Comment by marbalon** [comment]
This is accel limit... response is terrible!

**Comment by DzikuVx** [comment]
Limits increased 4 times on bigger presets. I hope you will be happy :)

**Comment by digitalentity** [comment]
@DzikuVx thanks, should be better now
