### ISSUE TITLE
Ukrainian language for INAV version 7.1.1

### ISSUE THREAD

**Issue by AndrewKZV** [iNavFlight/inav-configurator#2160]
[messages.json](https://github.com/user-attachments/files/16519366/messages.json)
![image](https://github.com/user-attachments/assets/0d67dd75-e151-41e0-9229-a14c4bdd03c5)

**Comment by bfmvsa** [comment]
Hi, it looks like you should open a pull request. Are you familiar with these dev things? If so please do, if not let me know. I will help you.
