### ISSUE TITLE
Air unit O3, speedeybee F405 WING, INAV 7.1.2: Crosshairnd horizon sidebar in OSD not in middle of google2 screen

### ISSUE THREAD

**Issue by samsab1** [iNavFlight/inav-configurator#2170]
hello
MSP displayport on UART5, BF43COMP on OSD; impossible to get the cross air and horizon in the middle of the screen.
is there something to do?
best regards

**Comment by mmosca** [comment]
If your goggles are setup for hd, you should BFHDCOMP instead of BF43COMP.

**Comment by samsab1** [comment]
i tried that too. same result, not centered on google2

**Comment by samsab1** [comment]
The others paramesters are diplayed where it should be, except cross hair and horizon sidebar........

**Comment by samsab1** [comment]
why do you close this thread?; it 's not solved from my point of view.
