### ISSUE TITLE
MATEK H743 WING V1 : ACCELEROMETER ICM 20602 NOT OFFERED

### ISSUE THREAD

**Issue by samsab1** [iNavFlight/inav-configurator#2220]
### Discussed in https://github.com/iNavFlight/inav-configurator/discussions/2219

<div type='discussions-op-text'>

<sup>Originally posted by **samsab1** October 26, 2024</sup>
hello, i try to convert this FC to INAV 7.1.2 but it doesn't work: the list of accelerometer does'nt match what it is required: i mean ICM20602. when running betaflight this FC works, but uses ICM20602
![2024-10-26_07h42_08](https://github.com/user-attachments/assets/1c14439a-2807-4d27-a8f5-4c16fbddd2bf)

how can use this FC with INAV? Is it possible to get a firmware for that FC for last INAV?
best regards from France
</div>

**Comment by mmosca** [comment]
ICM20602 uses the MPU6500 driver in INAV.

Set you gyro to auto and let inav auto detect it.

Otherwise, post a picture of your fc.

**Comment by samsab1** [comment]
![IMG_20241027_121856 1](https://github.com/user-attachments/assets/08071c31-db2a-4593-9aed-106cf316f96f)
Setting gyro to auto does not give any result

**Comment by samsab1** [comment]
![IMG_20241027_121841 1](https://github.com/user-attachments/assets/de9e4233-387a-41ac-bbe0-01bce43566bb)

**Comment by mmosca** [comment]
@mateksys any idea what is going on here?
