### ISSUE TITLE
7.1.2 Plane cruise mode issue with changing altitude

### ISSUE THREAD

**Issue by jaroszmm** [iNavFlight/inav-configurator#2221]
I asked around and it seems this is not my issue only.

Long story short:
IF plane is in cruise mode it randomly reacts to elevator input from radio. If I want to climb I pull the stick and plane goes up normally as it is supposed to.

BUT
If I push the stick down weird things happen. Sometimes it won't dive at all despite pushing the stick fully. Sometimes it takes like 10 seconds to react and dive, and sometimes it does it instantly.

What is worse this can change midflight. So one time I push the stick and plane stays level, other time, during the same flight, plane goes down as it is supposed to.

I already noticed that on two of my planes with 7.1.2, but also I know of at least two people having the same issue. One of them even couldn't climb and only change heading in cruise mode.

If I switch in flight to angle/acro/rth then I can control altitude and pitch normally. This happens only in cruise mode.

Any ideas?

**Comment by b14ckyy** [comment]
Resubmitted in correct repo: https://github.com/iNavFlight/inav/issues/10435
