### ISSUE TITLE
Parachute does not turn red in failsafe

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#2232]
Current master [8.0] The parachute does not turn red when you disconnect the transmitter. News of the disconnect it making it to configurator. As the arming flags show an issue with the RX link. But the parachute does not respond.

**Comment by MrD-RC** [comment]
The flight controller is in failsafe, only the parachute is not lighting. Potentially this is an issue with the periodic updates? If you use the programming framework and make a simple ` Equals | Flight Mode - Failsafe | Value - 1` line. You can see the active status light up blue. So failsafe is active.

**Comment by b14ckyy** [comment]
fixed
