### ISSUE TITLE
Demo mode gives 'callback is not a function' error when connecting

### ISSUE THREAD

**Issue by chasdabigone** [iNavFlight/inav-configurator#2236]
```
Running: - OS: Linux, Chrome: 120.0.6099.216, Configurator: 8.0.0
```

When I select "Demo mode" from the drop-down menu and click "Connect" the log says
```
Unexpected error: callback is not a function
Disconnecting...
```

**Comment by MrD-RC** [comment]
Demo mode does not work in master. It will only work in releases. This is known.

**Comment by stronnag** [comment]
> Demo mode does not work in master. It will only work in releases. This is known.

Out of interest why?
I have master installed; I have a SITL executable. It fails before it gets to run it.

**Comment by stronnag** [comment]
In fact if you just comment out the (*seems to JS neophyte*) "bogus" callback line, then it just works.
Possibly yet  another artefact of the Electron migration.

**Comment by chasdabigone** [comment]
What is the best way to test changes i made to configurator without
plugging in a FC in master?

**Comment by stronnag** [comment]
> What is the best way to test changes i made to configurator without plugging in a FC in master?

SITL

**Comment by 2A42** [comment]
> In fact if you just comment out the (_seems to this JS neophyte_) "bogus" callback line, then it just works. Possibly yet another artefact of the Electron migration.

hey, please, could you point the location of this callback line?
