### ISSUE TITLE
8.0 RC1 MacOS ARM build reports as damaged

### ISSUE THREAD

**Issue by jlpoltrack** [iNavFlight/inav-configurator#2245]
The 8.0 RC1 build for ARM 'INAV-Configurator_darwin_arm64_8.0.0.dmg' reports as damaged when trying to open (running M4 Mini).  The x86 version works fine.

![image](https://github.com/user-attachments/assets/d0afae32-95c6-42ca-9e3a-48f2bd164e34)

**Comment by mmosca** [comment]
I will add a note to the release notes.

We currently don't have access to an Apple Developer account to sign the binaries.

Running: 
```xattr -cr /path/to/your/INAV Configurator.app```

Should fix it.

**Comment by jlpoltrack** [comment]
Brilliant - this worked.

**Comment by jlpoltrack** [comment]
Brilliant - this worked.  Will close.
