### ISSUE TITLE
8.0-RC1 Storing Geozones causes all free number fields to be read-only until restart

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/inav-configurator#2251]
## Reproduce

- Connect Configurator to FC
- Open Mission Control
- Create any Geozone if none present yet
- Click on Store to FC and wait for reboot
- Wait for reconnect
Result: No text field can be directly edited like Altitudes, Distances etc. 

Reconnect of FC does not fix
As a workaround, Configurator needs to be restarted entirely. 
Normal Save and Reboot from other pages are not trigger the issue as far as I can tell. 

Replicated in RC1 and Nightly inav-configurator-dev-20241117-65

Demo: https://youtu.be/hoj7qgpSJNk

**Comment by stronnag** [comment]
Does not happen here. After reboot, text fields are editable ... at least with the SITL as FC. Let me try a real one.

**Comment by b14ckyy** [comment]
I can replicate on 2 FCs and also got the same report from 2 users. 
Are you on Windows or linux? Maybe only windows affected?

**Comment by stronnag** [comment]
Linux. 
However, this looks strange ...
![image](https://github.com/user-attachments/assets/d75d82d4-1d26-480e-b692-8b5e513e8f56)

**Comment by stronnag** [comment]
There is no problem on Linux with editing fields after reboot with "real" FCs, so maybe it's a Windows issue.

**Comment by b14ckyy** [comment]
Yeah I think there is a confusion between ASL reference and Launch Alt reference for the validity check. 
![image](https://github.com/user-attachments/assets/4bb3e0a5-68d9-43bd-b71c-eabcc22e6818)

@Scavanger

**Comment by Scavanger** [comment]
Fix for sanity check: https://github.com/iNavFlight/inav-configurator/pull/2252

The bug that the fields (affects ALL(!) input fields even in other tabs!) are inactive after saving is strange, and as @stronnag said, only occurs under windows. I can't find a bug in the code. I haven't changed anything in the code and I guess it worked before. 
Apparently the input fields lose their focus. 
Workaround: Deactivate the Configurator window briefly (minimise, activate another window, etc.) then everything works again.

**Comment by b14ckyy** [comment]
Fixed in https://github.com/iNavFlight/inav-configurator/pull/2252
