### ISSUE TITLE
MacOS Github Actions broken

### ISSUE THREAD

**Issue by Scavanger** [iNavFlight/inav-configurator#2254]
It's a matter of luck if the GH Actions for MacOsX work. 

But I don't see any pattern at all:
Mostly the ARM build fails, but sometimes also the x86 build, sometimes it is `npm install` with `closure-util EEXIST`, then again `permission denied` during build.
This is completely without logic.

**Comment by mmosca** [comment]
It is intermitent, but certainly happens more often with macos.

**Comment by b14ckyy** [comment]
Haven't seen a failed Mac build so far. Guess we can close.
