### ISSUE TITLE
Total mess in configirator on small screens

### ISSUE THREAD

**Issue by and-sh** [iNavFlight/inav-configurator#2265]
1024x768 resolution, Debian. Gnome, cannot reach save button, can not reach CLI.
Large font (accessibility) lead to worst results.
![Screenshot From 2024-11-26 19-00-06](https://github.com/user-attachments/assets/cd6d2b24-8c66-4b49-81dd-5107435ca405)

**Comment by and-sh** [comment]
I found some solution. If I press Tab several times it switch  focus to buttons and they become partially visible. same with cli.

btw Linux is becoming noticeably more convenient than Windows. For example, I use different desktops for different tasks, which allows me to switch between them quite quickly.
![Screenshot From 2024-11-26 20-55-12](https://github.com/user-attachments/assets/71a07c3b-0aae-41d9-a704-c7bf384bf8f6)

**Comment by MrD-RC** [comment]
I believe this has been fixed in 8.0.

**Comment by and-sh** [comment]
This is 8

I guess that some minor parameters of window are incorrect. All content are in places. I can switch between them by Tab. I can not scroll by sliders only.

Found a new solution. Just stretch the window a little.
![Screenshot From 2024-11-27 07-30-01](https://github.com/user-attachments/assets/1d760537-dbb4-4d96-bc82-df76df437346)
![Screenshot From 2024-11-27 07-30-49](https://github.com/user-attachments/assets/d3220b1b-4ef2-4475-ba5c-83871d2dc5f9)

**Comment by MrD-RC** [comment]
With a resolution that size, you should run Configurator maximised.

**Comment by MrD-RC** [comment]
@and-sh Could you try using this configurator https://github.com/iNavFlight/inav-configurator/actions/runs/12065115088?pr=2266

**Comment by and-sh** [comment]
On Debian, Gnome work fine, thank you very much
![Screenshot From 2024-11-29 11-28-16](https://github.com/user-attachments/assets/9d42fc11-1de8-4b34-956a-2b9306ac58d9)
