### ISSUE TITLE
MSC button working from CLI but not from Blackbox tab

### ISSUE THREAD

**Issue by jaroszmm** [iNavFlight/inav-configurator#2292]
As in the title. 
I have my SD Card in the FC (SB405Wing mini).
INAV 8 RC3 and latest configurator.
If I want to download logs using USB-cable from the FC I click MSC button in the blackbox tab but nothing happens despite multiple clicking on the button.
But if I go to CLI and click MSC button there, INAV Configurator immediatelly says "rebooting" and I get access from Windows Explorer to the SD card.

https://github.com/user-attachments/assets/62d5eb17-c543-4a10-ba12-bf2c655146a9

**Comment by MrD-RC** [comment]
Fixed in 8.0
