### ISSUE TITLE
NW-builder

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#230]
Prepare (nw-builder)[https://github.com/nwjs-community/nw-builder] configuration

1. Add `nw-builder` as dependency
1. Exclude `node_modules` folder from NW packaging completely
1. Package only build `*.css` and `*.js` files, do not package source files
1. Exclude `*.png` from `resources/osd/` folder

@fiam do you want to handle this?

**Comment by fiam** [comment]
@DzikuVx Assign it to me, please.

**Comment by DzikuVx** [comment]
have fun :)
