### ISSUE TITLE
firmware load buttons do nothing

### ISSUE THREAD

**Issue by KtotheG** [iNavFlight/inav-configurator#241]
i was using 1.7.2 configurator and the load firmware buttons do nothing. upgraded to the newest version and they are still dead. i downloaded the newest .hex for omnibus f4pro and cant even install from a local file.

**Comment by fiam** [comment]
@KtotheG Can you bring up the inspector and check if the console has printed any error messages?

**Comment by DzikuVx** [comment]
Confirmed working with latest release
