### ISSUE TITLE
Calibrate magnetometer button greyed out

### ISSUE THREAD

**Issue by mmoore112** [iNavFlight/inav-configurator#245]
I have the Omnibus F4 V3. Holybro Ublox NEO-M8N GPS Module with HMC5883L digital compass. the Holybro does turn green and start to flash the blue led(?) after start time on the unit. When i enable the Mag to this unit INAV causes the ready light on the Omnibus FC to flash rapidly. I assume this is because the compass has not been calibrated. IF i turn off the MAG the flashing stops. Anyway i do not  know if this is a Hardware problem or INAV. So, Can not fly. NO Calibrate Compass button.

Please advise

Thanks

**Comment by digitalentity** [comment]
Was anybody able to reproduce this issue with latest Configurator?
