### ISSUE TITLE
Require the configurator version to be >= than the INAV version

### ISSUE THREAD

**Issue by fiam** [iNavFlight/inav-configurator#278]
Due to the significant changes we've been introducing in the format of several messages when introducing new features, I think we should add a mechanism to check that the configurator version is greater or equal than the INAV version being configured. Otherwise we're risking corrupting some settings or not setting them at all.

For example, configurator 1.7.3 will happily manipulate the feature bits to set the RX in 1.7.4 (rather than using the receiver configurator message) and it will incorrectly tell the user the settings have been saved.

Best way to future proof this is to fallback to CLI when configurator version < INAV version. Additionally, we could show a banner at the top or the CLI with the link to the configurator releases page.

**Comment by Linjieqiang** [comment]
That sounds great..

**Comment by DzikuVx** [comment]
done in #757
