### ISSUE TITLE
flip-32-f4-omnibus-nano 

### ISSUE THREAD

**Issue by juanquy** [iNavFlight/inav-configurator#283]
Hi:
After flashing latest iNav firmware baro and GPS are in RED
Barometer BMP280
SPI Sensor MPU6000

Switch back to BetaFlight 3.2 and GPS is working fine but No baro is detected.
Any Help how I can get iNAv working with this board? with baro .

**Comment by fiam** [comment]
@juanquy Does it stay red if you just save and reboot?

**Comment by juanquy** [comment]
Both are Red all the time , in Betaflight GPS is fine , baro is now not
detected, it was detected before I flash BF 3.2.

**Comment by juanquy** [comment]
Nobody ?

**Comment by digitalentity** [comment]
Wrong issue tracker. This issue is firmware-related, not configurator related. Please re-open in https://github.com/iNavFlight/inav/issues
