### ISSUE TITLE
1.8-RC1 - Various presets cannot be saved

### ISSUE THREAD

**Issue by Target0815** [iNavFlight/inav-configurator#284]
All FW presets (Airplane General, 600mm Flying Wing, Flying wing Z84) cannot be saved (Confirm / Save and Reboot do nothing).

No problem with the default or the copter presets.

**Comment by fiam** [comment]
@Target0815 Could you let us know the FC you're using?

**Comment by fiam** [comment]
@Target0815 Managed to reproduce it. It's definitely a configurator issue and happens only under Chrome, not under NW.js. Working on a fix right now.

**Comment by Target0815** [comment]
SP Racing F4 Evo. Yes, with Chrome App.

**Comment by fiam** [comment]
@Target0815 I've just submitted a PR which fixes the problem and a new configurator release will follow in the coming days. Thanks for reporting this issue!
