### ISSUE TITLE
1.8.0 not able to set Receiver Mode of 1.7.3 target AIR3 ; backward compatibility issue

### ISSUE THREAD

**Issue by AlouetteIII** [iNavFlight/inav-configurator#287]
If i use 1.8.0 to change the receiver mode of a board coded 1.7.3 ; for example to Multiwire - on reboot it shows "no receiver" ; or other settings,  similar - whatever is chosen / saved - after beboot is corrupted to another    = bug

if i use 1.7.3 to change the receiver mode of a board coded 1.7.3 ; for example to Multiwire - on reboot it shows multiwire - correctly saving and showing the new mode.

**Comment by digitalentity** [comment]
@AlouetteIII please make sure you are using latest Configurator (1.8.0). We've changed the receiver code considerably, you need to use latest Configurator to be able to configure it.

**Comment by fiam** [comment]
I can reproduce this one. The configurator actually sets `feature RX_PPM`, but doesn't recognise it properly. Working on a fix.

**Comment by digitalentity** [comment]
Thanks @fiam
