### ISSUE TITLE
Board axis display option on OSD

### ISSUE THREAD

**Issue by Hyprmtr** [iNavFlight/inav-configurator#297]
I'd like to suggest an option for board axis display in degrees on the OSD. This would help a lot when trying to level or trim the board for level flight. If this is currently possible option, please advise and disregard this suggestion. Thank you.

P.S.: Also, Is Map mode possible with this OSD configurator? I use Map mode on my MWOSD R1.6 planes. It is a very nice radar type option. 

Ken

**Comment by shellixyz** [comment]
This is possible now, closing
