### ISSUE TITLE
nw.dll / trojan / stand alone configurator

### ISSUE THREAD

**Issue by Schalonsus** [iNavFlight/inav-configurator#301]
nw.dll in 1.7.3 package is identified as virus/trojan from Windows 10 antivirus

**Comment by DzikuVx** [comment]
I've installed 1.8.1 few days ago on Win10 and it worked fine. I suppose we can close it

**Comment by nathanjel** [comment]
Please reopen.
This just occurred in 2.2.0 in Windows 10. Very annoying...

**Comment by Target0815** [comment]
I can confirm that ... Win10 complains about the nw.dll of the configurator 2.2.0 (SoftwareBundler:Win32/Prepscram)
