### ISSUE TITLE
Mid level not persisting

### ISSUE THREAD

**Issue by slicc** [iNavFlight/inav-configurator#309]
In the configuration tab, I when I change the receiver mid level from the default of 1500 to 1520 and then click save and reboot, the value does not persist, but reverts back to 1500.

I am using an omnibus F4 V5 and the latest iNAV. My receiver is an fs-x6b with fs-i6b transmitter,

**Comment by shellixyz** [comment]
I can't reproduce the issue but the MSP protocol on the firmware side limits `midrc` between 1401 and 1599.

**Comment by digitalentity** [comment]
Fixed #372

**Comment by shellixyz** [comment]
There is another issue but I'm making a PR for it.
