### ISSUE TITLE
Multishot disable my magnetometre

### ISSUE THREAD

**Issue by bop4hell** [iNavFlight/inav-configurator#325]
Hi everyone !

I have a issue that I can't find anywere else.
When I use multishot as ESC protocole my Magnetometre get disconfigured " AUTO => HMC5883" when my FC reboot, ant it's the same with the CMD ligne.

I have reflash full erase my FC to be shure but no change. 

Gear :

Omnibus F3
ESC DYS XS30
GPS uBlox Neo-M8N

**Comment by DzikuVx** [comment]
This is not a bug, AUTO gets always replaced with specific hardware after that hardware has been identified
