### ISSUE TITLE
No Dataflash Chip Found - Matek F405 Mini FC

### ISSUE THREAD

**Issue by toddkurtz** [iNavFlight/inav-configurator#327]
Hi, I've entered set blackbox_device = SPIFLASH in CLI and tried enabling/disabling Blackbox in config tab but I continue to get the "no dataflash chip found" error in the top corner of the configurator. I isn't saving BB data either. Can you take a look or provide suggestions?

Thank you!!!

Todd

**Comment by DzikuVx** [comment]
this is firmware, not configurator issue. Please report it in https://github.com/iNavFlight/inav
