### ISSUE TITLE
Position hold not visible in configurator

### ISSUE THREAD

**Issue by bazyl78** [iNavFlight/inav-configurator#33]
After flashing Naze32 with latest release of inav I don's see at all any navigation flight modes in configurator. Are there any limitations for Naze 32 or I can assign modes only via CLI? I was using Inav configurator and not a Cleanflight one.

**Comment by digitalentity** [comment]
Do your have GPS and compass connected and detected by flight controller?
INAV won't show any navigation modes if you don't have all required sensors
available.

**Comment by bazyl78** [comment]
Ok. I thought it will be visible but not activ without gps. Will connect and try.

**Comment by davidgermany** [comment]
had the same issue.
On some drones you need to plug in the battery for the GPS to work.
Just USB doesn't always power the GPS, and when it is not powered, option will not show in INAV.
