### ISSUE TITLE
feature request: satellite view for GPS map

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav-configurator#336]
Can we get satellite view setup in the openStreetMap interactive map in the GPS tab?

**Comment by DzikuVx** [comment]
Yes and no. The legal maps we can use (OpenStreetMap) has no satellite view. Other map providers does not allow for GPS tracking purposes. This is quite complicated from the legal point of view. 
I keep that in mind and probably I have a solution, but that will have to wait a little

**Comment by wx4cb** [comment]
maybe you can add an option to allow for a google maps api key/code pair? that way that puts the legal responsibilities on the user and not the devs?

**Comment by DzikuVx** [comment]
yes, this is more less the idea

**Comment by DzikuVx** [comment]
done in #595
