### ISSUE TITLE
Drop PID scaling

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#34]
Drop PID scaling in configurator, use CLI values where possible

**Comment by DzikuVx** [comment]
@digitalentity any thought here?

**Comment by theArchLadder** [comment]
I agree with this, having different scaling in the GUI and CLI is just confusing on unit-less values.

**Comment by digitalentity** [comment]
I agree. No need to scale anything, just use same values as in CLI to avoid confusion.

**Comment by Ralf-W** [comment]
BTW "set roll_rate =20" is displayed as 200 deg/s in configurator. Please change GUI to 20 deg/s or add a decimal Point 20.0 deg/s.

**Comment by digitalentity** [comment]
@Ralf-W FYI CLI displayes rate values in 10*deg/s, so `roll_rate=20` **is** 200 deg/s. It's also documented in wiki - https://github.com/iNavFlight/inav/wiki/Rate-conversion-for-INAV-1.2

**Comment by Ralf-W** [comment]
@digitalentity 
Uups. Sorry, my fault.
