### ISSUE TITLE
1.9.1 Manual Mode Not Present

### ISSUE THREAD

**Issue by BigTradioman** [iNavFlight/inav-configurator#356]
Latest download of 1.9.1 does not have the Manual mode tab as promised. The Expo graphs are not working and it is not clear what the graduations are in comparison to the tx settings. Improvements to OSD not obvious so exactly what has been changed?

**Comment by digitalentity** [comment]
Configurator 1.9.1 + firmware 1.9
Manual mode is present:
![image](https://user-images.githubusercontent.com/11059099/36475187-a6e41492-1745-11e8-9e31-fd92324e8768.png)

Expo graphs are working:
![image](https://user-images.githubusercontent.com/11059099/36475227-bb52660e-1745-11e8-8819-6b66f5430af5.png)

Expo is always in arbitrary units. In case of INAV - in fractions of 1. OSD improvements are not related to Configurator. @BigTradioman make sure you upgraded you **firmware** as well.

Looks much like a bogus issue to me. Closing.
