### ISSUE TITLE
Show navPos[2] value 

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav-configurator#360]
Could be neat is we can display the navPos[2] value in meters inside the brackets so it can be directly compared with baro. 
![image](https://user-images.githubusercontent.com/20860004/36639144-193f1380-1a06-11e8-9648-ce1dc001a462.png)

**Comment by DzikuVx** [comment]
@giacomo892 wrong project man :)

**Comment by giacomo892** [comment]
@DzikuVx hahahahah I'm deeply sorry man LOL I opened the issue 15m after I left the bed. Should I close and open there?

**Comment by DzikuVx** [comment]
Yes please

Paweł Spychalski

Od: giacomo892
Wysłano: niedziela, 25 lutego 2018 20:08
Do: iNavFlight/inav-configurator
DW: Paweł Spychalski; Mention
Temat: Re: [iNavFlight/inav-configurator] Show navPos[2] value (#360)

@DzikuVx hahahahah I'm deeply sorry man LOL I opened the issue 15m after I left the bed. Should I close and open there?

**Comment by giacomo892** [comment]
Done. Closing.
