### ISSUE TITLE
1.9.1 mission editor creates erroneous position on WP save (47bf5bb7a99389e3539da6feacf778fbe111f274)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#370]
Using commit 47bf5bb7a99389e3539da6feacf778fbe111f274 (#367), has introduced following problem:

* Restore a mission from eeprom 
* Select a WP (WP2 in the 1st image)
* Add a speed
* Click save

The unexpected result is that the position of the affected WP has lat and lon reversed (2nd, 3rd image)

Presumably an accidental side-effect of the previous lon-lat label fix.

![screenshot-20180302205918-1108x761](https://user-images.githubusercontent.com/158229/36921740-56f693b4-1e5d-11e8-91ba-ef8c62d8f9fa.png)

![screenshot-20180302205948-1106x751](https://user-images.githubusercontent.com/158229/36921753-5fe2d596-1e5d-11e8-924f-ab9579e3f061.png)

![image](https://user-images.githubusercontent.com/158229/36921841-b9f87ba8-1e5d-11e8-9d33-b18d7fece085.png)

**Comment by shellixyz** [comment]
#367 or https://github.com/iNavFlight/inav-configurator/commit/47bf5bb7a99389e3539da6feacf778fbe111f274 are not the issue. It is present since 6cd87dbd. Fixed now.
