### ISSUE TITLE
Configurator 1.9.2.1 MAC

### ISSUE THREAD

**Issue by HB9DOD** [iNavFlight/inav-configurator#376]
This version do not open , it will not run on an IMAC Version 10.13.3
It stops with a "NWJS" See Picture

Thanks

Tom
![screen shot 2018-03-06 at 09 52 59](https://user-images.githubusercontent.com/37102817/37022750-38567176-2124-11e8-81b2-6cd8b472ca82.png)

**Comment by digitalentity** [comment]
Thanks for reporting. Binary updated, please try downloading again.

**Comment by HB9DOD** [comment]
Works with the 1.9.2.2. Version, Thanks for the fast reply
Tom
