### ISSUE TITLE
Window is too small for Macbook Pro unless maximized

### ISSUE THREAD

**Issue by dbasch** [iNavFlight/inav-configurator#377]
On a Macbook Pro 13 I cannot access the bottom tabs (e.g. CLI) unless I maximize the screen. This would probably be fixed if the window were movable / resizable vertically.

**Comment by Tygrys-1** [comment]
Same problem on Chuwi 13" windows tablet. The resolution is 3000x2000 points, font scaling is 250%

**Comment by rsilk1949** [comment]
Same problem on 13" HP laptop with default resolution of 1366 x 768.

**Comment by ewingate** [comment]
Same issue with Lenovo X220 running Ubuntu (1366x768).

**Comment by DzikuVx** [comment]
Min resolution was lowered in 2.5
