### ISSUE TITLE
Smartport Telem not working

### ISSUE THREAD

**Issue by Ernie34** [iNavFlight/inav-configurator#378]
I've been unable to get smartport telem to work at all with the inav firmware. I've tried it on physical UARTS as well as soft serials. If I flash betaflight to the board and set it up the same way it works fine on both soft serial and physical uarts.

**Comment by shellixyz** [comment]
Please post a config dump.

This is not related to the configurator but the firmware please close this one and reopen here: https://github.com/iNavFlight/inav/issues/new
