### ISSUE TITLE
Unable to select cusom channel map

### ISSUE THREAD

**Issue by elektrofreakz** [iNavFlight/inav-configurator#380]
Having a small problem here.
The standard channel map is AETR5678 or TAER5678
I need 1234AETR. But it's not possible to change this? Every time i change it, it will jump back to AETR5678. I'm using INAV 1.9.2

**Comment by shellixyz** [comment]
Please see this: https://github.com/iNavFlight/inav/issues/2774

Also this is not related to the configurator but the firmware it should have been opened here: https://github.com/iNavFlight/inav/issues
