### ISSUE TITLE
configurator 1.9.2 persistant help popup 

### ISSUE THREAD

**Issue by teknoflyer** [iNavFlight/inav-configurator#384]
does anyone else have this problem? on the OSD settings page, if you double click on any of the question marks in the Alarms section, the popup will not close even when you change to any other screen including the CLI screen? it also happens if you single click one alarm item and then single click another alarm question mark. does not happen to other help ? marks on the OSD page.  only shutting down the navigator clears it.

**Comment by shellixyz** [comment]
I can reproduce the issue. It will be fixed in the next release of the configurator. Thanks for reporting.
