### ISSUE TITLE
1.9.2 configurator launches minimized

### ISSUE THREAD

**Issue by artempolikarpov** [iNavFlight/inav-configurator#395]
OS: Windows 7x64 SP 1

Newly unzipped 1.9.2 configurator launches minimized.
It is displayed in task bar and processes list, but minimized and it is impossible to maximize. 

Restarts don't help.

Tried different approaches: as admin and not, also compatibility options for Win 7 - but nothing worked for me.

**Comment by Afinogen** [comment]
@artempolikarpov Delete config folder in AppData

Нужно удалить конфигурационный файл в папке AppData, вроде как фиксил это...

**Comment by artempolikarpov** [comment]
There is no config file or folder inside AppData or iNav folder

**Comment by Afinogen** [comment]
@artempolikarpov look in  C:\Users\%Your_UserNname%\AppData\Local\inav-configurator

**Comment by artempolikarpov** [comment]
There is only User Data folder

**Comment by Afinogen** [comment]
@artempolikarpov remove  C:\Users\%Your_UserNname%\AppData\Local\inav-configurator\User Data folder. After starting the configurator, it is automatically created

**Comment by RAMukOK** [comment]
I was having this issue.  Deleting the user data folder fixed it.

BTW, you will have to go to tools folder options and check view hidden files folders and drives to see the folder in question.

**Comment by craig34a** [comment]
Thank you. This is an issue after reinstall in a different folder.
