### ISSUE TITLE
Suggestion: rework the GUI/Logo a bit?

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/inav-configurator#4]
I could rework the colorscheme a bit to look nicer. The dark blue color is a bit heavy on the yes :). I also think the logo could use some work – and maybe not look so much alike the CF Logo. Do you call it iNAV or iNAVFLIGHT? (first one is a bit nicer - people call you project iNAV anyway). @digitalentity what do you think?

**Comment by digitalentity** [comment]
@skaman82 You have push access to this repo - feel free to do pretty much whatever you want :smile: 
The "official" name is INAV (capital "I"). INAVFlight was chosen to keep some resemblance to Cleanflight, but that could be dropped.

**Comment by digitalentity** [comment]
I'm not a UI/UX guy so any assistance with usability and UI cleanup is very appreciated and welcomed!

**Comment by skaman82** [comment]
First ideas regarding the logo. Thoughts?
![Uploading Bildschirmfoto 2016-05-17 um 19.26.56.png…]()

**Comment by DzikuVx** [comment]
My favs: 1 and 4 without map pin :)

**Comment by digitalentity** [comment]
I agree with @DzikuVx - 1 and 4 are my favorite

**Comment by jarno83** [comment]
My 12 points goes to ........ logo nr. +1:

**Comment by sppnk** [comment]
Me too, but I would prefer to have also an airplane logo :-)

**Comment by theArchLadder** [comment]
Wow, very nice logos, my vote also goes to nr. 1!
I agree that it would be nice to also have a airplane in there, but perhaps it just makes it feel cluttered...?

**Comment by skaman82** [comment]
see https://github.com/iNavFlight/inav-configurator/pull/8
