### ISSUE TITLE
A couple of things are missing from the modes tab!!!

### ISSUE THREAD

**Issue by kooopa** [iNavFlight/inav-configurator#400]
Help!!

Sir. I'm having this problem I reflashed the latest firmware v1.9.0 and redownloaded the configurator v1.9.2 I also checked if the configurator is seeing the correct version using the cli but still nothing I'm using a omnibus f3 v1.1 FC also autotune and a number of things is missing from the modes tab. what seems to be the problem? I included a screen shot of the modes tab
![s1](https://user-images.githubusercontent.com/37981560/38174920-3e120d94-3607-11e8-8b47-6acfccc42362.PNG)
![s2](https://user-images.githubusercontent.com/37981560/38174921-3e4e85b2-3607-11e8-827a-24c1989eb4f8.PNG)
![s3](https://user-images.githubusercontent.com/37981560/38174922-3e8f3a4e-3607-11e8-97cc-f8779ea4d18b.PNG)

**Comment by shellixyz** [comment]
Autotune is only available for fixed wing. Navigation modes are only available with GPS for fixed wing and with GPS+Mag for multirotors.

**Comment by kooopa** [comment]
So autotune and a couple of things doesn't always show up in the modes tab it depends on what will you use it for. about the manual mode how do I find it? haha sorry I'm a noob I'm still learning hahaha anyways thanks for the reply and clarification.

**Comment by shellixyz** [comment]
Yes. The manual mode is also only available when the flight controller is configured for use with a fixed wing model.
