### ISSUE TITLE
Inav 1.8 

### ISSUE THREAD

**Issue by bmoreking443** [iNavFlight/inav-configurator#402]
Hello all,
  Currently working on my 3rd inav build and this is where the problem lies.  I'm using a omnibus F4 pro v2, digital 9g servos , matek pdb. Servos are powered from a 5v pad on the pdb .Currently I can arm my plane but when I increase the throttle servo 3 moves with the throttle stick movement which I know is wrong.  My motor is connected to pwm 1 and does spin in the motors tab. When rolling left servo 3 on pwm 3 moves correctly.  When rolling right servo 4 connected to pwm 4 moves very little if at all.  Servos have been tested and they work fine.  I can get full range of servo 4 when using the throttle stick which is weird. I've changed the board and pdb and the issue followed.  Can you explain or give a little insight on how I can resolve the servo issue.

**Comment by shellixyz** [comment]
This is not a configurator issue please close this one and create a new one here with a config dump: https://github.com/iNavFlight/inav/issues
