### ISSUE TITLE
Capacity warning percents

### ISSUE THREAD

**Issue by alexeystn** [iNavFlight/inav-configurator#403]
Battery Capacity fields are not clear without description. It took me some time to figure out that it is spent %, not remaining %.

![capacity](https://user-images.githubusercontent.com/8948963/38458450-32946a4e-3aa7-11e8-87e3-a034e764aa97.png)

**Comment by shellixyz** [comment]
It is remaining % not spent %. % of the capacity field immediately above.

**Comment by shellixyz** [comment]
It is explained in detail in the [battery documentation](https://github.com/iNavFlight/inav/blob/master/docs/Battery.md). But we could add a tooltip.
