### ISSUE TITLE
Implement 7" preset

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#404]
[7inchGPSQuad.txt](https://github.com/iNavFlight/inav-configurator/files/1894946/7inchGPSQuad.txt)

This side of iNavFlight/inav#2995

**Comment by 18kian18** [comment]
> [7inchGPSQuad.txt](https://github.com/iNavFlight/inav-configurator/files/1894946/7inchGPSQuad.txt)
> 
> This side of [iNavFlight/inav#2995](https://github.com/iNavFlight/inav/issues/2995)

it okay all of this are negative?
acczero_x 
acczero_y
acczero_z
