### ISSUE TITLE
Unable to connect for v1.9.3 on F4 board (Matek F405 STD) with iNav 1.9.1 firmware

### ISSUE THREAD

**Issue by chtay** [iNavFlight/inav-configurator#412]
Prior upgrade to iNav 1.9.1, it is able to connect to F4 board with 1.9.0 firmware.
After upgrade to 1.9.1 (recent released), it failed to connect with timeout message.
Revert it back to 1.9.0, it works again.

**Comment by digitalentity** [comment]
Try flashing 1.9.1 with full erase

**Comment by chtay** [comment]
Done that as well...that is my default setting.

**Comment by digitalentity** [comment]
Tested on my board. No issues. What do you have connected to the board?

**Comment by chtay** [comment]
Hi again.
I am using Matek F405 STD. The firmware for this board is MATEKF405SE.
It is only connect my RX (Taranis XSR).
I tried to flash the firmware now (Tue 24 Apr 2018) but looks like the s3.amazonaws.com is down. I when to matek website to download but is not available as well (is there but link not available).
Possible firmware fault? Will have to wait till the link is up again.

**Comment by chtay** [comment]
Hah! I saw a post in the inav github as well. My mistake in this case. In this case, lets close this issue then.
