### ISSUE TITLE
cannot save mission to OmnibusF3clone EEPROM

### ISSUE THREAD

**Issue by petrweigl** [iNavFlight/inav-configurator#417]
I have perfectly (not PID tuned) working f450 with OmnibusF3clone. POSHOLD, RTH etc working. 

Saving mission from INAVconfigurator to FC works. After restart FC the mission is (of course) no longer in FC. BUT after try to save mission to EEPROM and power off and power on, the mission is also gone. I don't know if it is not hardware failure (i have only one FC) but everything else is working.

version INAV configurator 1.9.3. mac osx
version firmvare 1.9.1. Omnibus target

**Comment by shellixyz** [comment]
You need to load the mission from the EEPROM. It is not loaded automatically. You can do it with a stick command:

![stick commands](https://github.com/iNavFlight/inav/blob/master/docs/assets/images/StickPositions.png)

**Comment by KiwiDavid** [comment]
I'm using an SPF3 clone and can't get iNav 1.9.1 and Config 1.9.3 to save/load WP's.  Works fine with iNav 1.9.0 and Config 1.9.3

Cheers,
David

**Comment by MRC3742** [comment]
Same here using SPF3EVO Genuine.

Can save mission to FC only using configurator. Will not save to Eeprom.
Must use stick commands to save to or load from Eeprom using 1.9.1 and Win7 Config 1.9.3

**Comment by KiwiDavid** [comment]
Just confirming the above  - can only save and load to EEPROM using stick commands.  Can not save and restore a mission from the configurator alone.

**Comment by roskajuri** [comment]
Same issue here.
