### ISSUE TITLE
Important confirmation window for the user.

### ISSUE THREAD

**Issue by Lord-Quake** [iNavFlight/inav-configurator#419]
I was working with my settings in the configurator when I accidentally hit the "Reset Settings" button.
Obviously I was quite upset losing my all work. Luckily I had a diff backup and only needed to do minor changes.

![reset_settings](https://user-images.githubusercontent.com/29223282/39532281-d9875332-4e2c-11e8-853a-f2ac78503fa6.jpg)

My request is to have a pop window asking for confirmation. This is for all relevant situations within the configurator.

**Comment by DzikuVx** [comment]
done in #407
