### ISSUE TITLE
MSP catch-ups with BF

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#46]
We need to catch up with Betaflight a little bit. Especially MSP needs to be separated into protocol and handler parts - as done here 96115be10e902afb2d443f41ee0e291507ad1284

**Comment by DzikuVx** [comment]
Protocol | Implementation split will be done as part of #71

**Comment by DzikuVx** [comment]
Done in cbb201612470460b2a63640af4d1f6ffd0ef8976
