### ISSUE TITLE
Configuration -> Battery Capacity -> Misleading Info

### ISSUE THREAD

**Issue by davidngrc** [iNavFlight/inav-configurator#460]
The "Capacity" should mark as "Capacity per Cell", so it is more clear.
I got a 4s 18650, each 3500 mah, I had no idea, and enter 3500*4 = 14000 mah to this field..
@_@.

**Comment by fiam** [comment]
@davidngrc Wiring batteries in series increases its nominal voltage, but not its capacity measured as `Ah` since that's at the nominal voltage (it does increase `Wh`). All batteries are measured like that.

**Comment by davidngrc** [comment]
@fiam  OMG, silly me, but I am sure I am not the only one.
is it possible add a "?" on that place, and when user mouse over the "?", it will show your explanation?
