### ISSUE TITLE
TFLidar for avoidance 

### ISSUE THREAD

**Issue by sammichael25** [iNavFlight/inav-configurator#465]
Is it possible to use this tf lidar sensor to make drones avoid obstacles and improve low altitude holds?
[https://www.sparkfun.com/products/14588](url)

**Comment by shellixyz** [comment]
It is not supported at the moment. I intend to add support for it but don't know when I will have time to do it.

**Comment by DzikuVx** [comment]
This is firmware ( https://github.com/iNavFlight/inav ) , not Configurator topic. To avoid confusion I'm closing this one. Thanks.
