### ISSUE TITLE
Are Acc and Gyro x and y sensor display labels reversed?

### ISSUE THREAD

**Issue by KiwiDavid** [iNavFlight/inav-configurator#471]
Playing with a bare SPF3 board and referring to the manufacturers axis data (MPU-6050) it appears that the configurator may have acc and gyro x and y axis reversed.

The change between z axis facing up and z axis facing down should be and is 2G.   With the chip's x axis facing up and then facing down the difference on the sensor's x display is zero however the y axis changes through 2G.
Similarly when doing a quick rotation about the z axis the z gyro responds whereas when doing a quick rotation about the chip's x axis it's the y gyro plot that responds.
It may be that this is academic due to the calibration process and it certainly does not affect performance however it may make any diagnostic process a little confusing.
Can someone take a look and see if they can confirm what I'm seeing?

David

**Comment by DzikuVx** [comment]
`MSP_RAW_IMU` reports in board, not chip orientation, so this is probably the reason for what you are observing

**Comment by digitalentity** [comment]
Pitching will be read as rotation around Y axis and gravity change on X
axis.

Let's not mix up sensors, there's no roll/pitch/yaw for accelerometer and
compass - only X/Y/Z axis.

**Comment by KiwiDavid** [comment]
Can you please confirm -  that's Y axis and X axis as displayed, not actual chip axis outputs?

**Comment by digitalentity** [comment]
@KiwiDavid what would be the point in showing sensor axis? Firmware is only concerned about aircraft-relative data. Data you see are even board-relative because they consider board orientation as well.

**Comment by KiwiDavid** [comment]
OK thanks for clearing that up.  Aircraft-relative are the key words.   Sorry to be a pain on this.

David
