### ISSUE TITLE
MSP & GUI - add support for setting the gyro sync and motor protocol

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#48]
See https://github.com/iNavFlight/inav/pull/397 and https://github.com/iNavFlight/inav/pull/397/commits/8a7361625ecb88cc5a10fc20d66c53c0ba3a8449

EDIT: Also remove ONESHOT feature for version 1.2.3+
- [x] feature OneShot125 removed from 1.3 up
- [x] Motor protocol and refresh rate
- [x] Servo refresh rate
- [x] Gyro sync and denom

**Comment by digitalentity** [comment]
@DzikuVx maybe you can have a look at this?

**Comment by DzikuVx** [comment]
I will see what I can do. Not this week probably

**Comment by digitalentity** [comment]
Thanks!

**Comment by DzikuVx** [comment]
Implementation moved to #60
