### ISSUE TITLE
Tricopter Selection in Mixer Tab does not save.

### ISSUE THREAD

**Issue by spaelectronics** [iNavFlight/inav-configurator#489]
I recently upgraded to the 2.0 RC1 for both Firmware & Configuration, and I noticed when trying the new Mixer Tab, that when I choose "Tricopter", neither the "Load & Save" or the "Save" buttons work.

They work fine in Multirotor, just not Tricopter.

**Comment by flounderscore** [comment]
I believe you need to get the latest inav-configurator (from github, not
the releases).

**Comment by spaelectronics** [comment]
I have no idea how to compile it.. or else I would.

**Comment by DzikuVx** [comment]
Valid point, indeed it seems to be not working

**Comment by DzikuVx** [comment]
Will be fixed in Configurator RC2
