### ISSUE TITLE
Configurator 2.0.0.RC2- RC channels missing from the Mixer

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav-configurator#501]
2.0.0-RC2
SBUS 16 ch. RX
Only RC channels 5 to 8 are available in the mixer.
Trims are set-up on channels 8 and 9 for in-flight trimming.
How to forward channels >8 to servos in the new mixer?

**Comment by blurcak** [comment]
Hi why U closed this issue? the servo mix is still limited to channels 1-8 on TX, im using ch10 for servo tilt, and its not accesible

**Comment by Arvycka** [comment]
I  decided that I can remap channels and use 5, 6, 7 and 8 for auxiliary functions. I did not expect this issue to be fixed.

**Comment by blurcak** [comment]
Ohh, ok thats solution too :), im missing old mixer and channel forward :)

**Comment by Arvycka** [comment]
New channel forwarding works just fine, only devs forgot to include the rest of the channels. ☺ Or maybe there are technical reasons for it. Either way this issue did not get any attention...
