### ISSUE TITLE
Configurator 2.0.0.RC1 Installation Issue

### ISSUE THREAD

**Issue by plainpylut** [iNavFlight/inav-configurator#504]
I downloaded the Windows 10 (64bit) Standalone application (INAV-Configurator_win32_2.0.0-rc1.zip) and installed it.  The program ran and displayed an icon on the task bar, but I could not get the program to display the opening page; it just displays the icon on the taskbar.

I finally figured out that installing RC1 did not remove any old iNav 1.9.3 configuration files down user path "/home/USER/AppData/Local/inav-configurator/UserData/".
I deleted the contents of "UserData" and re-installed iNav.

iNav RC1 now properly executes!

This needs to be fixed; purge old config files or make them version specific.

**Comment by DzikuVx** [comment]
There is no "installer" for INAV Configurator, only executables

**Comment by plainpylut** [comment]
Sir,
Correct, however, if I delete all files in "UserData", some code segment in RC-1 re-creates them.  I call that 'installation'.  Maybe it should be called 'configuration'.  If I leave the old 1.93 files in "UserData", RC-1 refuses to display the opening page.  I only have an icon on the taskbar.
Can this be fixed?

Love your YouTube presentations on iNav!  :)
