### ISSUE TITLE
Motors tab not working in 2.0 rc1

### ISSUE THREAD

**Issue by mirohristov-com** [iNavFlight/inav-configurator#505]
The motors tab doesn't show individual motors and the master slider doesn't spin the motors. 
(with the safety checkbox on)

FC: Omnibus F4 v2 Pro.

Should I try iNav 1.9?

![inav-motor-bug](https://user-images.githubusercontent.com/7188826/42062627-2225cb86-7afc-11e8-8803-78d64017a0ad.jpg)

**Comment by flyfisher2** [comment]
I had that once when I first upgraded to 2.0.
Just powered everything OFF and On, been OK ever since.

**Comment by DzikuVx** [comment]
@mirohristov-com you are not using INAV 2.0. Only INAV 2.0 with Configurator 2.0
`Running firmware released at Apr 21...`

**Comment by mirohristov-com** [comment]
Omg i'm an idiot :) I just re-flashed and it works like a charm.

Quick question: is there a reason the unstable releases are listed as boards with a '-rc1' prefix as opposed to firmware version under that board?

![image](https://user-images.githubusercontent.com/7188826/42077757-e5c763d8-7b47-11e8-8915-2f5916dc23e6.png)

**Comment by DzikuVx** [comment]
This is bug that will be solved in RC2
