### ISSUE TITLE
OSD Font "Large" displays dots all over the screen

### ISSUE THREAD

**Issue by kn8alpha** [iNavFlight/inav-configurator#509]
[2.0.0 RC2] 
While the default font and even the Clarity font seems fine, after the 'Large' font gets uploaded the screen initializes with dots all over, but they do not get cleared once the OSD elements are loaded.

See [Example pic](https://lh3.googleusercontent.com/rao8RveZ9Vsp2xzOAVo62BMk0Wm1Ep44z_ye2B0lRWqIKFirhVJ1JTBKmDqnB7e0U7C-XW505T6xm1rpZ0BLXGo3lKWywSDuL6n1ulMTVvx1L_JsvPBfaVvLmzqR2ey5vTLgKVP1gfeBFQw1WYmDW9GAdP_UUnHpMS6hQYNrRKgIJC8QvnNn-OuXzAKS_Xz-efPkm4aOxm1oSnfF5vnYpEzR7x4IGBg7S1Ox_czSOwnAmacvjdSEE6lZefmjVVM3d0xlI2tyau17vpwGbPQGspzXYWpAFq64I3kJVns3DQvAzN6crax-NGpctfz_7zVwu68zG4Sm23L_4P-2VaXAWgkdWmtfmQpFiUrFjOYrvQeK0Lmb-K1m-z9ceecMkhXVZiF9lwlm2vSaT-2iOJkSqtJE-hy70Nr-dPCfBTy9Kg7VO02umTm3kX5_4j_OVmUhpdALW_9oIy4KVwFVZCQbMgyLM_SHNTHeJN_9e9ILsFKbxX8_6Wl2lQ2apfOHymPTmYWwsiBD9iNf31FLyYwsqqJNqLp-yoW5lPuq2eNIPI459-CsXVTEFngXC10BPKHLgASY_VmwlaqwO552cxDkUK0wiNL76-F89DRO0YM=w281-h220-no)

I noticed that large font has a 000 image (with a decimal kind of image) while others don't, might this be it:
https://github.com/iNavFlight/inav-configurator/blob/master/resources/osd/large/000.png

**Comment by fiam** [comment]
@kn8alpha Just got it fixed. It was indeed that pesky 000 image. Please, use the font attached to this message in the meantime.
[large.mcm.zip](https://github.com/iNavFlight/inav-configurator/files/2150258/large.mcm.zip)
