### ISSUE TITLE
Automatically enlarge the screen on Windows

### ISSUE THREAD

**Issue by junwoo091400** [iNavFlight/inav-configurator#513]
Can the *enlargement* be default state?

 The full screen is not displayed if not enlarged. So clicking the enlarge button every time is bugging me a little :)

Not a Big issue. But i hope it can be fixed easily as well.

**Comment by shellixyz** [comment]
It is the job of the window manager to restore the previous window state, it is not to the program to decide if it should run maximized or not.

**Comment by junwoo091400** [comment]
Thx for clearing that up
