### ISSUE TITLE
new mixer does not display tricopter motor allocation correctly (nor reversed servo)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#514]
"One of our motors is missing"

![image](https://user-images.githubusercontent.com/158229/42134363-5ac2c9b6-7d32-11e8-8f0f-7995989c08d4.png)

```
# INAV/MATEKF405 2.0.0 Jul  1 2018 / 09:19:28 (8f16ac1ff)

mmix 0  1.000  0.000  1.333  0.000
mmix 1  1.000 -1.000 -0.667  0.000
mmix 2  1.000  1.000 -0.667  0.000

# servo mix
smix 0 5 2 -100 0
set platform_type = TRICOPTER
set model_preview_type = 1
```
The example shown flies perfectly.

However, this appears to be causing some concern to the CLI challenged on RCG.

Noted that the reversed servo is also not shown as reversed in the servo tab, yet the weight /rate is +ve there (can we also be consistent in our nomenclature, it also causes some users much confusion).

![image](https://user-images.githubusercontent.com/158229/42134395-f813b22a-7d32-11e8-8915-b53af563a435.png)

Configurator 2.0.0-rc2

**Comment by gregbiv** [comment]
any news?

**Comment by stronnag** [comment]
The reversed servo display is fixed (now shows -100) at least in 08d50f7feec3631592e30cc45e92788966c8a15b

**Comment by DzikuVx** [comment]
thanks @stronnag for testing

**Comment by stronnag** [comment]
A little misunderstanding. The above comment only showed that half the problem is addressed (the reversed servo).

The PWM allocation is still displayed incorrectly (shows Servo5, Motor 2, Motor3) --- motor 1 is absent. 

![image](https://user-images.githubusercontent.com/158229/50513276-9d2b3880-0a8e-11e9-97f0-b98735a82d26.png)
