### ISSUE TITLE
2.0.0RC2 CLI command space problem

### ISSUE THREAD

**Issue by davidngrc** [iNavFlight/inav-configurator#515]
set SPACE xxx SPACE = SPACE yyy
works

but 
set SPACE SPACE xxx SPACE = SPACE yyy
will not work, same goes to get

cant we just use regular expression    \s+   to handle CLI command space?

**Comment by shellixyz** [comment]
Not sure why this is a big issue but this solves it: https://github.com/iNavFlight/inav/pull/4537

**Comment by davidngrc** [comment]
better ignore more space like
set SPACE SPACE SPACE  xxx SPACE SPACE SPACE  = SPACE SPACE SPACE  yyy

why I encounter this problem?
my old keyboard have a malfunction space key, hit once, two space out   :)
