### ISSUE TITLE
Feature Request: Format blackbox SD Card and export logs

### ISSUE THREAD

**Issue by davidngrc** [iNavFlight/inav-configurator#516]
It would be nice if iNav configurator have the following features
1. Format blackbox SD Card
2. Export blackbox SD Card logs

**Comment by Afinogen** [comment]
I support, the SD card is not always convenient to take out

**Comment by fiam** [comment]
I did some work in this INAV branch, but I got file corruption problems. If anyone wants to take a crack at it, be my guest: https://github.com/iNavFlight/inav/tree/agh_msc

**Comment by davidngrc** [comment]
new to this, too many commits, could you point me to the right one?

**Comment by davidngrc** [comment]
@fiam ?

**Comment by Afinogen** [comment]
Get list logs from SD to configurator - success.
Next - read log file...

**Comment by davidngrc** [comment]
@Afinogen nice one, so you modify the iNav code or just modify the inav-configurator code?

**Comment by Afinogen** [comment]
@davidngrc  and iNav and inav configrurator code. But experience in the development for microprocessors I do not, I will need code review)
After work I push the branches for viewing

**Comment by Afinogen** [comment]
@davidngrc  https://www.youtube.com/watch?v=LMbChvbcZzw
Is there any reason?

**Comment by davidngrc** [comment]
@Afinogen that method is better, but is it hard to implement here?

**Comment by Afinogen** [comment]
@davidngrc I could not implement msc ( The option with msc seems to me to be the best.
I managed to get the list of files in the CLI (using asyncfatfs), but there are problems when working with msp. I can not solve this problem yet and there is not enough time

**Comment by Jonny360** [comment]
Yes plz, after spending 10 minutes with tweezers to get an sdcard in only to realize I can't access from usb. Please implement this.

**Comment by AdamGFPV** [comment]
Any news on this? It would be so useful as I cannot get to the SD card on all of my builds

**Comment by MrD-RC** [comment]
MSC is implemented in 5.0
