### ISSUE TITLE
Airspeed sensor icon

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#52]
With upcoming airspeed sensor support we'll also need an airspeed sensor icon for Configurator header line. @skaman82 can you create one?

**Comment by skaman82** [comment]
@digitalentity the airspeed sensor is basically a tube, so it is hard to make a icon out of it so the user would instantly understand what it stands for. I cam up with this. What do you think?
<img width="211" alt="bildschirmfoto 2016-12-09 um 00 20 20" src="https://cloud.githubusercontent.com/assets/11768024/21031724/4c17d288-bda5-11e6-8ce6-2b9413c10595.png">

**Comment by digitalentity** [comment]
Looks ok to me. Thanks!

On Dec 9, 2016 9:20 AM, "Albert Kravcov" <notifications@github.com> wrote:

@digitalentity <https://github.com/digitalentity> the airspeed sensor is
basically a tube, so it is hard to make a icon out of it so the user would
instantly understand what it stands for. I cam up with this. What do you
think?
[image: bildschirmfoto 2016-12-09 um 00 20 20]
<https://cloud.githubusercontent.com/assets/11768024/21031724/4c17d288-bda5-11e6-8ce6-2b9413c10595.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav-configurator/issues/52#issuecomment-265885670>,
or mute the thread

**Comment by skaman82** [comment]
Great, I will add this to the configurator then - together with the red icons

**Comment by digitalentity** [comment]
Great! Thanks!

On Dec 9, 2016 9:28 AM, "Albert Kravcov" <notifications@github.com> wrote:

Great, I will add this to the configurator then - together with the red
icons

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav-configurator/issues/52#issuecomment-265887148>,
or mute the thread

**Comment by skaman82** [comment]
@digitalentity it is taken care of in https://github.com/iNavFlight/inav-configurator/commit/544be1746eccf3ef58dd169c4f33df4749619468 and https://github.com/iNavFlight/inav-configurator/commit/584b8df22b9758aa1190b2b546ddbfde5c4f198a

**Comment by skaman82** [comment]
just ad the class .error to the class of the specific icon (like .sonaricon > add .error) and it will be shown in red.

**Comment by digitalentity** [comment]
Great, thanks!
