### ISSUE TITLE
Feature PWM_OUTPUT_ENABLE

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#53]
Support for iNavFlight/inav#706

**Comment by digitalentity** [comment]
@DzikuVx we should probably make the feature the topmost one - above `MOTOR_STOP` and make it red when disabled. What do you think?

**Comment by digitalentity** [comment]
Possibly also have a red warning on "Setup" screen to indicate that outputs are disabled.

**Comment by DzikuVx** [comment]
That was my intention, indeed. I was even thinking about some kind of popup

**Comment by digitalentity** [comment]
I think popup will be annoying, just a warning on main screen (or in the top line) should be enough I think.

**Comment by digitalentity** [comment]
PR #56 exists to make this happen. Closing.
