### ISSUE TITLE
Feature Request: allow dfu to flash the hex in the sd card (with parameter)

### ISSUE THREAD

**Issue by david-ng-hk** [iNavFlight/inav-configurator#543]
My flight controller boot button was broken, and I always go to dfu mode by entering the command dfu in the CLI.

however, due to the windows dfu and some unknown reason, I can not go to the dfu mode.
in the "device manager" -> it shows "Unknown USB Device (Device Descriptor Request Failed)"
I try every driver in the latest zadig, without success, even after reboot the PC.
but then, I had no idea why, sometimes the dfu command just works.

So.
is it possible we enhance the dfu command?

option 1) after dfu command, the flight controller will reboot, it will look for a file like iNav.hex and erase all previous setting, and flash it, then delete this iNav.hex from sd card.

option 2) add some parameter to the dfu command, like
dfu  hex_filename.hex erase_all ...
then the board reboot, and run the above command automatically.

**Comment by digitalentity** [comment]
I'm afraid this is not possible. DFU bootloader resides in ROM, we have no control over it's functionality.

**Comment by davidngrc** [comment]
but how come we can select which file to flash in the inav configurator?

**Comment by digitalentity** [comment]
Configurator talks to the DFU bootloader and spoon-feeds it raw bytes to flash. It's the Configurator that reads the file, not the flight controller.

**Comment by davidngrc** [comment]
I guest the dfu loader is like one in an android phone?

in android, the twrp app can select an andoid rom to flash inside the android,
then auto reboot to twrp recovery, and flash that rom.

is that similar?

**Comment by digitalentity** [comment]
Yes and no. In android phone bootloader is aware of file system, in STM32 devices it's not. In STM32 devices bootloader is programmed in the factory and supports only specific protocols of communicating with the external flashing software. It can't be extended or modified.

**Comment by davidngrc** [comment]
anyone else confirm this?
because I search on the internet, it has some boot stm32 from sd card ...
