### ISSUE TITLE
Feature request - one-click "save" dump, diff, and screenshots automatically of all config pages

### ISSUE THREAD

**Issue by VoicOfReason** [iNavFlight/inav-configurator#544]
My suggestion is a "one-click" feature in iNav configurator that will auto save a diff, dump, and automatically save screenshots of all config pages (each page to a different jpg file) to a pre-set folder on the computer. This would make upgrading to new firmware less painless.

**Comment by wx4cb** [comment]
this would be awesome

**Comment by VoicOfReason** [comment]
For simplicity, the export could be a zip file with craft name, date, FC
name, and iNav firmware version as file name.

**Comment by johnlenfr** [comment]
This would be nice feature

**Comment by MicroMontis** [comment]
Would be nice!

**Comment by DzikuVx** [comment]
Screenshot is out of option. CLI has now "Save to file" button.
