### ISSUE TITLE
iNav Configurator does not open on Windows

### ISSUE THREAD

**Issue by bs1957** [iNavFlight/inav-configurator#548]
Version 2.0.0-rc3 Win 32
OS: Windows 7 Ultimate
RAM 4GB

Program starts and closes its window immediately. Icon on the task bar stays on.
Task manager shows 4 exe instances running though I started it once.
debug log: 
[0719/210755.226:ERROR:registration_protocol_win.cc(56)] CreateFile: The system cannot find the file specified. (0x2)
[0719/210800.772:ERROR:registration_protocol_win.cc(56)] CreateFile: The system cannot find the file specified. (0x2)

**Comment by DzikuVx** [comment]
https://youtu.be/XMoULyiFDp4

**Comment by killa198921** [comment]
I’m having the same issue.

**Comment by DzikuVx** [comment]
@killa198921 the last comment shows the solution to the problem

**Comment by Krilatii** [comment]
Win 7 -64. Такая же проблема! второй день разбираюсь, не могу запустить!

**Comment by Krilatii** [comment]
Спасибо ну тут я не нашел решения проблемы. человек на видео решает ее в win 10.. у меня нет таких файлов и папок

**Comment by NigelDcruz** [comment]
> https://youtu.be/XMoULyiFDp4

This solved the problem. Thanks.
