### ISSUE TITLE
[Feature Request] Modes ordered if used

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#555]
Not sure how easy this would be to implement, but on the modes screen, would it be possible to have the modes that you are using to be ordered to the top of the list at page load?

for example, see the attached picture, it would be nice that the modes that are being used were all at the top to avoid scrolling half/3-4' of the way down the page. It would help with knowing which ones were on a particular switch and the logic etc - at least for me.

It doesn't have to be "dynamic", but could be done whenever the page loads and gets the new "values"

![untitled](https://user-images.githubusercontent.com/1495297/43045220-79a30016-8d82-11e8-81b9-7f3981cadc98.png)

**Comment by Hennyr** [comment]
I agree, for mee to

**Comment by Tygrys-1** [comment]
I'd like a chcckbox for "Sort the used modes first". When assigning modes it is good to have them all visible in the known order. When managing used modes it might be convinient to have used on top.
