### ISSUE TITLE
[Feature request] selectable units for RTH altitude etc

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#556]
I find it really difficult (and having to constantly use a calculator :D) to convert from feet/inches to centimeters for doing things like the cruise altitude/rth altitude in the advanced tuning tab.

Being brought up on ft/in/mph and not being good at math it would be nice to be able to pick which unit i'm using. This shouldn't require any changes to the base inav code as it can be done programatically within the configurator.

If we can say have a drop down box for example next to the RTH altitude line that we can pick feet/meters from and then when we hit save it converts it to the cm format and put it in the FC.

![untitled](https://user-images.githubusercontent.com/1495297/43046781-181599de-8d9c-11e8-9301-4ac84413ffba.png)

**Comment by MrD-RC** [comment]
Added in 4.0
