### ISSUE TITLE
Profiles.js : how to set servo limits and mid points?

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav-configurator#557]
Sorry to bother, but I'm trying to build a profile for a wing and wanted to set max deflection in it.

How do I do that? Is it perhaps also possible to predefine MODES (as modes tab) ?

### Improvement:
Whoever makes a profile should be able to document **WHAT** and **WHY** a setting is set like it is. Some bigger description could perhaps do or even.

**Comment by wx4cb** [comment]
I thought servo limits are in the mixer tab under weight ?

**Comment by Pairan** [comment]
sure ... but I wanted to make a predefined profile for a wing. Its deflection is not 100% and thats what I wanted to predefine for that.

**Comment by DzikuVx** [comment]
Servo limits are set in "Servo" tab in min and max columns
