### ISSUE TITLE
maps inav

### ISSUE THREAD

**Issue by jose-elmacg** [iNavFlight/inav-configurator#558]
Hi, I would like to know if there is any version of inav configurator that does not have openstreet maps. someversion of goglee earth or similar since I can not work the points of the route in the flight field since it has no streets and I need a version with satellite view. or some plugin to change it.
Thank you

**Comment by DzikuVx** [comment]
done in #595 will be available in 2.1

**Comment by mwsadc** [comment]
I don't see this in 2.1.  Patel, please reopen.
