### ISSUE TITLE
feature request: copy osd screens

### ISSUE THREAD

**Issue by P-I-Engineer** [iNavFlight/inav-configurator#567]
it would be cool to be able to copy the osd layout between the screens.

it's an easy way to make pop up osd items.

thank you

**Comment by wx4cb** [comment]
having just setup my osd screens, i agree, it would be nice to be able to copy into the others. I have some things such as battery voltage and lat/long on all the screens int he same place.

**Comment by shellixyz** [comment]
For now you can do it from the CLI. You can find the ids here: https://github.com/iNavFlight/inav/blob/master/src/main/io/osd.h#L38

For example if you want to have VBAT (id 1) at the same position on all the OSD layouts you need to run:
osd_layout 0 1 column row V
osd_layout 1 1 column row V
osd_layout 2 1 column row V
osd_layout 3 1 column row V

**Comment by jj-uk** [comment]
+1 on this. I have setup the default layout the way I like it. I'd now like to duplicate that to 2 alt osd screens, then turn off stuff on them.

A "copy from OSD x screen" button next to the OSD preview would be a great addition.

**Comment by pDR8iLQ4go** [comment]
Does it work to paste a part of a dump file like „osd_layout 0 1 column row V“ in the CLI command line? Or may I even copy and paste all osd information in the CLI command line?

**Comment by jj-uk** [comment]
Yes. Dump to a text file, and change the screen I'd then paste back in the terminal.

**Comment by MrD-RC** [comment]
https://www.mrd-rc.com/tutorials-tools-and-testing/useful-tools/inav-osd-switcher-tool/

**Comment by jj-uk** [comment]
I don't think this should have been closed. It's not been implemented in iNav. Creating an external tool is a cool, but having this in the GUI is cooler.
