### ISSUE TITLE
configurator doesn't work in 10.9.5 HELP !!!

### ISSUE THREAD

**Issue by freddybloggs** [iNavFlight/inav-configurator#569]
I have 10.9.5 you have disabled the standalone app on my machine.

**Comment by shellixyz** [comment]
I'm using 50.29.32.45 and it is working fine for me :rofl:

**Comment by freddybloggs** [comment]
what is 50.29.32.45 and where do I get it, the last usable version for me is 1.9.3 and with this I am unable to set up my HEX as there is no mixer TAB.

**Comment by shellixyz** [comment]
You can get the latest version here: https://github.com/iNavFlight/inav-configurator/releases

**Comment by freddybloggs** [comment]
I have it, it won't work with 10.9.5 is says it requires OS 10.10 or greater

**Comment by shellixyz** [comment]
Latest is 2.0.0. You are sure you got the latest one ? Screenshot ?

**Comment by freddybloggs** [comment]
![screen shot 2018-08-30 at 23 40 04](https://user-images.githubusercontent.com/383514/44883162-23d13400-acae-11e8-921c-4837e4dcf70a.png)

**Comment by shellixyz** [comment]
Maybe it is a requirement of the updated NPM
