### ISSUE TITLE
[feature request] parameters for mission waypoints (time to stay, action, etc.), numbering waypoints

### ISSUE THREAD

**Issue by Pitichinaccio** [iNavFlight/inav-configurator#575]
Hello, 
I had the idea of adding some more parameters to the waypoints of a mission, like time to stay (until flying forward to next WP), actions (staying still, heading to certain direction, turning round with defined speed) and things like that.
There was also an other suggestion on the INAV group at facebook to add numbers to the waypoints and have them dislayed on the OSD.
Unfortunately my programming skills are to poor to do this on my own, but maybe it is an idea worth thinking about. Thanks!
Bernd

**Comment by MrD-RC** [comment]
There is loiter time and other enhancements in missions now. I think this issue can be closed.
