### ISSUE TITLE
SETTINGS VALIDATED PROBLEM

### ISSUE THREAD

**Issue by GaryMcDonogh** [iNavFlight/inav-configurator#579]
My aircraft has a X at settings validated.
How do I determine what settings are causing the problem?

 diff

# version
# INAV/SPEEDYBEEF4 2.0.0 Aug 20 2018 / 19:24:34 (dbdd1656a)

# resources

# mixer
mmix 0  1.000  0.000  0.000  0.000

# servo mix
smix 0 3 0 100 0
smix 1 4 2 100 0
smix 2 5 1 100 0

# servo
servo 3 1000 2000 1446 100
servo 4 1000 2000 1479 100
servo 5 1000 2000 1542 -100

# feature
feature -BLACKBOX
feature -OSD
feature MOTOR_STOP
feature GPS
feature AIRMODE
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 3 2 115200 57600 0 115200
serial 4 0 115200 38400 0 115200

# aux
aux 0 0 1 1875 2100
aux 1 1 0 900 1325
aux 2 8 0 1850 2100

# adjrange

# rxrange

# osd_layout

# master
set looptime = 2000
set gyro_sync = ON
set gyro_hardware_lpf = 188HZ
set acc_hardware = MPU6000
set acczero_x = 69
set acczero_y = -40
set acczero_z = -368
set accgain_x = 4117
set accgain_y = 4121
set accgain_z = 3978
set mag_hardware = NONE
set baro_hardware = NONE
set pitot_hardware = NONE
set serialrx_provider = SBUS
set failsafe_procedure = NONE
set failsafe_min_distance = 2000
set failsafe_min_distance_procedure = NONE
set align_board_roll = -30
set align_board_yaw = 900
set platform_type = AIRPLANE
set model_preview_type = 14
set nav_rth_allow_landing = NEVER
set nav_rth_abort_threshold = 35000
set nav_rth_altitude = 3500
set nav_fw_cruise_thr = 1650
set nav_fw_max_thr = 1750
set nav_fw_bank_angle = 75
set nav_fw_climb_angle = 60

# profile
profile 1

set mc_p_pitch = 20
set mc_d_pitch = 15
set mc_p_roll = 20
set mc_d_roll = 15
set mc_p_yaw = 45
set mc_i_yaw = 5
set mc_d_yaw = 15
set mc_i_level = 5
set fw_p_pitch = 20
set fw_i_pitch = 30
set fw_ff_pitch = 15
set fw_p_roll = 20
set fw_i_roll = 30
set fw_ff_roll = 15
set fw_p_yaw = 45
set fw_i_yaw = 5
set fw_ff_yaw = 15
set max_angle_inclination_rll = 750
set max_angle_inclination_pit = 800
set dterm_setpoint_weight =  2.000
set pidsum_limit = 1
set nav_mc_pos_z_p = 40
set nav_mc_pos_z_i = 5
set nav_mc_pos_z_d = 10
set nav_mc_vel_z_p = 0
set nav_mc_vel_z_i = 0
set nav_mc_vel_z_d = 0
set nav_mc_pos_xy_p = 75
set nav_mc_pos_xy_i = 5
set nav_mc_pos_xy_d = 8
set nav_mc_vel_xy_p = 0
set nav_mc_vel_xy_i = 0
set nav_mc_vel_xy_d = 0
set pitch_rate = 15
set yaw_rate = 9
set manual_rc_expo = 50
set manual_rc_yaw_expo = 40

# battery_profile
battery_profile 1

**Comment by DzikuVx** [comment]
Use CLI `status` command
