### ISSUE TITLE
angle mode  roll and pich rate 

### ISSUE THREAD

**Issue by kfir13** [iNavFlight/inav-configurator#58]
hello 
i am trying to increase  the rate of roll and pich in angle mode 
can someone give me a tip ?
i am using the latest firmware
thanks 
kfir

**Comment by DzikuVx** [comment]
@kfir13 There is no setting that sets roll/pitch rate in Angle mode directly. 
Rate is determined by  LEVEL P  =

**Comment by digitalentity** [comment]
@kfir13 maybe you are talking about increasing maximum **roll/pitch angles** in `ANGLE` mode? Those are controlled by `max_angle_inclination_rll` and `max_angle_inclination_pit` CLI parameters.
