### ISSUE TITLE
Cannot configure servos in iNav 1.9.1 with 2.0 configurator

### ISSUE THREAD

**Issue by Tygrys-1** [iNavFlight/inav-configurator#583]
The servos tab is empty. It tells to configure the mixer.
The mixer tab says that it is not supported on 1.9.1.

Can the configurator be smarter and allow servo page to work as before on pre 2.0 software?

**Comment by davidngrc** [comment]
why not use the v1.9.1 configurator? https://github.com/iNavFlight/inav-configurator/releases/tag/1.9.1
v2.0 change so many things, I don't think the developer have time to do backward compatibility test.

**Comment by Tygrys-1** [comment]
Because when I start the configurator 1.9.3 it told me that there is a new version to upgrade. So I upgraded :-)

**Comment by DzikuVx** [comment]
This land in "no fix" zone I'm affraid. With Configurator 2.1 we lock firmwares older than 2.0
