### ISSUE TITLE
[feature request]  save complete missions in local file

### ISSUE THREAD

**Issue by Pitichinaccio** [iNavFlight/inav-configurator#584]
I think it would be helpfull to have the option to save a complete mission in a local file on the PC. 
Sometimes you want to modify a previous mission or just want to fly it once again. In this case you have to re-enter all waypoints into the configurator, as only one mission could be stored within the FC. Maybe it's also possible to store sveral missions in the FC EEPROM and load the by stick command.

**Comment by DzikuVx** [comment]
done in #720
