### ISSUE TITLE
Inav 2.0 Unable to calibrate accelerometer

### ISSUE THREAD

**Issue by emaggard13** [iNavFlight/inav-configurator#586]
I flashed Inav 2.0 to my matek f411 wing and am unable to complete calibration.  I get to step 3 and it reverts back to step 2.  Accelerometer is acting as expected on setup tab but I cant complete calibration.

**Comment by DzikuVx** [comment]
Order is not important, only first step should be performer with the board facing up. All other steps can be done is any order
