### ISSUE TITLE
Inav 2.0 OSD Lines

### ISSUE THREAD

**Issue by MohammadMubin** [iNavFlight/inav-configurator#589]
Hello i have upgrade to inav 2.0 and facing a issue where there are lines on the OSD 

![win_20181027_14_37_19_pro](https://user-images.githubusercontent.com/12457839/47603027-c03e5b00-d9ff-11e8-958e-4c5a90bb9447.jpg)

**Comment by DzikuVx** [comment]
Upload OSD fonts
