### ISSUE TITLE
Please add support for Holybro Kakute F7

### ISSUE THREAD

**Issue by wsalopek** [iNavFlight/inav-configurator#594]
Subject says it all.  Thanks.

**Comment by shellixyz** [comment]
It has already been done. Will be available in 2.1.

**Comment by DJBriez** [comment]
YES!!!!

**Comment by wsalopek** [comment]
Is there a guesstimated ETA?

Thanks...

--

Bill

**Comment by DzikuVx** [comment]
Noty sooner than January
