### ISSUE TITLE
Nav poshold problem

### ISSUE THREAD

**Issue by Castion01** [iNavFlight/inav-configurator#597]
[blackbox_log_2018-11-11_172439.TXT](https://github.com/iNavFlight/inav-configurator/files/2569567/blackbox_log_2018-11-11_172439.TXT)
Hi, I'm having a problem to activate NAV POSHOLD / HEADING HOLD function. I'm using an SP F3 FC with NAZA GPS on a 250 size frame. I have 9-10 satellites, the quad is flying OK in angle mode (besides of a mild backwards drift) but when I activate with a switch NAV POSHOLD nothing happens, the quad is not keeping the position or not even changing the flying behaviour. I have calibrated accelerometer, compass, no warning signals. I have tried NAV POSHOLD alone and also together with HEADING HOLD with the same switch with no luck. Please help me to find the solution to this problem.

I have attached the some pictures, dump file and blackbox file. 
![nav pos hold 2](https://user-images.githubusercontent.com/35392524/48315437-67adb700-e5d6-11e8-8d6a-22548a2a6274.JPG)
![nav pos hold 3](https://user-images.githubusercontent.com/35392524/48315438-67adb700-e5d6-11e8-8bbb-f2349e9e605c.JPG)
[DR0111_150_Flysky_Inav_F3_NAZA!.txt](https://github.com/iNavFlight/inav-configurator/files/2569563/DR0111_150_Flysky_Inav_F3_NAZA.txt)

![nav pos hold 1](https://user-images.githubusercontent.com/35392524/48315400-04bc2000-e5d6-11e8-9f5b-4b5f3edc8601.JPG)

**Comment by Castion01** [comment]
I've made some more flying tests. Programmed a switch pos1: Angle mode, pos2: Heading hold & Nav Poshold (and NO Angle mode). I armed the quad in pos1 (Angle mode) then I was hovering around in 1m altitude then moved the flight mode switch to pos2. The quad did not keep the position but was not even in Angle mode which I found a bit odd as Nav Poshold mode is by default combined with Angle mode. 

Does it mean that the Nav poshold was not active (despite that flight mode was actived with the switch)?

**Comment by kardon18** [comment]
Are you aware that **Nav Poshold** is a Loiter function? So the quad will take up a stationary position in the air.  
It is best used in conjunction with **Altitude hold** mode.  This will give the quad the ability to hold, not only 2D position, but altitude as well.
You need a barometer for this to work. And I noticed from your configurator screen shoots, that the Barometer is not configured or connected correctly.

**Comment by shellixyz** [comment]
@Castion01 Sounds like the PH mode wasn't activating. It can happen even if you have a 3D fix when the estimated position precision is too low. For now if the PH mode is not activating and you don't have any other mode combined to it it is like you have no mode selected (ACRO). Have you got a BB log ?

@kardon18 Since 2.0 PH is always 3D you don't need to add AH to it.

**Comment by Castion01** [comment]
Thanks for the advises so far. I have activated the PH in the air.
@shellixyz, In theory, the PH mode by-default including the Angle mode (https://github.com/iNavFlight/inav/wiki/Navigation-modes). But I have tried also with Angle mode with no success. 
My supposition is that F3 Acro and NAZA GPS somehow are not compatible. I've ordered a M8N GPS to do other tests with the same Betaflight setup.

**Comment by Castion01** [comment]
Looks like I've found the problem and it was the sbus setup. Changed to PPM and now works.

**Comment by davidbitton** [comment]
@Castion01 any idea why that might be?

**Comment by Aaronprat** [comment]
@Castion01 can you share more information about the solution?

Thanks

**Comment by fremebondo** [comment]
Hi, I am facing the same exact issue on a fixed wing. Any hint to solve? I'm using SBus to read from taranis X8R receiver.

**Comment by Palput** [comment]
hello, I am interested in this case and I am researching all about it, i would appreciate information. 
Thank you
Pd: as soon as I change PPM I will say if it really works for future reference.
