### ISSUE TITLE
Vision Font - Additions for increased sharpness and clarity 

### ISSUE THREAD

**Issue by kardon18** [iNavFlight/inav-configurator#605]
Vision font is my most preferred font to use. Although I do find that some of the characters are a little difficult to see and make out on lower resolution screens.
I went through and changed the highlights a layout of some of the characters, so they appear clearer to read at a glance. And look a little sharper.

If they seem acceptable. Would you mind adding some of them?

![157-158](https://user-images.githubusercontent.com/43928973/49339647-32eac800-f689-11e8-8110-f0c1a958eba6.png)
![160](https://user-images.githubusercontent.com/43928973/49339648-32eac800-f689-11e8-8b42-a27c3eab0677.png)
![166](https://user-images.githubusercontent.com/43928973/49339649-33835e80-f689-11e8-8337-67cff8f5342a.png)
![167](https://user-images.githubusercontent.com/43928973/49339799-06d04680-f68b-11e8-82e5-1e3329e684ee.png)
![169](https://user-images.githubusercontent.com/43928973/49339651-341bf500-f689-11e8-934e-f80d242bc289.png)
![172-173](https://user-images.githubusercontent.com/43928973/49339652-341bf500-f689-11e8-8fb7-140a6f7f5475.png)
![174](https://user-images.githubusercontent.com/43928973/49339653-34b48b80-f689-11e8-9d6e-afbf5c4e9258.png)
![176](https://user-images.githubusercontent.com/43928973/49339654-34b48b80-f689-11e8-9668-efa92fe25364.png)
![177](https://user-images.githubusercontent.com/43928973/49339655-354d2200-f689-11e8-9d45-275c8b30de53.png)
![178](https://user-images.githubusercontent.com/43928973/49339656-354d2200-f689-11e8-9605-77989919fac8.png)
![181](https://user-images.githubusercontent.com/43928973/49339657-354d2200-f689-11e8-8177-8bce55e14a49.png)
![182](https://user-images.githubusercontent.com/43928973/49339658-35e5b880-f689-11e8-898a-e07c899f5952.png)
![184](https://user-images.githubusercontent.com/43928973/49339659-35e5b880-f689-11e8-80af-528c3426622c.png)
![185](https://user-images.githubusercontent.com/43928973/49339660-367e4f00-f689-11e8-873a-f652183daaff.png)
![186](https://user-images.githubusercontent.com/43928973/49339661-367e4f00-f689-11e8-95b5-fe83107a93eb.png)
![187](https://user-images.githubusercontent.com/43928973/49339662-367e4f00-f689-11e8-93fc-abe24203fc3b.png)
![189-190](https://user-images.githubusercontent.com/43928973/49339663-3716e580-f689-11e8-8aa0-55020f8164f4.png)
![218-219-220-221-222](https://user-images.githubusercontent.com/43928973/49339664-3716e580-f689-11e8-8a3e-c540c5ba405e.png)
![006](https://user-images.githubusercontent.com/43928973/49339665-3716e580-f689-11e8-8fe2-bde4b6df2bfb.png)
![007](https://user-images.githubusercontent.com/43928973/49339666-37af7c00-f689-11e8-9b25-37a2a785e39f.png)
![024](https://user-images.githubusercontent.com/43928973/49339667-37af7c00-f689-11e8-8ed7-143aa68503bb.png)
![025](https://user-images.githubusercontent.com/43928973/49339668-38481280-f689-11e8-9630-fcbc12b91434.png)
![026](https://user-images.githubusercontent.com/43928973/49339669-38481280-f689-11e8-8d3d-2d4d1a858c36.png)
![027](https://user-images.githubusercontent.com/43928973/49339670-38481280-f689-11e8-9da6-e6d29f43eab9.png)
![028](https://user-images.githubusercontent.com/43928973/49339671-38e0a900-f689-11e8-8ba9-3ea496e4ef2d.png)
![029](https://user-images.githubusercontent.com/43928973/49339672-38e0a900-f689-11e8-87fe-6a00b311d8c8.png)
![030-031](https://user-images.githubusercontent.com/43928973/49339673-39793f80-f689-11e8-929e-ab3fa694722c.png)
![037](https://user-images.githubusercontent.com/43928973/49339674-39793f80-f689-11e8-857f-7e368b11d9d0.png)
![042](https://user-images.githubusercontent.com/43928973/49339675-39793f80-f689-11e8-8ec5-17ac95965201.png)
![154](https://user-images.githubusercontent.com/43928973/49339677-3a11d600-f689-11e8-8e06-76f550ebd66b.png)
![155](https://user-images.githubusercontent.com/43928973/49339678-3a11d600-f689-11e8-9e30-9e7f59e99fe2.png)
![156](https://user-images.githubusercontent.com/43928973/49339679-3aaa6c80-f689-11e8-816b-80c366d5930e.png)

**Comment by shellixyz** [comment]
Could you upload a zip of the directory with the modified chars please ? Would make comparing the old and new chars much easier.

**Comment by kardon18** [comment]
I wasn't sure if you meant a zip folder of the .png  

Or was talking about adding a zip with the modified characters being ran through the Max7456tool and converted to .mcm 
That is a bit over my head at the moment. I'm trying to work out the Max7456tool. 

[Font modifications.zip](https://github.com/iNavFlight/inav-configurator/files/2637616/Font.modifications.zip)

**Comment by shellixyz** [comment]
Perfect, it is what I needed. Not everybody likes your modifications so I proposed them as a new font "Vision Alt". See #608.

**Comment by kardon18** [comment]
@shellixyz -Not everybody likes your modifications so I proposed them as a new font "Vision Alt"

That sounds good to me.
I wasn't expecting that you would propose a new font. But to my surprise it was added. Thanks Michel.

I only changed a few thing, hoping they may be adapted to the current Vision font. 
But due to it being its own font. I have given it some more individuality. And have tried to make it stand by itself.
There a few new extra's I worked on today. I did this after using the version you made last night. And flying with it today, to see if any area's needed cleaning up.
It looks okay. But I though I may as well go the whole way before its release in 2.1.

I know you went to a lot of effort yesterday to get it all going. 

Would you mind again incorporating these into Vision-Alt.
(I also added the new 3D speed symbols in this lot too)

Thanks

[vision-alt (tweeks).zip](https://github.com/iNavFlight/inav-configurator/files/2643518/vision-alt.tweeks.zip)

**Comment by shellixyz** [comment]
> Would you mind again incorporating these into Vision-Alt.

No problem. I just updated the PR with your new proposed modifications :)

**Comment by kardon18** [comment]
Thanks again Michel for your help.

I took it out this morning with the latest editions. And i'm very pleased with the appearance. 
I was concerned about how the variant of the new home arrow, would look. It took some getting right, on certain angles. But it work well. It has a shallower look to it. More like the StarTrek/Starfleet insignia.

![vision-alt pre 1](https://user-images.githubusercontent.com/43928973/49478221-4b1e3b00-f873-11e8-9b5a-a7cc270ee9f2.PNG)
![vision-alt pre 2](https://user-images.githubusercontent.com/43928973/49478223-4bb6d180-f873-11e8-9834-fddce0eac4e4.PNG)

**Comment by kardon18** [comment]
Thanks again Michel for your help.

I took it out this morning with the latest editions. And i'm very pleased with the appearance.
I was concerned about how the variant of the new home arrow, would look. It took some getting right, on certain angles. But it works well. It has a shallower look to it. More like the StarTrek/Starfleet insignia.

![vision-alt pre 1](https://user-images.githubusercontent.com/43928973/49479161-211a4800-f876-11e8-9bba-ceba731da84f.PNG)
![vision-alt pre 2](https://user-images.githubusercontent.com/43928973/49479162-21b2de80-f876-11e8-9c42-e7214d97e1f4.PNG)

**Comment by kardon18** [comment]
With these it should be finished. I noticed that Speed and 3D Speed were different in layout.

Let me know of 152 "gyro". I added two others in this zip. Choose which one you like best of these.  Or just leave the one from yesterday.

[vision-alt fixes.zip](https://github.com/iNavFlight/inav-configurator/files/2649643/vision-alt.fixes.zip)

**Comment by shellixyz** [comment]
I updated the PR. Symbol 152 doesn't matter, it is not used.

**Comment by kardon18** [comment]
I did a lot of flying yesterday, with the vision-alt.  And noticed that a some of the icons needed toning down a little on their boarders. Just to keep in line with vision fonts over all look. 
Although these new tones still leave it more highlighted than the original vision. Which is the look I was after. Not too much...Not too little.
I think I'm becoming OCD :/
Thanks again.

[vision-alt (more tweeks).zip](https://github.com/iNavFlight/inav-configurator/files/2660197/vision-alt.more.tweeks.zip)

**Comment by shellixyz** [comment]
Hehehehe ;)

PR Updated

**Comment by shellixyz** [comment]
PR merged, closing

**Comment by kardon18** [comment]
Hi Michel,
Sorry to be a pain.
I didn't know when you would merge the font.
And I have been fine tuning it, and adding many extra's. With some flight buddies trying it too. And giving me their impressions.
It now has some modified letters and numbers as well. Most of vision has been altered for the new look of vision-alt.
It also 3D home and wind direction indicators.
Let me know what you think?

**It is now finished and read to merge.**
Thanks for your patience with me, as I was getting it spot on.
  
![vision-alt](https://user-images.githubusercontent.com/43928973/50119869-1a44f980-02a8-11e9-90de-8d7d60c0a575.PNG)


The files is already in .MCM
[vision-alt.zip](https://github.com/iNavFlight/inav-configurator/files/2688077/vision-alt.zip)

**Comment by shellixyz** [comment]
Sorry I should have asked you. Looking good ! I will update it.

**Comment by kardon18** [comment]
@shellixyz 
I have another dozen updates to the vision-alt font. Which changes its appearance a little more, in area's.
I won't post them here yet. Because I've noticed that there have been a few extra functions added to inav, that may require glyph additions or edits. Before 2.1 is released.

Keep me informed of whether the font needs any additions. And when the time comes for the 2.1 RC.
Then i'll post the rest.

Thanks

**Comment by shellixyz** [comment]
Sorry, been away for a week. I'm slowly going through the GH mails. 

I don't see any glyph needing to be changed or added for the new features. The only feature I can think of that needs new glyphs in 2.1 is the 360° AHI but the glyphs for that (vertical horizon bars) are already present.

**Comment by kardon18** [comment]
I hadn't heard back from you Shelli.
I wasn't sure if you were working on the above mentioned or not. So I thought I'd post the finished Vision-alt font anyway.

[vision-alt(finished).zip](https://github.com/iNavFlight/inav-configurator/files/2730214/vision-alt.finished.zip)

**Comment by shellixyz** [comment]
Sorry, looks like I've missed the notification mail. You last update looks good. I didn't include the symbols 8 to 12 in the update because they are unused. I can include your propositions for the remaining flight time and distance symbols, they are looking good. We're going to release 2.1RC very soon.

**Comment by kardon18** [comment]
Thanks for the update :)

The file here includes :
1) Flight time remaining in - hours / minutes
2) Distance remaining in - Km / Meters / Miles / Feet  

There are six glyphs in total, for each font.
With each gylph having its own characteristics style for that font.

I know six extra symbols for this function is a lot. But I figured; Unless the Remaining time in HOURS was included. A bug might turn up.

I thought this my save you some time. 
[Remaining time_Remaining distance_glyphs.zip](https://github.com/iNavFlight/inav-configurator/files/2731024/Remaining.time_Remaining.distance_glyphs.zip)

**Comment by kardon18** [comment]
How about this symbol  for #3587

![over home location](https://user-images.githubusercontent.com/43928973/50744456-6ff13e00-1277-11e9-9e0e-7a1111e98955.PNG)
[Over home position icon.zip](https://github.com/iNavFlight/inav-configurator/files/2731114/Over.home.position.icon.zip)

**Comment by shellixyz** [comment]
Nice. I didn't check how it looks on the OSD but it should do the job :+1:

**Comment by shellixyz** [comment]
We're going to wait for 2.2 to decide if we're adding new symbols for the remaining distance and time because of the new changes to the OSD code in 2.1

**Comment by kardon18** [comment]
Opps.
I didn't mean to step on anyone's toes.

How about "IMPACT" font.  
Its similar to that style.

**Comment by kardon18** [comment]
Hi Shelli,
I noticed a few extra commit features.  **Home Slope and Total** 

@danarrib  and @OlivierC-FR have added fonts in Clarity and Vision accordingly.

I thought i'd do the same for Impact.
Plus I also did another "Over Home Location" symbol that is 3D in appearance.  Its still based on the above, glyph I posted; But it better suits the style of the 3D home arrow in Impact.

[Home_Total and Slope glyphs for Impact font.zip](https://github.com/iNavFlight/inav-configurator/files/2751696/Home_Total.and.Slope.glyphs.for.Impact.font.zip)

Let me know what you think.
![example](https://user-images.githubusercontent.com/43928973/51069360-5db13e80-1681-11e9-865f-1e4094490bac.PNG)

**Comment by kardon18** [comment]
Hi Shelli,
I noticed a few extra commit features.  **Home Slope and Total** 

@danarrib  and @OlivierC-FR have added fonts in Clarity and Vision accordingly.

I thought i'd do the same for Impact.
Plus I also did another "Over Home Location" symbol that is 3D in appearance.  Its still based on the above, glyph I posted; But it better suits the style of the 3D home arrow in Impact.

[Home_Total and Slope glyphs for Impact font.zip](https://github.com/iNavFlight/inav-configurator/files/2751696/Home_Total.and.Slope.glyphs.for.Impact.font.zip)

Let me know what you think.
![example](https://user-images.githubusercontent.com/43928973/51069360-5db13e80-1681-11e9-865f-1e4094490bac.PNG)

**Comment by kardon18** [comment]
Hi Shelli,
I noticed a few extra commit features.  **Home Slope and Total** 

@danarrib  and @OlivierC-FR have added fonts in Clarity and Vision accordingly.

I thought i'd do the same for Impact.
Plus I also did another "Over Home Location" symbol that is 3D in appearance.  Its still based on the above, glyph I posted; But it better suits the style of the 3D home arrow in Impact.

[Home_Total and Slope glyphs for Impact font.zip](https://github.com/iNavFlight/inav-configurator/files/2751696/Home_Total.and.Slope.glyphs.for.Impact.font.zip)

Let me know what you think.
![example](https://user-images.githubusercontent.com/43928973/51069360-5db13e80-1681-11e9-865f-1e4094490bac.PNG)

**Comment by kardon18** [comment]
> 
> 
> It's looking good ! I will take the time this weekend to add the code for the home glyph and update the font.

Thanks Shelli

**Comment by kardon18** [comment]
Hi Shelli, Any chance of you integrating the above characters, plus a few that I fixed up by request. Before the full version of 2.1 is released?  
All are in this zip.
Thank you
[Update with slope_home_total.zip](https://github.com/iNavFlight/inav-configurator/files/2810733/Update.with.slope_home_total.zip)

**Comment by kardon18** [comment]
Hi Shelli, Any chance of you integrating the above characters, plus a few that I fixed up by request. Before the full version of 2.1 is released?  
All are in this zip.
Thank you
[Update with slope_home_total.zip](https://github.com/iNavFlight/inav-configurator/files/2810733/Update.with.slope_home_total.zip)

**Comment by kardon18** [comment]
Thank you Alberto :+1:  Much appreciated.

**Comment by Jetrell** [comment]
Hey guys, I found this original Impact font thread.
Over the months I have used Impact font with inav and cleaned it up.
This upgrade/fix/addition adds better 3D looking home arrows, with other cleanups.

Any chance @fiam or @shellixyz of adding them?
[Impact 2.2 additions.zip](https://github.com/iNavFlight/inav-configurator/files/3275365/Impact.2.2.additions.zip)
