### ISSUE TITLE
Motor value is displayed at incorrect location in motor test mode

### ISSUE THREAD

**Issue by flybabo** [iNavFlight/inav-configurator#613]
To reproduce the problem:
1. Select the motors tab.
2. Enable motor test mode.
3. Move the second slider up and down and you'll see that the motor value of the second motor is displayed under the first motor bar graph.

Motor values are displayed correctly at each motor bar graph.
They also displayed correctly when the master slider is moved up and down.

**Comment by shellixyz** [comment]
Confirmed

**Comment by shellixyz** [comment]
Fixed by #614, closing
