### ISSUE TITLE
LED Strip Non-Functional 2.0.0

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav-configurator#619]
When I go into the LED Strip page, it shows "0 remaining" even though I haven't programmed any LEDs (new FC).  Also, there doesn't seem to be any LED config data when I do a dump (2.1 pre-release).

Has LED functionality been totally removed?  I know it never really worked well, but at least I could get the LEDs to light and change to red when the battery was low.

**Comment by shellixyz** [comment]
It seems to be working fine for me (master branch + OMNIBUS). Maybe the target you're using doesn't have the LED_STRIP feature enabled.

![capture d ecran de 2018-12-22 16-07-25](https://user-images.githubusercontent.com/4030264/50375818-ca499800-0603-11e9-9701-3b3ea5f43c77.png)

**Comment by teckel12** [comment]
@shellixyz How would the configurator know if my target supports LED strip? My target is new, so 2.0.0 doesn't know it even exists.

I haven't messed with the configurator source, so I really don't know how it operates. But it allows me to activate LED strip and LED strip is on the menu.  Maybe this is what happens with a target that the configurator doesn't know about? 

I'll close this and take it to Telegram as a question instead of an issue.

**Comment by teckel12** [comment]
The target MATEKF722SE has LED and buzzer enabled, but it seems the configurator doesn't know about it.

**Comment by teckel12** [comment]
Closing this as it's got to be an issue with the target
