### ISSUE TITLE
new mixer does not display tricopter motor allocation correctly

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#624]
Continues #514, which addressed half the previously reported problem.

**Comment by stronnag** [comment]
Motor 1 missing 

![image](https://user-images.githubusercontent.com/158229/50513431-ad8fe300-0a8f-11e9-93c5-878d9dae7d03.png)

**Comment by DzikuVx** [comment]
fixed in #810 and will be a part of the next release
