### ISSUE TITLE
No map displayed on GPS tab with 2.1.1

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav-configurator#664]
Map area remains blank in GPS tab at all times with the Configurator 2.1.1:

![gps map](https://user-images.githubusercontent.com/25912739/51787773-a804e600-217e-11e9-82b5-fdb2970af174.png)

Map is shown correctly  with the Configurator 2.0:

![map 2 0](https://user-images.githubusercontent.com/25912739/51787864-89ebb580-217f-11e9-94f0-86260a20d940.jpg)

**Comment by vasobg** [comment]
Yes, I have the same issue!

**Comment by DzikuVx** [comment]
@Arvycka @vasobg 

Please post screenshots with settings popup:

![image](https://user-images.githubusercontent.com/966811/52175283-a7cda180-27a1-11e9-90b2-e7eed1d145bf.png)

"double gear" icon in top-right corner

**Comment by Arvycka** [comment]
I don't have a GPS lock inside today, but even without it 2.0.0 displays a progress bar and a message "Waiting for GPS 3D lock".
There is nothing going on in that window in 2.1.1 - it's dead:

![gps](https://user-images.githubusercontent.com/25912739/52175498-8672b280-27ad-11e9-9599-a7f416bdb6fd.jpg)

**Comment by Arvycka** [comment]
Pawel, it's only in the Chrome App that the map is not displayed - it's fine in the stand-alone windows version.
