### ISSUE TITLE
add a Search field

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav-configurator#665]
There are so many parameters in INAV that it's tough to navigate.
One solution I see in some programs is adding a search box. When you type in the box, the UI gets filled with matches, thes matches can be sliders or radio buttons, fields etc...

**Comment by DzikuVx** [comment]
This thing will rather never happen without major rewrite of everything. CLI has something like this. Type `get {x}` where `{x}` is a letter or two or a setting name and it will list all settings that match

**Comment by laurentopia** [comment]
Ok thanks. I'll learn to love CLI
