### ISSUE TITLE
Changing "acc_lpf_hz" setting in configurator does not change CLI value

### ISSUE THREAD

**Issue by teknoflyer** [iNavFlight/inav-configurator#669]
changing the value of "acc_lpf_hz" in configurator 2.1 does not change the value in CLI. using CLI to change the value does change and show the new value. however the configurator still shows the old value that was last set by the configurator. the two different values still show when the board is read on a different computer. this was tried on all versions from 1.93 to 2.1.1 on both an spracing F3 EVO and omnibus F4 pro using the latest firmware 2.0.1 and 2.1RC2

**Comment by DzikuVx** [comment]
Confirmed, firmware bug not configurator. I'm closing this one
