### ISSUE TITLE
GUI Modes checkbox hide/show unassigned

### ISSUE THREAD

**Issue by roscor61** [iNavFlight/inav-configurator#699]
Hi,
I want request a  checkbox in the GUI in Modes section  that hides/view all the non-assigned modes.
Thank you

**Comment by wx4cb** [comment]
i mentioned a similar thing a couple years ago that was effectively ignored :D

https://github.com/iNavFlight/inav-configurator/issues/555

**Comment by DzikuVx** [comment]
done in 3.0
