### ISSUE TITLE
Matek F405 Wing EEPROM save waypoint doesn't work

### ISSUE THREAD

**Issue by fahrvergnuugen** [iNavFlight/inav-configurator#711]
Waypoint missions can't be saved to the EEPROM on the Matek F405 Wing flight controller. Clicking save causes the log to say "EEPROM Saved" but no waypoints are stored.

I'm running version 2.1.0 with the 2.1.4 iNav configurator.

**Comment by Carlitoscadiz** [comment]
I  am running Inav 2.1.4 configurator with matek wing 405SE firmware 2.1.0 and have the same problem. Mission can not be  save to FC  neither write to EEPROM.  
I downgraded to Inav configurator 2.1.2 and Matek 405SE firmware 2.0 and still have the same problem.

**Comment by shellixyz** [comment]
@fahrvergnuugen Please see this: https://github.com/iNavFlight/inav/issues/4456#issuecomment-469752884
