### ISSUE TITLE
Modeled a Wing to replace the default Box 

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav-configurator#712]
Attached is the obj, you can chose the format in this page https://a360.co/2TiEye2
![image](https://user-images.githubusercontent.com/26075468/53954575-78a19d00-408b-11e9-98a3-d187908125bb.png)

[S800 wing.zip](https://github.com/iNavFlight/inav-configurator/files/2941048/S800.wing.zip)

**Comment by Arvycka** [comment]
A fixed wing model of any sort would be better than that ancient ugly box :)

**Comment by laurentopia** [comment]
> 
> 
> A fixed wing model of any sort would be better than that ancient ugly box :)

Except that

**Comment by laurentopia** [comment]
> 
> 
> A fixed wing model of any sort would be better than that ancient ugly box :)

The Fusion360 repository is public, feel free to change the model.

**Comment by Arvycka** [comment]
I meant the box in the configurator, your model is fine ☺

**Comment by Mateyhv** [comment]
Any way to replace the box with the S800 wing obj?

**Comment by DzikuVx** [comment]
It's a beuty of a open source that anybody can do it
