### ISSUE TITLE
matek f722-se problem althold

### ISSUE THREAD

**Issue by llucas33** [iNavFlight/inav-configurator#718]
hello,
I have the flight controller matek f722-se, in stabilized it goes well, the problem is when I put althold. It does not respond to the trhottle, it starts to accelerate and it does not respond to the gas stick until you cut engines with the stick to 0. Can it be pid problems or filters?
Thank you.

**Comment by shellixyz** [comment]
Althold mode is controlling the throttle. The base throttle (when level) is set by `nav_fw_cruise_thr`. The throttle used is `nav_fw_cruise_thr + pitch * nav_fw_pitch2chr`. The pitch stick in AH for fixed wing is used to request an increase/decrease in altitude, maximum set by `nav_manual_climb_rate`. You can set `nav_fw_allow_manual_thr_increase` to `ON` if you want to be able to increase the throttle manually.

Please refer to [this document](https://github.com/iNavFlight/inav/blob/master/docs/Cli.md) for more info about these settings.

The right place to ask this type of question is in the forums (RCGroups for example), iNav's group on Facebook or [iNav's telegram channel](https://t.me/INAVFlight)
