### ISSUE TITLE
[SOLVED]  INAV Failed to open serial port on WINDOWS

### ISSUE THREAD

**Issue by aletev** [iNavFlight/inav-configurator#726]
Hi everybody, for me was very hard to solve this "problem". Wasn't easy to find something about it. And as I shared it with a group of friends and they told me that for them was a problem too, I decided to write this lines.
I could solved it just for windows, not for ubuntu. (for the moment).
The key was [https://impulserc.com/pages/downloads](url).
Just this steps:
1) Download ImpulseRC Driver Fixer
2) Connect the FC to the usb.
3) Run ImpulseRC Driver Fixer. And wait until it connects to the FC and retrieves drivers info an update the loaded ones.
4) Restart... and now you can flash your FC. 
In my case is an OMNIBUS SD F4 V5. Flashed with OMNIBUSF4V3 (inav).

Bye.

**Comment by julienguegan** [comment]
I also have "Failed to open serial port" and try to use ImpulseRC driver but it gives me an error ... 
![impulseRC driver](https://user-images.githubusercontent.com/45081450/87424772-d37ec900-c5dc-11ea-8f40-4dd6163a067d.png) 

If someone has a solution for this, it would be great !

**Comment by DzikuVx** [comment]
@julienguegan probably a different program is blocking COM port

**Comment by julienguegan** [comment]
@DzikuVx Did you already encountered this error ? I can't figure out if there is something blocking the COM port ...

I also try to launch zadig but in devices list I don't have the "STM32 Virtual COM port"
![image](https://user-images.githubusercontent.com/45081450/88054281-5cf24600-cb5d-11ea-8b47-8a37692fb23e.png)

**Comment by shenshihehe** [comment]
nice suggesition
