### ISSUE TITLE
Feature request: analog temperature sensor support

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav-configurator#739]
I would like to request this option. To keep the weight and size down in smaller models. That also use smaller devices like ESC's.
In the case of an LM75 breakout board. It is almost as large as the ESC, which blocks its cooling efficiency.
While a thermistor is very small and can be slipped under the heat shrink tube of the ESC, with ease.

The RSSI ADC pin on most Flight Controllers that is not used by many of us. Who put RSSI/LQ on a radio channel. Could be the option for this.
And it only uses 2 wires instead of four. To simplify the application.

![20190401_204232](https://user-images.githubusercontent.com/47995726/55347764-499f0f80-5501-11e9-8f19-fedd2dfac7d6.jpg)

**Comment by shellixyz** [comment]
@digitalentity Could you please move this issue to the firmware repos

**Comment by Jetrell** [comment]
Sorry about that @shellixyz 
I was not sure which to place the request under, cause it is see in both Configurator and firmware.
I'll close it here and re-open it there.
