### ISSUE TITLE
Motor Tab - Offset on the servos

### ISSUE THREAD

**Issue by lichtl** [iNavFlight/inav-configurator#742]
Hi,

it seems that on the motor page the servo count is off.

![image](https://user-images.githubusercontent.com/1228155/55674425-e1f81400-58b4-11e9-95a5-418a05d07e79.png)
![image](https://user-images.githubusercontent.com/1228155/55674429-e9b7b880-58b4-11e9-870d-efbc8f7bce6f.png)

```
# diff

# version
# INAV/FF_F35_LIGHTNING 2.1.0 Feb 25 2019 / 16:46:34 (65b0ec142)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

# resources

# mixer
mmix 0  1.000  0.000  0.000  0.000
mmix 1  1.000  0.000  0.000  0.000

# servo mix
smix 0 3 0 50 0
smix 1 3 1 50 0
smix 2 4 0 -50 0
smix 3 4 1 50 0

# servo
servo 3 1000 2000 1634 -100
servo 4 1000 2000 1469 100
```

**Comment by shellixyz** [comment]
Well yes and no. Servo indexes start at 0. So servo 3 in the mixer is servo 4 in the servos tab (if servo index 0 is the first servo, servo index 3 is the fourth servo). Not the most straightforward I agree. Just explaining how it is.

**Comment by lichtl** [comment]
yes thought so as well. however would be probably better to have them consistent especially when the model is shown in top left which then result in more risk of confusion.

**Comment by DzikuVx** [comment]
Changed in #806
