### ISSUE TITLE
(New) Impact mini font

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav-configurator#746]
This font is modeled off the Impact font. But it has a smaller stature in all characters. To take up less OSD screen space. But is still easy to read at a glance. 
![Capture](https://user-images.githubusercontent.com/47995726/69862753-3beb9500-12ef-11ea-8899-3465da073753.PNG)

[Impact_mini.zip](https://github.com/iNavFlight/inav-configurator/files/3904774/Impact_mini.zip)
(updated 29.11.2019)

If any of the Dev's think it is worthy of a PR and to merge. Then feel free to do so.

**Comment by wx4cb** [comment]
i like it, but maybe make the stroke thinner a little some of the numbers seem a little "cramped"

**Comment by Jetrell** [comment]
@wx4cb Its only two pixels wide. If it goes to one pixel....it becomes like Default font.

The idea was to keep it FULL in its look, but still be a small in stature.  So that's the best it can be, with the available pixel density  :-) 
I find it looks better in the goggles than the preview here.

**Comment by wx4cb** [comment]
@Jetrell ok cool... hard to tell from the preview image
