### ISSUE TITLE
You need to upgrade your firmware before you can use the ... tab

### ISSUE THREAD

**Issue by careyer** [iNavFlight/inav-configurator#747]
Hi there,

I am new to iNAV and I have a copter with Nace32 ... I flashed the latest iNAV version for that board (1.7.3) but on each try to connect it will tell me "You need to upgrade your firmware before you can use the ... tab".... the CLI works flawlessly... but any of the other tabs wont

![INAV](https://user-images.githubusercontent.com/6156251/56320295-1e086000-6164-11e9-9152-ff060863e58c.JPG)

**Comment by DzikuVx** [comment]
Use Configurator 1.7.3

**Comment by DzikuVx** [comment]
https://github.com/iNavFlight/inav-configurator/releases/tag/1.7.3

**Comment by careyer** [comment]
@DzikuVx Thank you very much for pointing me in the right direction! Have a good day!
