### ISSUE TITLE
Can't upload OSD fonts with MacOS

### ISSUE THREAD

**Issue by spacyje** [iNavFlight/inav-configurator#748]
Hi,
I installed the latest version of inav 2.1.0 on a matek F722 card and I can't upload the font, it still blocks about half of the font upload, I did some research and I went to the configuration page to enable/disable the osd with lipo, without lipo but it's always the same.
On the 2.0 I didn't have this problem.
Any solution?

**Comment by jimokeane** [comment]
I also have this problem. I tried every possible thing I could think of based on other suggestions. OSD switch on/off. Making sure board had battery power, .etc. I found that no matter what the upload of the font stopped about at 300 / 500 or something like that. Font was then corrupted in the OSD! I went back to the previous version of the configurator and uploaded the old font. This upload works fine, but when you boot the F722 Wing, it shows a message that the font is invalid.

**Comment by jhyden** [comment]
I had the same problem with a f722se and a Mac. Went back to 2.0 and the upload works.

**Comment by shellixyz** [comment]
@spacyje @jimokeane Are you using MacOS ?

**Comment by jimokeane** [comment]
Yes - I am running MacOS 10.13.6 (17G6030)

**Comment by jhyden** [comment]
Same here

**Comment by JohnDevine** [comment]
Just commenting .. same here Mac os x, F722-se font load stalls at 304/512

**Comment by jfmrod** [comment]
Same here

**Comment by JohnDevine** [comment]
> Just commenting .. same here Mac os x, F722-se font load stalls at 304/512

Still in 2.2.0

**Comment by Flyboy369** [comment]
Same for me.  New to FPV, with iNav 2.2.0 font upload failed at 257/512 every time on my mac with matek F722-SE  Downloaded 2.0.0 and it worked great although when the fc boots up the OSD screen states "Invalid Font"

**Comment by fiam** [comment]
Just tested with the PR in #800, which fixes the problems on F3 with macOS, and it turns out it also fixes the problem for F722. We'll be shortly releasing configurator 2.2.1 with this change.

**Comment by DzikuVx** [comment]
2.2.1 released so we can close this. Thank you very much
