### ISSUE TITLE
I have the eachine Matek 405f board and inav configurator dont see it, i have BF4.0 on it

### ISSUE THREAD

**Issue by backman8571** [iNavFlight/inav-configurator#754]
I have the eachine Matek 405f board

It has BetaFlight 4.0

Why does the inav dont see the board

![inav](https://user-images.githubusercontent.com/45211794/56850272-d9986500-68c5-11e9-8fae-7157eb5a65cd.JPG)

Thanks

Per

**Comment by shellixyz** [comment]
iNav's configurator can't be used with Betaflight. You have to flash iNav on your board first

![image](https://user-images.githubusercontent.com/4030264/56851710-8e587380-6912-11e9-9211-f2171ae0ae48.png)
