### ISSUE TITLE
Issue with using Airbot with iNav, wont connect after flash.

### ISSUE THREAD

**Issue by oleost** [iNavFlight/inav-configurator#76]
Hi, having issue with using iNav after flash.
When if first got the Airbot F4 with MPU6000 I manage after a while getting to work with iNav, I tried changing some gyro sync settings and after that I cannot get it working again.

I tried flashing iNav 1.3, I tried flashing iNav 1.4 and Betaflight.

When flashing betaflight it just works, no need to install Zadig driver, its there already and I dont have multiple interfaces to install driver to. (interface 0 and interface 1) which shows up dual in device manager after I installed driver on both aswell.

With iNav I tried replacing driver, removing all driver etc etc.
iNav configurator is official from google store.

First I uninstalled all driver to start over:
![1 uninstalled all drivers](https://cloud.githubusercontent.com/assets/5670710/20942777/30d59db0-bbfd-11e6-8fd9-05dac086ac3a.PNG)

After that it did not work and I tried to replace interface 1 with WINUSB
![2 installed winusb on interface 1](https://cloud.githubusercontent.com/assets/5670710/20942778/30d5c3b2-bbfd-11e6-9624-8dc51ffe296f.PNG)

That did not work either so I tried to replace interface 0 aswell, this time I have now com ports to connect to.
![3 installed winusb on both interface](https://cloud.githubusercontent.com/assets/5670710/20942781/30dc9458-bbfd-11e6-8eea-c7edbe9e6f9c.PNG)
![4 installed winusb on interface 1_showinginterface0](https://cloud.githubusercontent.com/assets/5670710/20942780/30d68d60-bbfd-11e6-800c-2fad7aa5557f.PNG)

Flashed betaflight revo, everything is working without doing anything
![5 flashed with revo target betaflight without installing any drivers manually](https://cloud.githubusercontent.com/assets/5670710/20942779/30d6436e-bbfd-11e6-8cc4-4400dfb9a705.PNG)

And then I tried with iNav Revo target, that did not make any difference.
![6 flashed with inav revo target](https://cloud.githubusercontent.com/assets/5670710/20942776/30d573bc-bbfd-11e6-9824-f735122fce4a.PNG)
![7 flashed with inav revo target manually installed driver interface 1](https://cloud.githubusercontent.com/assets/5670710/20942783/30f05db2-bbfd-11e6-85c5-d2d41d428174.PNG)
![8 flashed with inav revo target manually installed driver on both interface](https://cloud.githubusercontent.com/assets/5670710/20942782/30edaa86-bbfd-11e6-9f75-228d69561b9d.PNG)

**Comment by oleost** [comment]
Not sure if this is the right place for the issue, if it should be at main github.

Also tried flashing iNav with betaflight configurator, did not help. Also tried flashing latest 1.5 development.

There is something wierd here, dunno if its only my setup or something else.

Also I cannot flash "full erase" since then it hangs on erasing, this is apperntly a known issue since the chip is locked. https://www.rcgroups.com/forums/showpost.php?p=35965420&postcount=384

I could try and unlock it but I would like to find out the issue first.

**Comment by DzikuVx** [comment]
I'd say it is somehow connected to driver. I remember I had to restore Windows to previous recovery point when I started to play whit F4 boards few times.

**Comment by oleost** [comment]
Hmm, wierd. But any reason to identify it different than just Revo ? 

Anyway will try and unlock the board. 

But still finds it wierd that when flashed with iNav it shows to different interfaces and only one when betaflight.

**Comment by DzikuVx** [comment]
Well, this is not REVO board. Motor 6 connected to different CPU pin, different sensors and so on... 
I think that VCP is not visible because wrong driver is loaded, not because config is wrong. After flashing with different firmware, all config is gone

**Comment by oleost** [comment]
Closing this one, probably user error. (Replaced wrong driver with zadig)

Will update here if I get it working without restoring windows / reinstalling Windows

**Comment by oleost** [comment]
Complete reinstall including driver packages from device manager, and then installed https://quadmeup.com/stm32-virtualcomport-driver-for-windows/ this driver did the trick for me.
