### ISSUE TITLE
ubuntu/Linux unable to access save/reboot buttons

### ISSUE THREAD

**Issue by wx4cb** [iNavFlight/inav-configurator#760]
under any form of linux (mainly using ubuntu 18.06) whenever I try to get to the buttons they don't show as shown in this picture. the window is maximised etc but there's no way to get at them

my screen resolution is shown in the xwininfo shell. This is obviously a resolution issue with the configurator not respecting WM sizes.

![image](https://user-images.githubusercontent.com/1495297/57183165-083eae80-6e77-11e9-82be-66c1b492d8f1.png)

**Comment by wx4cb** [comment]
https://imgur.com/ZrmPHO5

**Comment by wx4cb** [comment]
Bump

**Comment by shellixyz** [comment]
Looks like there is a minimum size for the window. Until this is fixed you should be able to move the window up to reach the save button by holding the super key, clicking anywhere on the window and dragging it up

**Comment by wx4cb** [comment]
i tried that but it wouldn't work on the smaller screen.

**Comment by DzikuVx** [comment]
#942 allows for 800x600 window size
