### ISSUE TITLE
Output Mapping problem

### ISSUE THREAD

**Issue by TTRNFPV** [iNavFlight/inav-configurator#761]
![57444626_285720068996487_5899564530869993472_n](https://user-images.githubusercontent.com/50282308/57190043-90d94f80-6f48-11e9-9a16-6abb416e6c83.jpg)

Use inav_2.1.0_OMNIBUSF4V6 firmware
The output map is out of order. Will the next version of firmware be fixed?

**Comment by DzikuVx** [comment]
fixed in #810 and will be a part of the next release
