### ISSUE TITLE
No map displayed on GPS tab with 2.1.4 launched from Chrome (re issue #664)

### ISSUE THREAD

**Issue by Ravid824** [iNavFlight/inav-configurator#763]
GPS tab is not displaying the MAP whee launching  the configurator from Chrome.
It works fine when lunching the standalone configurator.
Any intention to fix this issue?

**Comment by giacomo892** [comment]
Chrome apps are strongly limited and being phased out by google itself, so just use the standalone version.

**Comment by Ravid824** [comment]
thank you
