### ISSUE TITLE
Support sensor config

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav-configurator#77]
as is iNavFlight/inav/#744 

- [x] MSP_SENSOR_CONFIG
- [x] MSP_SET_SENSOR_CONFIG
- [x] MSP_SENSOR_STATUS

**Comment by digitalentity** [comment]
I've just finished `MSP_SENSOR_STATUS` in 7d2ef3a166c93430c768dd759ed07caf56780c9a. Sorry, didn't notice that you was working on this one as well :smile:

**Comment by DzikuVx** [comment]
done, closing
