### ISSUE TITLE
How does the configurator flash firmware without connecting the connector

### ISSUE THREAD

**Issue by liutairan** [iNavFlight/inav-configurator#784]
I have a question that how does the configurator flash firmware without connecting the boot connectors? 

I am trying to build a simple configurator program (with Python) to flash the firmware to SP Racing F3 boards. I found that when I use iNav configurator, I only need to connect the board via USB, then I can flash the firmware easily. But if I use another software "stm32flash" (https://sourceforge.net/p/stm32flash/wiki/Home/), then I need to connect the boot connectors.

So, what are the tips you use that can do the flash without connecting them? Thank you!

**Comment by shellixyz** [comment]
You can send `R` through the serial port to reboot into DFU (bootloader) then use dfu-util to flash a firmware

**Comment by liutairan** [comment]
> You can send `R` through the serial port to reboot into DFU (bootloader) then use dfu-util to flash a firmware

Thanks for the reply. What do you mean send `R` through the serial port?

**Comment by liutairan** [comment]
After a lot of trial and error, I finally had dfu-util installed. However, it cannot find my board while using `ls /dev/tty*` the device can be found as `/dev/tty.SLAB_USBtoUART`.

**Comment by liutairan** [comment]
I probably know how to do this now. Thanks.
