### ISSUE TITLE
Don't know how to make a pull request for up to 16 servos

### ISSUE THREAD

**Issue by Ralfde** [iNavFlight/inav-configurator#796]
I would like to make a pull request to use up to 16 servos instead of only max. 8. 
Maybe somebody could do the pull request for me.

servoMixerRuleCollection.js
let ServoMixerRuleCollection = function () {

    let self = {},
        data = [],
        maxServoCount = 16;

**Comment by DzikuVx** [comment]
INAV 2.3 will have 16 servos, I will try to make a PR for it in a next few days

**Comment by Ralfde** [comment]
Thanks a lot.
