### ISSUE TITLE
Old inav versionsdont communicate with new configurator (CC3D inav 1.7.3)

### ISSUE THREAD

**Issue by sppnk** [iNavFlight/inav-configurator#799]
Hi, trying to bring back to life some old CC3D boards I have flashed them with inav 1.7.3, but I have to use 1.7.3 configurator to make the setup, as new one gives  "configuration not received" error.

Not a big problem, just to note it. Thnks.

**Comment by DzikuVx** [comment]
This is by design. You can older Configurator from here https://github.com/iNavFlight/inav-configurator/releases
