### ISSUE TITLE
Paste dump file in CLI gives random errors

### ISSUE THREAD

**Issue by fremebondo** [iNavFlight/inav-configurator#805]
I am currently facing issues when restoring config like reported in #6 
I get 10 to 15 missed line each time I try to restore a dump.
I'm using INAV 2.2.0 on a SPF3 fc.

Would be possible to add a config value in INAV configurator so that a **configurable delay** is added after each newline?

**Comment by DzikuVx** [comment]
Configurator adds a 50m delay after each line by deafult.
