### ISSUE TITLE
Virus warning from windows defender

### ISSUE THREAD

**Issue by EdSmega** [iNavFlight/inav-configurator#811]
I am a new INAV user.  I installed it on 2 windows 10 computers and it worked on both until the latest Microsoft updates were applied to my desktop machine.  Inav stopped working and I got error messages about a virus.  Thinking I may have downloaded accidentally from a bad site, I deleted it and attempted to reload from github.  Now Windows defender won't allow the download to complete.  Message says threats found.   Before I deleted the previous install, the messages were to the effect that The software was downloaded from one of those bogus downloaders that bundles crap with your files.  Sorry I don't have the exact text anymore. attached is the screenshot from where I downloaded.    Error message from the notification error disappears when I activate my screen capture.

![inav download](https://user-images.githubusercontent.com/53020217/61409823-0b134200-a8b1-11e9-8c45-edab17d4bcd2.jpg)

**Comment by digitalentity** [comment]
Moved the issue to the configurator repository

**Comment by AnandNL** [comment]
I have had the same problem with the 64bit version, the 32 bit version works fine, the RC1 had the same problem. 

![inav](https://user-images.githubusercontent.com/30389313/61621119-9191a000-ac72-11e9-958e-8d5c46475963.PNG)
![inav virus](https://user-images.githubusercontent.com/30389313/61621136-99514480-ac72-11e9-81fd-ebb1d8f5cd59.PNG)

**Comment by EdSmega** [comment]
Good to know, thank you.  Next time I’ll just use the 32 bit version.  For now I managed to avoid the problem by creating a Defender exception for the Inav folder.


Ed

**Comment by DzikuVx** [comment]
Some antivir packages have false positive detection on NW.js packages. This is known problem. I suggest update virus definitions as the latest versions are no longer reporting
