### ISSUE TITLE
Unable to configure (pi)FF so it can be altered via adjustment

### ISSUE THREAD

**Issue by Pairan** [iNavFlight/inav-configurator#813]
**current situation V2.2.0**
The configurator  offers to alter xx-P, xx-I and xx-D values via the adjustments tab.

**Problem**
Currently the xx-FF value is missing in the [50 defined values](https://github.com/iNavFlight/inav/blob/master/docs/Inflight%20Adjustments.md#adjustment-function) so this can't be configured  (e.g. ROLL FF) and xx-D has no effect if it's altered in flight. 

**Desired behavior**
- Remove the xx-D entries in case they aren't needed anymore
- Add xx-FF entries to get in control
- Update [documentation](https://github.com/iNavFlight/inav/blob/master/docs/Inflight%20Adjustments.md#adjustment-function)

**Comment by Mateyhv** [comment]
Definitely would like to see the FF entries in the adjustment tab!

**Comment by avsaase** [comment]
This has been fixed a while ago
