### ISSUE TITLE
Matek F722-STD Looptime limitation

### ISSUE THREAD

**Issue by Elbarto** [iNavFlight/inav-configurator#819]
Hi,

I have a Matek F722-STD board with Inav 2.2.1 firmware on it and I can't figure out how to have a looptime greater than 1 Khz. I tried to toggle the sync with gyroscope looptime but it doesn't propose me to choose the gyro Looptime neither like on the Matek F4 board. I also changed the ESC protocol to Multishot but still no other option greater than 1 Khz for the looptime.

Am I doing something wrong or is it limited on purpose on the F7 board ?

Sorry if i'm posting this on the wrong place, and thanks for help.

**Comment by DzikuVx** [comment]
There is no limitation on looptime, I fly several F722 with looptimes > 2kHz. Probably you are not setting gyro LPF at 256Hz (Configuration page)
