### ISSUE TITLE
Motor tab - servos are not updated in real-time

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav-configurator#82]
When using a mix with servos (i.e. TRI or AIRPLANE) servo bars on the Motor tab are updated only when entering the tab.

**Comment by DzikuVx** [comment]
will take a look

**Comment by digitalentity** [comment]
Thanks! I only noticed because I was troubleshooting the tail servo on my TRI.

**Comment by DzikuVx** [comment]
#83 closing
