### ISSUE TITLE
Camstab on INAV

### ISSUE THREAD

**Issue by Conteet** [iNavFlight/inav-configurator#824]
I already use inav on FW and it fanstastic.

Now I want to use Inav on multicopter. actually it was for my final project to get bachelor degree at collage.

Basically it was multicopter for powerline inspection purpose.
which is need a gimbal to takes a stabillize footage.

here is the problem, I already assign the servo in pwm 5 & 6 (omnibus F4 v2 pro board)
to get my gimbal activated.

and also, I activated camstab mode on my auxilarry 5 switch.
but nothing happens.

do you guys have any idea about this?
or I was wrong from the beginning?

is it true that we need 2 separate flight controller? one for multicopter. and another for gimbal?
cant I just use 1 instead?

thanks in advance

**Comment by DzikuVx** [comment]
1. check if outputs are correctly assigned to servos in Mixer page
1. check is INAV is outputing anything on those servos in Motors page and if output moves
1. check if you gimbal controller has a FC input
1. INAV directly can drive only servo based gimbals. All other require gimbal controller
