### ISSUE TITLE
Problem with RTH throttle (iNAV)

### ISSUE THREAD

**Issue by edbfraga** [iNavFlight/inav-configurator#828]
Hi. I’m using a Matek F405 Wing for my Nano Talon FPV plane with the last iNAV firmware. 

Now the Problem:

I’m testing the RTH function in my stand and sometimes when I active the RTH function the throttle goes to 0% and sometimes it works fine, going to 100%. Why sometimes the throttle don’t work and sometimes it’s works. Is This because the minimum distance for RTH configuration? Because when i put the minimum distance for RTH in “0”, the problem is the same.
Someone can help me?

**Comment by DzikuVx** [comment]
yes, the most probably cause is min distance check
