### ISSUE TITLE
Weird ESC Protocol Issue

### ISSUE THREAD

**Issue by Fr4ctal-Dev** [iNavFlight/inav-configurator#832]
Hello
I don't know if I should put this here or in the inav repo, but bear with me.

I have a weird problem with a model of mine using the Matek F-405WING, a noname ESC that came with the model and a standard brushless 2207 motor.

My motor seems to only beep at about 3 beeps per second when I plug it in. After a lot of fiddling I've managed to figure out a temporary fix, basically I change the ESC protocol from standard to oneshot42, reboot, set it back to standard, reboot again and everything works fine, until I remove power from the ESC (I unplug the battery) this is obviously a massive problem and something I can only see being an issue with the actual inav software.

Any ideas?

**Comment by DzikuVx** [comment]
looka like a wird ESC issue. If calibration and "standard" ESC protocol ia not working I suggest getting a batter ESC
