### ISSUE TITLE
Weird Channel map

### ISSUE THREAD

**Issue by Blacksmith-Joe** [iNavFlight/inav-configurator#834]
So I can get the alierons and rudder to go the correct way when in manual mode, 

Flick to horizon mode and elevator will be correct and ailerons will be incorrect.

I can reverse things on Inav and in my taranis to get the correct movements in manual mode and in horizon mode but then the Chanel map says the ailerons are going the incorrect way but in real life they are going correct way and they are correcting the right way in horizon mode??? But it is showing the incorrect movement on the chanel map. Like wise I can flip it around so that the alierons are all correct but then the elevator is doing what the alierons was.

I've got the board orientation at 270 degrees which is correct, I checked against rag The nuts inav set up for his nano talon where he talks about board orientation as that was my first thought the problem could  be.

The board I'm using is a matek f411.

Help?
I'm so confused, I've never had any trouble with with all my omnibus f4 boards running inav before and now both my matek f411 boards are doing this.

**Comment by shellixyz** [comment]
Please make sure to follow this part of the Fixed Wing Guide: https://github.com/iNavFlight/inav/wiki/Fixed-wing-guide#step-3-setting-up-your-remote-endpoints-and-reversing-of-servos
