### ISSUE TITLE
REQUEST: show the build target in the configurator

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav-configurator#836]
like betaflight, on the top left corner it shows the build target so if i want to update the firmware it is simple, no need to dig on the web for info

**Comment by DzikuVx** [comment]
For future reference: please provide a screenshot/mock or any other visual aid

**Comment by laurentopia** [comment]
like the gray text below the betaflight logo
![image](https://user-images.githubusercontent.com/26075468/65795625-8c901780-e11f-11e9-94c4-540466606b80.png)

**Comment by jj-uk** [comment]
+1, saves having to go the cli and use the version command to find out what hardware and software my old models are running.

**Comment by MrD-RC** [comment]
In 6.0
