### ISSUE TITLE
Increase available mixer rules from 16 to 32 on F405-Wing: Safe to do?

### ISSUE THREAD

**Issue by SquashSquishSquaw** [iNavFlight/inav-configurator#837]
Hi folks,

for the setup of my full house glider on a Matek F405-Wing (Target: MATEKF405SE), I need more mixer rules than the available 16 rules.

In the file inav/src/main/flight/servos.h I have found two parameters:

#define MAX_SUPPORTED_SERVOS 8
#define MAX_SERVO_RULES (2 * MAX_SUPPORTED_SERVOS)

Increasing the constant factor from 2 to 4 hasn't done the job. Increasing the number of supported servos from 8 to 16 seems to work fine, however, I needed to disable the corresponding safety check in inav/src/main/build/build_config.c in order to be able to compile ("if MAX_PWM_SERVOS != MAX_SUPPORTED_SERVOS").

I'm aware this is a rather brute-force approach. So I'm wondering: Is it a safe thing to do? Or will I run into problems, like the FC running out of memory during flight? Or maybe, is there anything hard-coded that will lead to unexpected behavior of the software?

Many thanks in advance
Jenny

**Comment by DzikuVx** [comment]
INAV 2.3 which should be released in Q4 will have 16 servos and 32 rules
