### ISSUE TITLE
No Matek F411 WSE target in Inav configurator 2.2.1

### ISSUE THREAD

**Issue by benanerson** [iNavFlight/inav-configurator#840]
Hello,

While trying to set up my Matek F411 WSE flight controller, I noticed that their is no target for the Matek F411 WSE flight controller. On Matek's websie they specify the target as "MATEK411SE" however this target does not appear in the Inca configurator. 

Thank you! :)

![2019-10-06_094815](https://user-images.githubusercontent.com/56230627/66272480-33ab3800-e81f-11e9-84dd-5a1a72558933.png)

**Comment by DzikuVx** [comment]
This target will be released as INAV 2.3

**Comment by benanerson** [comment]
Hi DzikuVx,

Thanks for getting back to me. Is their an estimated release date for INAV 2.3 is? 

Thank you.

**Comment by unluckyfrog** [comment]
I've loaded 2.3 this morning and there is no Matek f411se target. Is there another target i can use?

**Comment by Grumpyrse** [comment]
Any update on this?

**Comment by DzikuVx** [comment]
@Grumpyrse INAV Configurator 2.3 and latest RC od INAV 2.3
