### ISSUE TITLE
Servo Numbering Inconsistency in 2.3.3 RC3

### ISSUE THREAD

**Issue by breadoven** [iNavFlight/inav-configurator#846]
In version 2.2.1 the servo mapping for a fixed wing is:

# mixer
mmix 0  1.000  0.000  0.000  0.000

# servo mix
smix 0 3 0 100 0 -1
smix 1 4 0 100 0 -1
smix 2 5 2 100 0 -1
smix 3 2 1 100 0 -1
smix 4 3 14 -120 0 -1
smix 5 4 14 120 0 -1

# servo
servo 2 1000 2000 1502 -100
servo 3 1000 2000 1500 -100
servo 4 1000 2000 1500 -100
servo 5 1000 2000 1500  100

The servos are numbered starting from 2 and this is the numbering shown in the Output mapping box in Configurator 2.2.1. However in Configurator 2.3.3 RC3 the servo numbering in the Output Mapping starts at 0 even though the servo numbering otherwise starts at 2 in the Servo Mixer box and Servo page.
Doesn't affect the way the servos work but is confusing. Seems to just affect the Output Mapping box.

**Comment by DzikuVx** [comment]
Servo ID is an arbitrary number that comes from legacy times. And it was always like that. If in previouis version you had a different servo id, that means you set it that way before
