### ISSUE TITLE
Firmware flash fails on version 2.3 RC2 

### ISSUE THREAD

**Issue by FelixvdDonk** [iNavFlight/inav-configurator#847]
Tested with Omnibus F4 V3.
Flashing inav 2.3 RC1 works on inav configurator 2.2.1 
It fails with inav configurator 2.3 RC2. 

When the FC goes into DFU mode the device is not recognized anymore with the error: UNKNOWN USB DEVICE - DEVICE DESCRIPTOR REQUEST FAILED in device manager

I tried fixing the drivers with zadig and impulse rc driver fixer tool. The only solution that worked was flashing with inav configurator 2.2.1

**Comment by DzikuVx** [comment]
This was already solved in RC3 that was release a few days ago. Please upgrade to 2.3.0-RC3
