### ISSUE TITLE
matek f765 . inav 2.3.0 -> ports tab not working. inav hangs 

### ISSUE THREAD

**Issue by holoduke** [iNavFlight/inav-configurator#849]
I had to upgrade my matek 765 board to inav 2.3.  In 2.2 telemetry is not working correctly.
In 2.3 everything seem to work alright. Except that in the configurater the port tab doesnt show any uarts. The configurator hangs and the only thing left is to press the disconnect button.
The speedybee app works fine and is showing all the ports. So as a work around i can use that app to configure the ports.
I am using the 2.3.0 macos version of the inav configurator.

**Comment by DzikuVx** [comment]
Tested Matek F765, INAV 2.3-RC2 and INAV Configurator 2.3.1 everything seems to be working correctly
