### ISSUE TITLE
Strange YAW values in motor mix

### ISSUE THREAD

**Issue by ds7060** [iNavFlight/inav-configurator#850]
Hello, I have just put some values in my motor mix to try the differential thrust and I got strange values after saving. I have tried both from GUI and CLI with the same results.
If I want 0,2 and -0,2, the values after saving are 0,20000000000000018 and -0,19000000000000007.
Is this normal?

**Comment by DzikuVx** [comment]
This is the result of converision from `float` to `int` and back. Just use
