### ISSUE TITLE
Configurator 2.3.1 Font manager selection issue 

### ISSUE THREAD

**Issue by Jetrell** [iNavFlight/inav-configurator#863]
The font manager in 2.3.1 works intermittently when selecting a new font. 
I tested it multiple time with alternate Configurators and firmware's with my Window 7 32bit PC that I take to the field.
The FC and Configurator have to be restarted to get a selection. And it doesn't seem possible to `open font file` at all.

![font manager](https://user-images.githubusercontent.com/47995726/69299093-cd119a80-0c63-11ea-8fc7-a264b61e80ff.PNG)

As a side note. This RED square below is now the toolbar icon for iNav.

![Capture](https://user-images.githubusercontent.com/47995726/69299608-19110f00-0c65-11ea-99be-8861781bb67d.PNG)

**Comment by DzikuVx** [comment]
OK, another issue with changes in nw.js and the fact that API over there is now changing...

**Comment by DzikuVx** [comment]
new configurator will be released very soon so closing

**Comment by Jetrell** [comment]
> 
> 
> new configurator will be released very soon so closing

Thanks Pawel.  I tested 2.3.2 and it works great :+1:
