### ISSUE TITLE
Servo number mismatch in configurator 2.3.1

### ISSUE THREAD

**Issue by Arvycka** [iNavFlight/inav-configurator#870]
Servo numbers in "Output mapping" section do not match servo numbers in "Servo mixer" section when a mixer preset is loaded.
![mixer](https://user-images.githubusercontent.com/25912739/69420076-a0728700-0d26-11ea-85eb-1ef44335a40a.JPG)

Why do we even need these servo numbers? Couldn't we just use Outputs? It complicates the mixer unnecessarily.

**Comment by DzikuVx** [comment]
They are not supposed to match. What you define in table is just an arbitrary number than later is converted to servo output number and actual output.
On top of that, some internal functions relay on servo index. 
If you want numbers to match, index them from 0.

**Comment by Arvycka** [comment]
But now that's even more confusing than it was before - now we have 3
numbers for a servo, an output, a number below it and a number in the
mixer. CLI uses mixer numbering. Output servo configuration also uses mixer
numbering, but outputs are paired with different non matching numbers? How
to track which servo is doing what?
The presets should be updated too and not to assign a random servo number
starting with 2
Also, at least in 2.2.1, servo autotrim ONLY works with default mapping
from a preset. You can number the servos whatever you like and control and
stabilization works fine, but servo autotrim only works correctly with
default mapping. Has this been fixed in 2.3?

2019-11-22, pn, 14:40 Paweł Spychalski <notifications@github.com> rašė:
