### ISSUE TITLE
No Inav target for matek f411 wse

### ISSUE THREAD

**Issue by Grumpyrse** [iNavFlight/inav-configurator#872]
After updating inav to 2.3.1 there is still no target for the matek f411 wse board.
Will this be rectified, or shall i continue to use the standard f411 target

**Comment by Jetrell** [comment]
@Grumpyrse  Its there.
The firmware for the F411WSE has not come out before. So it will not be found under stable targets unit the full version of 2.3 is released.
You have to select `Show Unstable Releases` .

![Capture](https://user-images.githubusercontent.com/47995726/69464012-45e23500-0dd1-11ea-81ee-5d5af8dfbbc5.PNG)

**Comment by Grumpyrse** [comment]
@Jetrell Thankyou, I had a blonde moment :)
