### ISSUE TITLE
2.3.3 Release documentation is misleading

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#905]
2.3.3 Release documentation  states  that the  iFlight SucceX-E F4 Stack is "recommended hardware".  We do not have a target for this device : https://github.com/iNavFlight/inav/pull/5314

Please remove this recommendation (here and for the 2.4 release).

**Comment by giacomo892** [comment]
BETAFLIGHTF4 target is the one for this board

**Comment by stronnag** [comment]
Thanks.
