### ISSUE TITLE
Configurator 2.3.2 Bluetooth Issues

### ISSUE THREAD

**Issue by Zangetsu57** [iNavFlight/inav-configurator#928]
I've been using a BT module with iNav for quite some time.  An issue arose when I upgraded from 2.1.4 to 2.2.x.  When a change is made and the FC reboots, I can no longer connect to the BT module.  Restarting the iNav Configurator allows me to reconnect, but it's quite annoying.  Note that this issue is present in Configurator 2.3.2 as well.  This issue is not present when connecting via USB.

**Comment by DzikuVx** [comment]
probably fixed by #931
