### ISSUE TITLE
Wrong inav-configurator version on download page

### ISSUE THREAD

**Issue by swepet** [iNavFlight/inav-configurator#945]
INAV-Configurator_linux64_2.4.1.tar.gz
INAV-Configurator_linux32_2.4.1.tar.gz

I have tried the files above and and they are not 2.4.1 
2020-03-14 @ 12:02:55 -- Running - OS: Linux, Chrome: 75.0.3770.142, Configurator: 2.4.0
And tells there is a new version available..

**Comment by DzikuVx** [comment]
After
