### ISSUE TITLE
nwjs helper used by inav configurator locks cpu at 99%. In Setup view

### ISSUE THREAD

**Issue by jackooooo** [iNavFlight/inav-configurator#949]
Inav configurator 2.4.1. MacOSX 10.13.4. Matek 405 Wing latest firmware
Configurator locks up when connected to Setup and FC.

If you connect to FC and then quickly go to any other area than Setup you can configure as normal. Soon as you switch back to Setup view nwjs helper goes back 99% and configurator locks up.

Seems to be related to this issue in NWJS helper library:
https://github.com/nwjs/nw.js/issues/2372

Which version of nwjs are you using? I had a similar issue with another app previously, a VPN app called Private Internet Access. They stopped using the nwjs library in later versions. 

![Screen Shot 2020-04-03 at 1 26 39 am](https://user-images.githubusercontent.com/37430938/78262995-1b597300-754d-11ea-822b-f18dc633837c.jpg)
[Sample of nwjs Helper.zip](https://github.com/iNavFlight/inav-configurator/files/4421778/Sample.of.nwjs.Helper.zip)

**Comment by DzikuVx** [comment]
INAC Configurator 2.5 uses an updated NW.js version: 0.42.2. Hopefully it will solve the issue
