### ISSUE TITLE
Allow re-ordering of modes page

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav-configurator#963]
Currently the modes page is a bit of a jumble, making it harder to see the set modes up; but even more so help other people with issues.

If the modes could be re-ordered by the user, that would be great. However, if not perhaps group the modes in a more user friendly way. For example:

Arm
Manual
Horizon
Angle
NAV RTH
NAV POSHOLD
NAV CRUISE
NAV ALTHOLD
NAV WP
etc.... 

The most used things closer to the top. Then grouped together appropriately; like flight modes, navigation, tuning, OSD, accessories (for example cam control, LEDs and beeper).

**Comment by robertha64** [comment]
Good idea, even the re-arangement will be very good.
+1

**Comment by wx4cb** [comment]
i mentioned a similar thing a couple years ago that was effectively ignored :D

https://github.com/iNavFlight/inav-configurator/issues/555

**Comment by rsilk1949** [comment]
I would prefer the sort order to be by Channel #.
When I am checking for example a 3 way switch, it is often necessary to scroll the mode page up & down to check the PWM values are set as expected.

**Comment by MrD-RC** [comment]
But surely all the modes on that switch will be the same type of mode?  So this would save scrolling

![image](https://user-images.githubusercontent.com/17590174/99187364-24026080-274e-11eb-85e2-63865c6cfcc2.png)
