### ISSUE TITLE
Goes to Configuration menu when clicking "Save and reboot"

### ISSUE THREAD

**Issue by tomidland** [iNavFlight/inav-configurator#97]
When you click the "Save and Reboot" button in Ports, Failsafe and Blackbox screens, it opens the Configurator screen. Not really a bug, but it gets annoying. :)

**Comment by DzikuVx** [comment]
@tomidland which board is it? VCP ?

**Comment by tomidland** [comment]
I use SPRACINGF3 with virtual com port (usb cable).

**Comment by tomidland** [comment]
I believe I installed this some time ago: STM32 Virtual COM Port Driver. http://www.st.com/en/development-tools/stsw-stm32102.html

**Comment by DzikuVx** [comment]
I think this issue is fixed in future Configurator 1.6
If not, doi not hesitate to reopen
