### ISSUE TITLE
Configurator 2.5.0 rc 1 - OSD Tab - Alarms - Temperature Labels

### ISSUE THREAD

**Issue by GregMichalski** [iNavFlight/inav-configurator#985]
OSD Tab - Under Alarms there are 2 instances of Minimum Baro Temp. Presume second instance should actually be minimum ESC temp.
![Issue001](https://user-images.githubusercontent.com/65134608/81509873-af042900-92db-11ea-803c-1d6677697708.jpg)

**Comment by DzikuVx** [comment]
will be done in RC2

**Comment by Jetrell** [comment]
@DzikuVx  When you say... done in RC2. Do you mean FW RC2? 
I would have thought Configurator RC2 would have fixed it. 
But it still displays `Minimum Baro temperature` alarm twice. The second should be` Minimum ESC temperature`.
 
![Capture](https://user-images.githubusercontent.com/47995726/81756421-0df5b800-94ff-11ea-9d55-5d6cfcd03710.PNG)

Thanks

**Comment by DzikuVx** [comment]
@giacomo892

**Comment by DzikuVx** [comment]
In that case fixed in 36e6cf38b16a9bc3a6f50923f036c38376f00074 and will be released with final

**Comment by Jetrell** [comment]
@giacomo892 @DzikuVx  Thanks guys :+1:
