### ISSUE TITLE
 Problem with "Omnibus F3" Inav 2.5.0RC1

### ISSUE THREAD

**Issue by Feldsalat** [iNavFlight/inav-configurator#987]
Conficurator 2.5.0RC1 and Inav 2.5.0RC1 
I cannot open the Advanced tuning tab with Omnibus F3 board. Configurator hangs with: "Waiting for data" Matek F405 and older Firmware on Omnibus F3 works fine.

**Comment by Sined216** [comment]
Configurator 2.5.0RC1, 2.5.0RC2 and inav 2.5.0RC1 matek F405SE
Same proplem on Configuration tab.

**Comment by stronnag** [comment]
Probably due to the removal of MR braking and the configurator not having read the release notes on this topic
