### ISSUE TITLE
Map and Direction Arrow is not showing in configurator 2.5 

### ISSUE THREAD

**Issue by NasirHayat** [iNavFlight/inav-configurator#988]
I Found a bug in the new version of the configurator. As you move in Mission Control Tab There is a Map and arrow sign (which show heading of dron on map) it is really useful feature when you going to set the orientation of the compass. This the map and heading arrow was working fine with older version 2.4.1 but not working in 2.5. I think this the best way to double-check compass orientation and calibration is fine if this mission control options works fine. 
![inav](https://user-images.githubusercontent.com/3838274/81550733-184a7180-939a-11ea-9c05-059fb9b89e9e.PNG)

**Comment by DzikuVx** [comment]
![image](https://user-images.githubusercontent.com/966811/84366701-7eadf400-abd3-11ea-8b53-b9b30c1dbc2a.png)

Works like expected

**Comment by tourerjim** [comment]
> I Found a bug in the new version of the configurator. As you move in Mission Control Tab There is a Map and arrow sign (which show heading of dron on map) it is really useful feature when you going to set the orientation of the compass. This the map and heading arrow was working fine with older version 2.4.1 but not working in 2.5. I think this the best way to double-check compass orientation and calibration is fine if this mission control options works fine.
> ![inav](https://user-images.githubusercontent.com/3838274/81550733-184a7180-939a-11ea-9c05-059fb9b89e9e.PNG)

Mines same on two quads I've setup now and can't work it out, get the Map GPS tab but not Missions tab

**Comment by tourerjim** [comment]
Solved, you have to keep zooming out
