### ISSUE TITLE
Gyro_lpf hz resets gyro looptime to 500Hz when changed

### ISSUE THREAD

**Issue by tomidland** [iNavFlight/inav-configurator#99]
When changing the "Gyroscope LPF cutoff frequency", it resets the "Gyroscope task frequency" to 500Hz in asynchronous mode.

**Comment by DzikuVx** [comment]
It is designed like this. Not all combinations of LPF/Gyro_task_frequency are allowed that's why LPF change resets the other setting

**Comment by tomidland** [comment]
Ah I see! But should it not keep its value if it is valid?

**Comment by DzikuVx** [comment]
Hmm... OK, makes sense

**Comment by andre92** [comment]
validation happens on flight controller, at least on F1 it does. Won't do faster than 500hz when using gps.

**Comment by DzikuVx** [comment]
Problem is with `gyro_sync_denominator`. Without logic that recomputes the change, simply changing from lpf 256HZ to 188Hz would create "unflyable" configuration. I will think about it in the future
